/**
 * Directivo aptitudes — Ejes 4 y 5 (gestión escolar + competencias pedagógicas).
 */
const {raw, push} = require("./directivo_aptitudes_part2");

const gestion = [
  {
    n: 61,
    stem: "Según la Guía 34 del MEN, ¿cuáles son las cuatro áreas de gestión que debe articular el Proyecto Educativo Institucional (PEI)?",
    options: [
      "Directiva, académica, administrativa-financiera y comunitaria",
      "Pedagógica, financiera, disciplinaria y deportiva",
      "Directiva, académica, deportiva y cultural",
      "Administrativa, comunitaria, financiera y tecnológica",
    ],
    correct: "A",
    expl: "La Guía 34 organiza la gestión institucional en estas cuatro áreas articuladas.",
    tags: ["guiaMen34", "ley115"],
  },
  {
    n: 62,
    stem: "¿Qué instancia del gobierno escolar, según la Ley 115 de 1994 y su decreto reglamentario, tiene la función de adoptar el manual de convivencia?",
    options: [
      "El Consejo Académico",
      "El Consejo Directivo",
      "El Personero Estudiantil",
      "La Asociación de Padres de Familia",
    ],
    correct: "B",
    expl: "El Consejo Directivo adopta el manual de convivencia como parte de sus funciones.",
    tags: ["ley115", "decreto1860"],
  },
  {
    n: 63,
    stem: "El Sistema Institucional de Evaluación de Estudiantes (SIEE) debe ser aprobado, según el Decreto 1290 de 2009, por:",
    options: [
      "El rector de manera unilateral",
      "El Consejo Directivo, tras el proceso de construcción participativa",
      "La Secretaría de Educación municipal",
      "Cada docente de forma independiente para su asignatura",
    ],
    correct: "B",
    expl: "El SIEE hace parte del PEI y se aprueba mediante acuerdo del Consejo Directivo.",
    tags: ["decreto1290", "ley115"],
  },
  {
    n: 64,
    stem: "¿Cuál es la principal diferencia funcional entre un rector y un coordinador en una institución educativa colombiana?",
    options: [
      "El coordinador tiene mayor jerarquía normativa que el rector",
      "El rector es el representante legal de la institución; el coordinador apoya la gestión académica y de convivencia bajo su orientación",
      "El coordinador es elegido por votación de los estudiantes",
      "No existen diferencias funcionales entre ambos cargos",
    ],
    correct: "B",
    expl: "El rector representa legalmente el establecimiento; el coordinador apoya la gestión bajo su orientación.",
    tags: ["ley715", "ley115"],
  },
  {
    n: 65,
    stem: "El Índice Sintético de Calidad Educativa (ISCE) se compone, entre otros factores, de:",
    options: [
      "Progreso, desempeño, eficiencia y ambiente escolar",
      "Asistencia, disciplina, infraestructura y presupuesto",
      "Matrícula, deserción, cobertura y nómina docente",
      "Evaluación docente, planta física, transporte y alimentación",
    ],
    correct: "A",
    expl: "Estos son los cuatro componentes definidos por el MEN para el ISCE.",
  },
  {
    n: 66,
    stem: "De acuerdo con el Decreto 1075 de 2015, ¿quién tiene la competencia para nombrar en período de prueba a los docentes que superan el concurso de méritos?",
    options: [
      "El rector de la institución educativa",
      "El nominador de la entidad territorial certificada",
      "La Comisión Nacional del Servicio Civil directamente",
      "El Consejo Directivo de cada institución",
    ],
    correct: "B",
    expl: "El nombramiento corresponde al nominador de la entidad territorial certificada.",
    tags: ["decreto1075"],
  },
  {
    n: 67,
    stem: "¿Cuál es el instrumento que orienta la organización pedagógica, administrativa y de gestión de una institución educativa, según la Ley 115 de 1994?",
    options: [
      "El Manual de Convivencia",
      "El Proyecto Educativo Institucional (PEI)",
      "El Plan Operativo Anual",
      "El Sistema Institucional de Evaluación",
    ],
    correct: "B",
    expl: "El PEI es el instrumento marco según el artículo 73 de la Ley 115.",
    tags: ["ley115"],
  },
  {
    n: 68,
    stem: "Según el Decreto 1860 de 1994, ¿cuáles son los órganos del gobierno escolar en toda institución educativa?",
    options: [
      "Rector, Consejo Directivo y Consejo Académico",
      "Rector, coordinador y secretario académico",
      "Consejo Directivo, Asociación de Padres y personero estudiantil",
      "Rector, Consejo Estudiantil y Contraloría Estudiantil",
    ],
    correct: "A",
    expl: "El Decreto 1860 establece estos tres órganos como los del gobierno escolar.",
    tags: ["decreto1860", "ley115"],
  },
  {
    n: 69,
    stem: "¿Cuál es la función principal del personero estudiantil, según la Ley 115 de 1994?",
    options: [
      "Representar al Consejo Directivo ante la Secretaría de Educación",
      "Promover el ejercicio de los derechos y deberes de los estudiantes",
      "Definir el currículo institucional",
      "Aprobar el presupuesto anual de la institución",
    ],
    correct: "B",
    expl: "Es la función central del personero, elegido por votación entre los estudiantes.",
    tags: ["ley115", "decreto1860"],
  },
  {
    n: 70,
    stem: "El Fondo de Servicios Educativos (FSE), compilado hoy en el Decreto 1075 de 2015, es administrado principalmente por:",
    options: [
      "El Consejo Directivo, a través del rector como ordenador del gasto",
      "La Secretaría de Educación municipal exclusivamente",
      "La Asociación de Padres de Familia",
      "El Consejo Académico",
    ],
    correct: "A",
    expl: "El rector actúa como ordenador del gasto, con la aprobación presupuestal del Consejo Directivo.",
    tags: ["decreto1075", "ley715"],
  },
  {
    n: 71,
    stem: "¿Qué establece la Ley 715 de 2001 respecto a los recursos del Sistema General de Participaciones (SGP) para educación?",
    options: [
      "Elimina la financiación estatal de la educación pública",
      "Define la distribución de recursos entre la Nación y las entidades territoriales para la prestación del servicio educativo",
      "Centraliza toda la contratación docente en el Ministerio de Educación",
      "Regula exclusivamente la evaluación de estudiantes",
    ],
    correct: "B",
    expl: "La Ley 715 organiza el sistema de transferencias y competencias entre niveles de gobierno.",
    tags: ["ley715"],
  },
  {
    n: 72,
    stem: "Según la Guía 34 del MEN, la autoevaluación institucional anual tiene como propósito principal:",
    options: [
      "Sancionar a los docentes con menor desempeño",
      "Identificar fortalezas y oportunidades de mejora en las cuatro áreas de gestión, como insumo para el plan de mejoramiento",
      "Reemplazar la evaluación de los estudiantes",
      "Definir el monto del presupuesto anual",
    ],
    correct: "B",
    expl: "Es la base del ciclo de mejoramiento continuo propuesto por el MEN.",
    tags: ["guiaMen34"],
  },
  {
    n: 73,
    stem: "¿Qué instancia del gobierno escolar tiene, entre sus funciones según el Decreto 1860, servir de órgano consultivo en la revisión del currículo?",
    options: [
      "El Consejo Directivo",
      "El Consejo Académico",
      "El Consejo de Padres",
      "La Contraloría Estudiantil",
    ],
    correct: "B",
    expl: "El Consejo Académico orienta la actividad pedagógica y revisa el currículo institucional.",
    tags: ["decreto1860", "ley115"],
  },
  {
    n: 74,
    stem: "El Sistema Especial de Carrera Docente regulado por el Decreto 1278 de 2002 aplica a:",
    options: [
      "Todos los docentes sin importar la fecha de su vinculación",
      "Los docentes y directivos docentes que ingresaron a la carrera a partir de junio de 2002",
      "Únicamente a los rectores de instituciones privadas",
      "Los docentes vinculados antes de 1979",
    ],
    correct: "B",
    expl: "El Decreto 1278 rige a quienes ingresaron desde su expedición; el 2277 rige a los vinculados antes.",
    tags: ["decreto1278"],
  },
  {
    n: 75,
    stem: "Según el Decreto 1290 de 2009, ¿cuál es una de las escalas de valoración que toda institución debe incluir en su SIEE, para efectos de homologación nacional?",
    options: [
      "Una escala cualitativa de cinco niveles obligatoria",
      "La escala nacional: Desempeño Superior, Alto, Básico y Bajo",
      "Una escala numérica de 1 a 100 obligatoria",
      "La institución no está obligada a reportar ninguna escala nacional",
    ],
    correct: "B",
    expl: "El Decreto 1290 exige incluir la escala de valoración nacional para facilitar la movilidad.",
    tags: ["decreto1290"],
  },
  {
    n: 76,
    stem: "¿Cuál es la instancia que suele actuar como segunda instancia dentro de la institución frente a las reclamaciones de los estudiantes sobre su evaluación, en el marco del SIEE?",
    options: [
      "El docente que asignó la calificación, sin posibilidad de otra instancia",
      "El Consejo Académico",
      "La Personería Municipal",
      "El Ministerio de Educación Nacional",
    ],
    correct: "B",
    expl: "El Consejo Académico suele actuar como segunda instancia en reclamos sobre evaluación.",
    tags: ["decreto1290", "decreto1860"],
  },
  {
    n: 77,
    stem: "La Ley 1620 de 2013 clasifica las situaciones que afectan la convivencia escolar en tres tipos. ¿Cuáles son?",
    options: [
      "Leves, graves y gravísimas",
      "Tipo I, Tipo II y Tipo III, según su gravedad e impacto",
      "Disciplinarias, académicas y familiares",
      "Internas, externas y mixtas",
    ],
    correct: "B",
    expl: "La Ley 1620 y su decreto reglamentario clasifican las situaciones en Tipo I, II y III.",
    tags: ["ley1620", "guiaMen49"],
  },
  {
    n: 78,
    stem: "Respecto al Índice Sintético de Calidad Educativa (ISCE), ¿qué mide el componente de Progreso?",
    options: [
      "El porcentaje de docentes con maestría",
      "La mejora de los resultados de la institución en pruebas Saber respecto al año anterior",
      "El número de estudiantes que permanecen en la jornada única",
      "El estado de la infraestructura física",
    ],
    correct: "B",
    expl: "El componente Progreso compara los resultados de la institución con los del año anterior.",
  },
  {
    n: 79,
    stem: "Según la normatividad vigente, ¿quién tiene la competencia de definir la planta de personal docente y administrativo de una institución educativa oficial?",
    options: [
      "El rector de la institución, de forma autónoma",
      "La entidad territorial certificada, con base en criterios técnicos definidos por el MEN",
      "El Consejo Directivo de cada institución",
      "La Comisión Nacional del Servicio Civil",
    ],
    correct: "B",
    expl: "La definición de la planta corresponde a la entidad territorial certificada.",
    tags: ["ley715", "decreto1075"],
  },
  {
    n: 80,
    stem: "¿Cuál es el propósito principal del Plan de Mejoramiento Institucional (PMI), derivado de la autoevaluación anual?",
    options: [
      "Sustituir el Proyecto Educativo Institucional",
      "Establecer metas, acciones y responsables para superar las debilidades identificadas en la autoevaluación",
      "Definir exclusivamente el calendario académico",
      "Reemplazar el Sistema Institucional de Evaluación de Estudiantes",
    ],
    correct: "B",
    expl: "El PMI traduce los hallazgos de la autoevaluación en un plan de acción concreto.",
    tags: ["guiaMen34"],
  },
];

for (const q of gestion) {
  push({
    id: `dir-apt-ges-${String(q.n).padStart(2, "0")}`,
    pillar: "pedagogico",
    module: "Gestión escolar",
    topic: "Gestión escolar · Directivo",
    stem: q.stem,
    options: q.options,
    correct: q.correct,
    expl: q.expl,
    tags: q.tags || [],
    dif: 3,
  });
}

const pedago = [
  {
    n: 81,
    stem: "El Diseño Universal para el Aprendizaje (DUA) propone que la planeación de clase debe ofrecer, desde el inicio, múltiples formas de:",
    options: [
      "Evaluación sumativa exclusivamente",
      "Representación, acción/expresión y motivación/compromiso",
      "Calificación numérica",
      "Distribución del tiempo de clase",
    ],
    correct: "B",
    expl: "Son los tres principios centrales del DUA para diseñar experiencias accesibles desde el diseño.",
  },
  {
    n: 82,
    stem: "La evaluación formativa se caracteriza principalmente por:",
    options: [
      "Asignar una calificación final al proceso de aprendizaje",
      "Brindar retroalimentación continua para ajustar la enseñanza y el aprendizaje durante el proceso",
      "Aplicarse únicamente al final del período académico",
      "Comparar el desempeño de los estudiantes entre sí",
    ],
    correct: "B",
    expl: "La evaluación formativa acompaña el proceso y orienta ajustes, a diferencia de la sumativa.",
  },
  {
    n: 83,
    stem: "Cuando un docente organiza una situación problema para que los estudiantes construyan conocimiento a partir de la exploración y el error, está aplicando principalmente un enfoque:",
    options: [
      "Conductista",
      "Constructivista",
      "Memorístico",
      "Tradicional-transmisionista",
    ],
    correct: "B",
    expl: "El constructivismo entiende el aprendizaje como construcción activa a partir de la exploración.",
  },
  {
    n: 84,
    stem: "Los Derechos Básicos de Aprendizaje (DBA) del MEN tienen como propósito principal:",
    options: [
      "Reemplazar los Estándares Básicos de Competencias",
      "Establecer los saberes y habilidades básicos que se espera que los estudiantes aprendan en cada grado, como referente para la planeación curricular",
      "Definir exclusivamente los criterios de evaluación docente",
      "Sustituir el Proyecto Educativo Institucional",
    ],
    correct: "B",
    expl: "Los DBA son un referente de planeación curricular, complementario a los Estándares.",
  },
  {
    n: 85,
    stem: "En un aula con estudiantes en condición de discapacidad, el Plan Individual de Ajustes Razonables (PIAR) tiene como finalidad:",
    options: [
      "Excluir al estudiante de las evaluaciones institucionales",
      "Definir los apoyos y ajustes específicos que garanticen su participación y aprendizaje en igualdad de condiciones",
      "Trasladar al estudiante a una institución de educación especial de forma obligatoria",
      "Reemplazar el informe académico regular del estudiante",
    ],
    correct: "B",
    expl: "El PIAR identifica barreras y define apoyos concretos, sin excluir al estudiante del proceso regular.",
    tags: ["decreto1421"],
  },
  {
    n: 86,
    stem: "Una rúbrica de evaluación es una herramienta pedagógica que principalmente permite:",
    options: [
      "Ocultar los criterios de evaluación al estudiante hasta el final del período",
      "Describir niveles de desempeño con criterios explícitos y comunicables al estudiante",
      "Reemplazar por completo la retroalimentación oral del docente",
      "Aplicarse únicamente en evaluaciones de matemáticas",
    ],
    correct: "B",
    expl: "La rúbrica hace explícitos los criterios y niveles de desempeño esperados.",
  },
  {
    n: 87,
    stem: "La Cátedra de la Paz, establecida por la Ley 1732 de 2014, tiene como propósito principal:",
    options: [
      "Reemplazar el área de ciencias sociales",
      "Fomentar el desarrollo de competencias ciudadanas y una cultura de paz en la comunidad educativa",
      "Sustituir el manual de convivencia",
      "Ser evaluada exclusivamente en pruebas Saber 11",
    ],
    correct: "B",
    expl: "Busca desarrollar competencias para la convivencia pacífica, como parte de la formación ciudadana.",
  },
  {
    n: 88,
    stem: "El Proyecto Ambiental Escolar (PRAE) se caracteriza principalmente por:",
    options: [
      "Ser un área independiente con intensidad horaria propia",
      "Ser un proyecto pedagógico transversal que articula la dimensión ambiental con distintas áreas del currículo",
      "Aplicarse únicamente en zonas rurales",
      "Reemplazar el Proyecto Educativo Institucional",
    ],
    correct: "B",
    expl: "Los proyectos pedagógicos transversales, como el PRAE, atraviesan varias áreas sin ser una asignatura aparte.",
  },
  {
    n: 89,
    stem: "La planeación curricular por competencias se diferencia de un enfoque exclusivamente por contenidos porque:",
    options: [
      "Prescinde por completo de los contenidos disciplinares",
      "Articula saberes, habilidades y actitudes que el estudiante debe movilizar para resolver situaciones",
      "Se centra únicamente en la memorización de conceptos",
      "Elimina la necesidad de evaluación",
    ],
    correct: "B",
    expl: "Un enfoque por competencias integra saber, saber hacer y saber ser, no solo contenidos.",
  },
  {
    n: 90,
    stem: "Según la taxonomía de Bloom (revisada), un verbo asociado a un nivel superior de pensamiento sería:",
    options: ["Identificar", "Recordar", "Evaluar", "Listar"],
    correct: "C",
    expl: "'Evaluar' corresponde a un nivel superior de pensamiento, a diferencia de 'recordar' o 'identificar'.",
  },
  {
    n: 91,
    stem: "El aprendizaje basado en proyectos (ABP) se caracteriza principalmente por:",
    options: [
      "La memorización de contenidos mediante repetición",
      "La resolución de un problema o pregunta auténtica a través de un producto final significativo para el estudiante",
      "La evaluación exclusivamente mediante exámenes escritos",
      "La ausencia total de planeación docente",
    ],
    correct: "B",
    expl: "El ABP parte de una pregunta o reto real que orienta el proceso hacia un producto tangible.",
  },
  {
    n: 92,
    stem: "Los Estándares Básicos de Competencias, emitidos por el MEN, tienen como función principal:",
    options: [
      "Reemplazar la autonomía curricular de las instituciones",
      "Establecer criterios comunes sobre lo que los estudiantes deben saber y saber hacer en cada área y grupo de grados",
      "Definir el manual de convivencia institucional",
      "Sustituir las pruebas Saber",
    ],
    correct: "B",
    expl: "Son un referente nacional de calidad que orienta, sin reemplazar, la autonomía curricular.",
  },
  {
    n: 93,
    stem: "La flexibilización curricular en el contexto de la inclusión educativa implica principalmente:",
    options: [
      "Reducir las expectativas de aprendizaje para todos los estudiantes del grupo",
      "Ajustar tiempos, metodologías o formas de evaluación sin renunciar a los propósitos esenciales del aprendizaje",
      "Eliminar la evaluación para los estudiantes con discapacidad",
      "Aplicarse únicamente en instituciones de educación especial",
    ],
    correct: "B",
    expl: "La flexibilización ajusta el 'cómo' sin renunciar a los propósitos de fondo del aprendizaje.",
    tags: ["decreto1421"],
  },
  {
    n: 94,
    stem: "El aprendizaje significativo, según la perspectiva ausubeliana, ocurre principalmente cuando:",
    options: [
      "El estudiante memoriza información de forma aislada",
      "El nuevo conocimiento se relaciona de manera sustancial con los saberes previos del estudiante",
      "El docente expone el contenido sin ninguna interacción",
      "La evaluación se realiza únicamente al final del período",
    ],
    correct: "B",
    expl: "Idea central de Ausubel: anclar el nuevo aprendizaje en estructuras cognitivas previas.",
  },
  {
    n: 95,
    stem: "La metacognición en el aula se refiere principalmente a:",
    options: [
      "La capacidad del estudiante de reflexionar y regular su propio proceso de aprendizaje",
      "La evaluación que el docente hace del grupo completo",
      "El uso exclusivo de herramientas digitales en clase",
      "La memorización de conceptos abstractos",
    ],
    correct: "A",
    expl: "La metacognición implica que el estudiante piense sobre su propio pensamiento y ajuste estrategias.",
  },
  {
    n: 96,
    stem: "El trabajo colaborativo en el aula, a diferencia del trabajo simplemente grupal, se caracteriza por:",
    options: [
      "La ausencia total de roles definidos",
      "Una interdependencia positiva entre los integrantes, con responsabilidad individual y colectiva sobre el resultado",
      "La evaluación exclusivamente individual sin ningún componente grupal",
      "La eliminación del rol del docente durante la actividad",
    ],
    correct: "B",
    expl: "El trabajo verdaderamente colaborativo exige interdependencia y responsabilidad compartida.",
  },
  {
    n: 97,
    stem: "La diferenciación pedagógica en el aula busca principalmente:",
    options: [
      "Aplicar la misma actividad, en el mismo tiempo, a todos los estudiantes sin excepción",
      "Ajustar contenidos, procesos o productos según las necesidades y ritmos de aprendizaje de los estudiantes",
      "Separar físicamente a los estudiantes según su rendimiento académico de forma permanente",
      "Reemplazar la evaluación formativa por evaluación sumativa",
    ],
    correct: "B",
    expl: "La diferenciación responde a la diversidad del aula ajustando distintos elementos del proceso.",
  },
  {
    n: 98,
    stem: "El Proyecto de Vida, como estrategia pedagógica en la educación media, busca principalmente:",
    options: [
      "Definir de manera obligatoria la carrera profesional del estudiante",
      "Acompañar al estudiante en la reflexión sobre sus intereses, metas y decisiones futuras",
      "Reemplazar la orientación vocacional por pruebas estandarizadas",
      "Ser evaluado únicamente en el área de ética",
    ],
    correct: "B",
    expl: "Es un proceso de acompañamiento y reflexión, no una definición vocacional obligatoria.",
  },
  {
    n: 99,
    stem: "La Educación Sexual, como proyecto pedagógico transversal obligatorio según la normatividad colombiana, debe abordarse principalmente desde:",
    options: [
      "Un enfoque exclusivamente biológico y reproductivo",
      "Un enfoque integral que incluya dimensiones biológicas, socioafectivas y de derechos",
      "Una sola sesión anual a cargo del área de ciencias naturales",
      "La exclusión de los padres de familia del proceso",
    ],
    correct: "B",
    expl: "El enfoque integral, con participación de la comunidad educativa, es el esperado.",
  },
  {
    n: 100,
    stem: "Un docente diseña una rúbrica con niveles de desempeño claros y la comparte con los estudiantes antes de iniciar una actividad evaluativa. Esta práctica favorece principalmente:",
    options: [
      "La opacidad de los criterios de evaluación",
      "La transparencia del proceso y la autorregulación del estudiante frente a lo que se espera de él",
      "La eliminación de la retroalimentación docente",
      "La reducción del tiempo dedicado a la planeación",
    ],
    correct: "B",
    expl: "Compartir los criterios previamente fortalece la transparencia y la autorregulación del estudiante.",
  },
];

for (const q of pedago) {
  push({
    id: `dir-apt-ped-${String(q.n).padStart(2, "0")}`,
    pillar: "pedagogico",
    module: "Competencias pedagógicas",
    topic: "Competencias pedagógicas · Directivo",
    stem: q.stem,
    options: q.options,
    correct: q.correct,
    expl: q.expl,
    tags: q.tags || [],
    dif: 2,
  });
}

module.exports = {raw, push};
