/**
 * Directivo aptitudes — Ola 2: Cuantitativo (121–140) + Blandas (141–160).
 */
const {raw, push} = require("./directivo_aptitudes_part4");

const cuant = [
  {
    n: 121,
    stem: "Una institución tiene 3 sedes con 420, 380 y 310 estudiantes. Si se debe asignar un refrigerio adicional per cápita de $1.200 diarios para todos, ¿cuál es el costo diario total?",
    options: ["$1.332.000", "$1.200.000", "$1.280.000", "$1.400.000"],
    correct: "A",
    expl: "420 + 380 + 310 = 1.110 estudiantes. 1.110 × $1.200 = $1.332.000.",
  },
  {
    n: 122,
    stem: "En una jornada de evaluación docente, se citan 45 docentes en grupos de 9 para las entrevistas. ¿Cuántos grupos se conforman?",
    options: ["4", "5", "6", "9"],
    correct: "B",
    expl: "45 ÷ 9 = 5 grupos.",
  },
  {
    n: 123,
    stem: "El PEI de una institución establece que el 60% de las horas de libre inversión se destinan a proyectos transversales. Si hay 20 horas de libre inversión al mes, ¿cuántas horas se destinan a esos proyectos?",
    options: ["10", "11", "12", "14"],
    correct: "C",
    expl: "20 × 0,60 = 12 horas.",
  },
  {
    n: 124,
    stem: "Un colegio tiene una tasa de aprobación del 88% sobre 625 estudiantes evaluados. ¿Cuántos estudiantes no aprobaron?",
    options: ["65", "70", "80", "75"],
    correct: "D",
    expl: "Aprobados = 625 × 0,88 = 550. No aprobados = 625 − 550 = 75.",
  },
  {
    n: 125,
    stem: "Se debe imprimir el manual de convivencia para 780 estudiantes, a razón de $850 por ejemplar. Si ya se imprimieron 300, ¿cuánto cuesta imprimir los restantes?",
    options: ["$408.000", "$380.000", "$396.000", "$420.000"],
    correct: "A",
    expl: "Restantes = 780 − 300 = 480. Costo = 480 × $850 = $408.000.",
  },
  {
    n: 126,
    stem: "Un coordinador debe distribuir 96 sillas nuevas entre 4 salones, de forma proporcional al número de estudiantes de cada uno: Salón A tiene 90, Salón B 60, Salón C 60 y Salón D 30 estudiantes (total 240). ¿Cuántas sillas corresponden al Salón B?",
    options: ["20", "24", "22", "26"],
    correct: "B",
    expl: "Salón B = 60/240 = 1/4. 96 × 1/4 = 24 sillas.",
  },
  {
    n: 127,
    stem: "En un simulacro de evacuación, un colegio de 900 estudiantes debe evacuar en grupos de 45 por punto de encuentro asignado. ¿Cuántos puntos de encuentro se requieren, como mínimo?",
    options: ["15", "18", "20", "22"],
    correct: "C",
    expl: "900 ÷ 45 = 20 puntos de encuentro.",
  },
  {
    n: 128,
    stem: "El presupuesto de una institución para material didáctico es de $18.000.000 al año, distribuido en partes iguales entre 4 períodos académicos. ¿Cuánto corresponde a cada período?",
    options: ["$4.000.000", "$4.250.000", "$4.750.000", "$4.500.000"],
    correct: "D",
    expl: "18.000.000 ÷ 4 = $4.500.000.",
  },
  {
    n: 129,
    stem: "Si el 42% de 950 estudiantes de una institución pertenece a estratos 1 y 2, ¿aproximadamente cuántos estudiantes son?",
    options: ["399", "380", "390", "410"],
    correct: "A",
    expl: "950 × 0,42 = 399 estudiantes.",
  },
  {
    n: 130,
    stem: "Un docente dicta 22 horas de clase a la semana. Si el año escolar tiene 40 semanas efectivas, ¿cuántas horas de clase dicta en total durante el año?",
    options: ["840", "880", "800", "900"],
    correct: "B",
    expl: "22 × 40 = 880 horas.",
  },
  {
    n: 131,
    stem: "En una prueba diagnóstica, un curso de 36 estudiantes obtuvo los siguientes resultados: 9 en nivel superior, 15 en nivel alto, 8 en nivel básico y el resto en nivel bajo. ¿Cuántos estudiantes quedaron en nivel bajo?",
    options: ["2", "3", "4", "5"],
    correct: "C",
    expl: "9 + 15 + 8 = 32. 36 − 32 = 4 estudiantes.",
  },
  {
    n: 132,
    stem: "Una rectoría debe repartir $2.400.000 en bonificaciones entre 8 docentes que participaron en un proyecto especial, en partes iguales. ¿Cuánto recibe cada uno?",
    options: ["$250.000", "$280.000", "$320.000", "$300.000"],
    correct: "D",
    expl: "2.400.000 ÷ 8 = $300.000.",
  },
  {
    n: 133,
    stem: "El aforo máximo del auditorio institucional es de 250 personas. Hay 180 personas confirmadas para un evento, y se espera un 20% adicional de acompañantes no confirmados sobre esas 180. ¿Cuántas personas se esperan en total, aproximadamente?",
    options: ["216", "198", "208", "225"],
    correct: "A",
    expl: "20% de 180 = 36. 180 + 36 = 216 personas esperadas.",
  },
  {
    n: 134,
    stem: "Una institución debe entregar 3 kits escolares por cada 5 estudiantes de los grados de transición. Si hay 145 estudiantes en transición, ¿cuántos kits se requieren?",
    options: ["80", "87", "84", "90"],
    correct: "B",
    expl: "145 ÷ 5 = 29 grupos de 5. 29 × 3 = 87 kits.",
  },
  {
    n: 135,
    stem: "El tiempo estimado para calificar una prueba de comprensión lectora es de 4 minutos por estudiante. Si dos docentes se reparten equitativamente la calificación de 130 pruebas, ¿cuánto tiempo, aproximadamente, le toma a cada uno?",
    options: ["3h 40min", "4h 00min", "4h 20min", "4h 40min"],
    correct: "C",
    expl: "130 ÷ 2 = 65 pruebas cada uno. 65 × 4 = 260 minutos = 4h 20min.",
  },
  {
    n: 136,
    stem: "Si la meta institucional es que el 75% de los estudiantes de grado once presenten las pruebas Saber en la fecha oficial, y la institución tiene 96 estudiantes en ese grado, ¿cuántos estudiantes representa esa meta?",
    options: ["68", "70", "76", "72"],
    correct: "D",
    expl: "96 × 0,75 = 72 estudiantes.",
  },
  {
    n: 137,
    stem: "Un colegio compró 60 tablets con un presupuesto de $54.000.000. Si el precio subió un 10% para la siguiente compra, ¿cuál sería el costo aproximado de comprar la misma cantidad de tablets al nuevo precio?",
    options: ["$59.400.000", "$56.500.000", "$57.800.000", "$60.000.000"],
    correct: "A",
    expl: "Precio unitario = 54.000.000 ÷ 60 = $900.000. Nuevo = 900.000 × 1,10 = $990.000. Total = 990.000 × 60 = $59.400.000.",
  },
  {
    n: 138,
    stem: "En una encuesta de clima escolar aplicada a 240 docentes y administrativos, el 65% calificó el ambiente laboral como bueno o excelente. ¿Cuántas personas no lo calificaron de esa manera?",
    options: ["70", "84", "78", "90"],
    correct: "B",
    expl: "65% de 240 = 156. 240 − 156 = 84 personas.",
  },
  {
    n: 139,
    stem: "En un informe de asistencia semanal, un curso de 33 estudiantes matriculados registró: lunes 32 presentes, martes 30, miércoles 31, jueves 29 y viernes 28. ¿Cuál fue el porcentaje promedio de asistencia esa semana, aproximadamente?",
    options: ["85%", "88%", "91%", "94%"],
    correct: "C",
    expl: "Promedio de presentes = (32+30+31+29+28)/5 = 30. 30/33 ≈ 0,909 = 91%.",
  },
  {
    n: 140,
    stem: "Para el cálculo del valor de una bonificación por desempeño, se aplica el 15% sobre el salario básico mensual de un docente que devenga $3.200.000. ¿A cuánto equivale la bonificación?",
    options: ["$420.000", "$450.000", "$500.000", "$480.000"],
    correct: "D",
    expl: "3.200.000 × 0,15 = $480.000.",
  },
];

for (const q of cuant) {
  push({
    id: `dir-apt-num-${String(q.n).padStart(3, "0")}`,
    pillar: "aptitudNumerica",
    module: "Razonamiento cuantitativo",
    topic: "Razonamiento cuantitativo · Directivo (ola 2)",
    stem: q.stem,
    options: q.options,
    correct: q.correct,
    expl: q.expl,
    tags: [],
    dif: 2,
  });
}

const blandas = [
  {
    n: 141,
    stem: "Llega a la rectoría una queja anónima que señala a un docente de mostrar favoritismo hacia ciertos estudiantes en la asignación de calificaciones. ¿Cuál sería la actuación más adecuada?",
    options: [
      "Revisar de manera discreta y objetiva los registros de evaluación del docente, y conversar con él antes de tomar cualquier decisión",
      "Ignorar la queja por ser anónima",
      "Sancionar de inmediato al docente basándose únicamente en la queja",
      "Compartir la queja abiertamente con todo el equipo docente",
    ],
    correct: "A",
    expl: "Ante una denuncia anónima, la verificación objetiva y discreta antecede cualquier acción, respetando el debido proceso.",
  },
  {
    n: 142,
    stem: "Un estudiante que había firmado un compromiso de convivencia tras una falta anterior incurre nuevamente en una situación similar semanas después. ¿Cuál sería la actuación más adecuada, siguiendo el manual de convivencia?",
    options: [
      "Ignorar la reincidencia si la primera falta no fue grave",
      "Aplicar el debido proceso considerando la reincidencia, y evaluar con el equipo de convivencia si se requiere un apoyo adicional o una medida más estructurada",
      "Expulsar automáticamente al estudiante sin más análisis",
      "Culpar exclusivamente a la familia por la reincidencia",
    ],
    correct: "B",
    expl: "La reincidencia debe abordarse dentro del debido proceso, valorando también posibles causas de fondo y apoyos adicionales.",
    tags: ["ley1620", "guiaMen49"],
  },
  {
    n: 143,
    stem: "Un docente solicita, la misma mañana, permiso por una emergencia familiar justo el día en que debía aplicar una prueba institucional a su grupo. ¿Cuál sería la actuación más adecuada del coordinador?",
    options: [
      "Negar el permiso porque la prueba ya estaba programada",
      "Pedirle al docente que aplace su emergencia hasta después de la prueba",
      "Conceder el permiso considerando la emergencia y organizar de inmediato un reemplazo o reprogramación de la prueba",
      "Cancelar la prueba para todo el año escolar",
    ],
    correct: "C",
    expl: "Priorizar la situación humana del docente y resolver operativamente la contingencia refleja un liderazgo equilibrado.",
  },
  {
    n: 144,
    stem: "El coordinador académico y el coordinador de convivencia no logran ponerse de acuerdo sobre la medida más adecuada para un estudiante con dificultades tanto académicas como disciplinarias. ¿Cuál sería la actuación más apropiada del rector?",
    options: [
      "Tomar la decisión final sin consultar a ninguno de los dos coordinadores",
      "Pedirle al estudiante que elija con cuál coordinador prefiere trabajar",
      "Asignar el caso al coordinador con mayor antigüedad, sin más análisis",
      "Facilitar un espacio conjunto de análisis del caso entre ambos coordinadores, buscando una decisión integral y consensuada",
    ],
    correct: "D",
    expl: "Un caso con dimensiones académicas y de convivencia requiere una mirada integral y consensuada.",
  },
  {
    n: 145,
    stem: "Un docente publica en sus redes sociales personales una crítica pública hacia una decisión institucional reciente, generando comentarios de padres de familia. ¿Cuál sería la actuación más adecuada del rector?",
    options: [
      "Conversar en privado con el docente sobre el impacto institucional de la publicación y explicar los canales internos disponibles para expresar desacuerdos",
      "Sancionar públicamente al docente sin conversar primero",
      "Ignorar la situación por tratarse de una red social personal",
      "Responder públicamente al docente en la misma red social",
    ],
    correct: "A",
    expl: "El diálogo privado, con orientación hacia canales internos, es la vía más constructiva.",
  },
  {
    n: 146,
    stem: "Un estudiante en condición de discapacidad es objeto de comentarios discriminatorios por parte de algunos compañeros. ¿Cuál sería la actuación institucional más adecuada?",
    options: [
      "Trasladar al estudiante afectado a otro grupo para evitar el conflicto",
      "Activar la ruta de convivencia correspondiente, atender la situación con el estudiante afectado y trabajar procesos formativos sobre inclusión con el grupo",
      "Sancionar únicamente con una anotación en el observador, sin más acompañamiento",
      "Minimizar la situación si no se repite en los días siguientes",
    ],
    correct: "B",
    expl: "La respuesta debe combinar atención al afectado con trabajo formativo preventivo en el grupo.",
    tags: ["ley1620", "decreto1421", "guiaMen49"],
  },
  {
    n: 147,
    stem: "El rector debe comunicar a un docente provisional que su contrato no será renovado por razones presupuestales ajenas a su desempeño. ¿Cuál sería la forma más adecuada de comunicarlo?",
    options: [
      "Comunicarlo mediante un mensaje escrito sin ninguna reunión previa",
      "Anunciarlo primero a todo el equipo docente antes que al docente afectado",
      "Reunirse en privado con el docente, explicar con claridad y respeto las razones de la decisión, y ofrecer la información pertinente sobre el proceso",
      "Evitar dar explicaciones para no generar más incomodidad",
    ],
    correct: "C",
    expl: "Una comunicación clara, respetuosa y en privado es la forma más adecuada de manejar una noticia laboral difícil.",
  },
  {
    n: 148,
    stem: "Un grupo de padres de familia se reúne informalmente a la entrada de la institución para expresar su inconformidad por el estado de la infraestructura. ¿Cuál sería la actuación más adecuada del rector?",
    options: [
      "Ignorar la reunión mientras no se convierta en un problema mayor",
      "Llamar a la Policía de inmediato sin antes dialogar",
      "Prometer una solución inmediata sin tener certeza de los tiempos reales",
      "Acercarse a escuchar sus inquietudes, explicar el estado real de las gestiones realizadas y proponer un espacio formal de seguimiento",
    ],
    correct: "D",
    expl: "Escuchar, informar con transparencia y ofrecer seguimiento formal atiende la inquietud sin falsas expectativas.",
  },
  {
    n: 149,
    stem: "Un docente solicita al rector un reconocimiento público por un logro obtenido con sus estudiantes. Al concederlo, algunos colegas expresan que sienten que existe favoritismo hacia ese docente. ¿Cuál sería la actuación más adecuada?",
    options: [
      "Mantener criterios claros y conocidos por todos para los reconocimientos institucionales, y explicarlos abiertamente cuando surjan percepciones de inequidad",
      "Dejar de reconocer públicamente los logros para evitar cualquier percepción de favoritismo",
      "Ignorar los comentarios de los colegas sin ninguna explicación",
      "Retirar el reconocimiento ya otorgado para evitar el conflicto",
    ],
    correct: "A",
    expl: "La transparencia en los criterios de reconocimiento previene y responde a percepciones de inequidad.",
  },
  {
    n: 150,
    stem: "Un docente informa al rector que un estudiante le manifestó, en una conversación reciente, pensamientos relacionados con quitarse la vida. ¿Cuál sería la actuación institucional más adecuada?",
    options: [
      "Pedirle al docente que maneje la situación por su cuenta, sin involucrar a más personas",
      "Activar de inmediato la ruta de atención en salud mental de la institución, contactar a la familia y a los profesionales de apoyo psicosocial disponibles, sin minimizar la situación",
      "Esperar a que el estudiante lo mencione directamente al rector antes de actuar",
      "Tratar el tema como un asunto exclusivamente disciplinario",
    ],
    correct: "B",
    expl: "Ante riesgo de este tipo, la activación inmediata de la ruta y el apoyo profesional es la respuesta apropiada.",
    tags: ["ley1620", "guiaMen49"],
  },
  {
    n: 151,
    stem: "Se plantea una inquietud, aún sin pruebas contundentes, sobre un posible conflicto de interés de un docente encargado de recibir cotizaciones para una compra institucional. ¿Cuál sería la actuación más adecuada del rector?",
    options: [
      "Ignorar la inquietud mientras no haya una denuncia formal",
      "Señalar públicamente al docente sin tener evidencia clara",
      "Revisar el proceso de manera objetiva, solicitar los soportes documentales correspondientes y, si es necesario, reasignar la responsabilidad mientras se aclara la situación",
      "Suspender de inmediato al docente sin ninguna verificación previa",
    ],
    correct: "C",
    expl: "La verificación objetiva y documentada, con medidas preventivas proporcionales, es la actuación más prudente.",
  },
  {
    n: 152,
    stem: "Al recibir retroalimentación sobre su evaluación de desempeño, un docente reacciona de forma muy defensiva y cuestiona la validez del proceso. ¿Cuál sería la actuación más adecuada del coordinador?",
    options: [
      "Terminar la conversación de inmediato ante la reacción defensiva",
      "Retirar la evaluación para evitar el conflicto",
      "Responder también de forma confrontativa para poner límites",
      "Escuchar su punto de vista, explicar con claridad los criterios y evidencias utilizados, y mantener la conversación en un tono respetuoso y profesional",
    ],
    correct: "D",
    expl: "Mantener la calma, explicar criterios y sostener un diálogo profesional favorece la retroalimentación constructiva.",
  },
  {
    n: 153,
    stem: "Una institución obtiene resultados más bajos de lo esperado en las pruebas Saber. El rector debe comunicar esta información a la comunidad educativa. ¿Cuál sería el enfoque más adecuado?",
    options: [
      "Presentar los resultados con transparencia, contextualizarlos y compartir el plan de acción institucional para atender las áreas de oportunidad identificadas",
      "Minimizar la difusión de los resultados para evitar preocupación",
      "Atribuir públicamente la responsabilidad exclusivamente a los docentes de las áreas evaluadas",
      "Esperar a que la comunidad pregunte directamente por los resultados",
    ],
    correct: "A",
    expl: "La transparencia acompañada de un plan de acción concreto fortalece la confianza institucional.",
  },
  {
    n: 154,
    stem: "Un grupo de estudiantes de grado once solicita apoyo institucional para organizar una feria de emprendimiento, pero no existe un rubro presupuestal asignado para esta actividad. ¿Cuál sería la actuación más adecuada del rector?",
    options: [
      "Negar la solicitud de inmediato por falta de presupuesto",
      "Explorar con los estudiantes alternativas de gestión (alianzas, autogestión, apoyo de padres) y orientar el proceso, en lugar de negar la iniciativa de entrada",
      "Aprobar la actividad sin ningún acompañamiento ni orientación",
      "Delegar toda la responsabilidad económica en los estudiantes sin ningún apoyo institucional",
    ],
    correct: "B",
    expl: "Acompañar la búsqueda de alternativas fomenta la iniciativa sin comprometer recursos inexistentes.",
  },
  {
    n: 155,
    stem: "Dos docentes compiten de forma poco sana por ser reconocidos como 'mejor docente del año', lo que ha generado tensión en el equipo. ¿Cuál sería la actuación más adecuada del rector?",
    options: [
      "Eliminar cualquier tipo de reconocimiento docente para evitar el problema",
      "Ignorar la tensión mientras no afecte directamente a los estudiantes",
      "Conversar por separado con cada docente sobre el impacto de esta dinámica en el equipo, y reforzar que el reconocimiento no debe entenderse como una competencia entre colegas",
      "Premiar a ambos por igual sin abordar la dinámica de fondo",
    ],
    correct: "C",
    expl: "Abordar la causa de la tensión y reforzar el sentido colaborativo del reconocimiento es más constructivo.",
  },
  {
    n: 156,
    stem: "Un padre de familia solicita al rector información confidencial sobre otro estudiante involucrado en un incidente con su hijo. ¿Cuál sería la actuación más adecuada?",
    options: [
      "Compartir toda la información solicitada para ser transparente",
      "Negarse a dar cualquier información sobre el proceso, incluida la que corresponde a su propio hijo",
      "Remitirlo directamente a buscar la información por sus propios medios",
      "Explicarle con respeto que, por razones de confidencialidad y protección de datos de menores, esa información no puede compartirse, y orientarlo sobre lo que sí puede conocer del proceso que involucra a su hijo",
    ],
    correct: "D",
    expl: "La confidencialidad de terceros debe protegerse, sin dejar de informar lo que sí le corresponde sobre su hijo.",
  },
  {
    n: 157,
    stem: "Un docente en período de prueba muestra un desempeño irregular, y se acerca la fecha límite para la evaluación que definirá su continuidad. ¿Cuál sería la actuación más adecuada del rector?",
    options: [
      "Realizar un acompañamiento y retroalimentación oportuna antes de la fecha límite, documentando el proceso, para que la decisión final esté sustentada en evidencias claras",
      "Esperar hasta el último día para informarle sobre su desempeño",
      "Aprobar su continuidad automáticamente para evitar un proceso incómodo",
      "Tomar la decisión final sin ningún registro documentado del proceso",
    ],
    correct: "A",
    expl: "El acompañamiento oportuno y la documentación del proceso son claves para una decisión justa.",
    tags: ["decreto1278"],
  },
  {
    n: 158,
    stem: "Llega a oídos del coordinador un rumor no confirmado sobre una posible situación de acoso entre estudiantes de un mismo curso. ¿Cuál sería la actuación más adecuada?",
    options: [
      "Ignorar el rumor mientras no exista una denuncia formal",
      "Indagar con discreción y de manera oportuna, sin exponer a los estudiantes involucrados, para verificar si existe una situación real que deba activarse formalmente",
      "Confrontar públicamente a los estudiantes señalados frente al curso",
      "Difundir el rumor entre otros docentes para obtener más información",
    ],
    correct: "B",
    expl: "La indagación discreta y oportuna permite verificar sin exponer innecesariamente a los estudiantes.",
    tags: ["ley1620", "guiaMen49"],
  },
  {
    n: 159,
    stem: "El rector debe decidir entre dos candidatos internos, igualmente calificados, para ocupar un cargo vacante de coordinación. ¿Cuál sería la actuación más adecuada?",
    options: [
      "Elegir al candidato con quien tenga mejor relación personal",
      "Dejar la decisión en manos de una votación informal entre los docentes",
      "Definir y aplicar criterios objetivos adicionales (como experiencia específica, evaluación de desempeño o entrevista estructurada) y comunicar la decisión con transparencia a ambos candidatos",
      "Aplazar la decisión indefinidamente para evitar el conflicto",
    ],
    correct: "C",
    expl: "Aplicar criterios objetivos y comunicar con transparencia fortalece la legitimidad del proceso.",
  },
  {
    n: 160,
    stem: "Un docente, en medio de una discusión con un estudiante durante la clase, alza la voz de forma notoria frente a todo el grupo. ¿Cuál sería la actuación más adecuada del coordinador al enterarse?",
    options: [
      "Sancionar públicamente al docente frente a otros colegas",
      "Ignorar la situación si el estudiante no presenta una queja formal",
      "Cambiar de inmediato al docente de todos sus grupos sin ninguna conversación previa",
      "Conversar en privado con el docente sobre lo ocurrido, revisar la situación con calma, y acordar estrategias para manejar situaciones similares sin perder la calma frente al grupo",
    ],
    correct: "D",
    expl: "El abordaje privado y formativo corrige la situación sin exponer públicamente al docente.",
  },
];

for (const q of blandas) {
  push({
    id: `dir-apt-blan-${String(q.n).padStart(3, "0")}`,
    pillar: "comportamental",
    module: "Competencias blandas",
    topic: "Valoración de competencias blandas · Directivo (ola 2)",
    stem: q.stem,
    options: q.options,
    correct: q.correct,
    expl: q.expl,
    tags: q.tags || [],
    dif: 2,
    caseStudy: true,
  });
}

module.exports = {raw, push};
