/**
 * Directivo aptitudes — Ejes 2 y 3 (cuantitativo + competencias blandas).
 */
const {raw, push, L} = require("./directivo_aptitudes_part1");

const cuant = [
  {
    n: 21,
    stem: "Una institución tiene 840 estudiantes matriculados. Si el 35% pertenece a la jornada de la tarde, ¿cuántos estudiantes estudian en esa jornada?",
    options: ["252", "294", "284", "315"],
    correct: "B",
    expl: "840 × 0,35 = 294 estudiantes.",
  },
  {
    n: 22,
    stem: "Un rector debe distribuir 45 computadores entre 3 sedes, de forma proporcional al número de estudiantes: Sede A 300, Sede B 200, Sede C 100. ¿Cuántos le corresponden a la Sede B?",
    options: ["10", "15", "20", "22"],
    correct: "B",
    expl: "Total = 600. Sede B = 200/600 = 1/3. 45 × 1/3 = 15.",
  },
  {
    n: 23,
    stem: "El promedio de 25 estudiantes en una prueba (escala 1 a 5) fue 3,8. Si se retira un estudiante con nota 1,0, ¿cuál es el nuevo promedio aproximado de los 24 restantes?",
    options: ["3,80", "3,85", "3,92", "4,00"],
    correct: "C",
    expl: "Suma total = 25 × 3,8 = 95. Nueva suma = 94. Nuevo promedio = 94/24 = 3,92.",
  },
  {
    n: 24,
    stem: "La jornada escolar dura 6 horas diarias, 5 días a la semana. El mínimo exigido para primaria es 25 horas semanales. ¿Cuántas horas adicionales por semana ofrece la institución?",
    options: ["3 horas", "5 horas", "6 horas", "8 horas"],
    correct: "B",
    expl: "6 × 5 = 30 horas semanales. 30 − 25 = 5 horas adicionales.",
  },
  {
    n: 25,
    stem: "De un presupuesto anual de mantenimiento de $60.000.000, se ha ejecutado el 40% en el primer semestre. ¿Cuánto queda disponible para el segundo semestre?",
    options: ["$24.000.000", "$30.000.000", "$36.000.000", "$40.000.000"],
    correct: "C",
    expl: "$60.000.000 × 0,60 = $36.000.000 disponibles.",
  },
  {
    n: 26,
    stem: "Un descanso dura 45 minutos y se organiza vigilancia en turnos de 15 minutos por patio. ¿Cuántos turnos distintos se necesitan cubrir por patio, como mínimo?",
    options: ["2", "3", "4", "5"],
    correct: "B",
    expl: "45 / 15 = 3 turnos por patio.",
  },
  {
    n: 27,
    stem: "En una institución, la relación estudiante-docente es de 28 a 1. Si hay 1.120 estudiantes, ¿cuántos docentes se requieren según esa relación?",
    options: ["35", "38", "40", "42"],
    correct: "C",
    expl: "1.120 / 28 = 40 docentes.",
  },
  {
    n: 28,
    stem: "De 500 estudiantes evaluados en pruebas Saber, el 18% se ubicó en nivel insuficiente. ¿Cuántos estudiantes fue eso?",
    options: ["80", "85", "90", "95"],
    correct: "C",
    expl: "500 × 0,18 = 90 estudiantes.",
  },
  {
    n: 29,
    stem: "La matrícula de una institución pasó de 950 a 1.045 estudiantes en un año. ¿Cuál fue el porcentaje de crecimiento?",
    options: ["8%", "9%", "10%", "12%"],
    correct: "C",
    expl: "Incremento = 95. 95/950 = 0,10 = 10%.",
  },
  {
    n: 30,
    stem: "Un rector organiza 6 grupos de grado sexto con un promedio de 32 estudiantes cada uno. Si se reorganiza en 8 grupos manteniendo el mismo total de estudiantes, ¿cuántos estudiantes tendría cada grupo?",
    options: ["20", "22", "24", "26"],
    correct: "C",
    expl: "Total = 6 × 32 = 192. 192/8 = 24 estudiantes por grupo.",
  },
  {
    n: 31,
    stem: "En la biblioteca escolar hay 2.400 libros. Si el 25% corresponde a literatura infantil y el 15% a textos de referencia, ¿cuántos libros pertenecen a otras categorías?",
    options: ["1.200", "1.320", "1.440", "1.500"],
    correct: "C",
    expl: "25% + 15% = 40%. Restante = 60%. 2.400 × 0,60 = 1.440.",
  },
  {
    n: 32,
    stem: "Un docente califica 40 evaluaciones a un ritmo promedio de 6 minutos cada una. Si dedica una jornada de 3 horas exclusivamente a esta tarea, ¿cuánto tiempo adicional necesitaría, aproximadamente, para terminar?",
    options: ["30 minutos", "45 minutos", "60 minutos", "90 minutos"],
    correct: "C",
    expl: "Tiempo requerido = 40 × 6 = 240 min (4 h). Disponible = 180 min. Faltan 60 minutos.",
  },
  {
    n: 33,
    stem: "Una institución destina el 12% de un presupuesto de $85.000.000 a materiales didácticos. ¿A cuánto equivale ese rubro, aproximadamente?",
    options: ["$8.500.000", "$9.200.000", "$10.200.000", "$11.000.000"],
    correct: "C",
    expl: "$85.000.000 × 0,12 = $10.200.000.",
  },
  {
    n: 34,
    stem: "En una encuesta a 180 docentes sobre el uso del PEI en su planeación, 126 respondieron que sí lo usan sistemáticamente. ¿Qué porcentaje representa esto?",
    options: ["60%", "65%", "70%", "75%"],
    correct: "C",
    expl: "126 / 180 = 0,70 = 70%.",
  },
  {
    n: 35,
    stem: "Un coordinador programa 5 reuniones de área, de 50 minutos cada una, con un descanso de 10 minutos entre ellas. Si empieza a las 7:00 a.m., ¿a qué hora terminaría la última reunión?",
    options: ["11:30 a.m.", "11:50 a.m.", "12:10 p.m.", "12:30 p.m."],
    correct: "B",
    expl: "5 × 50 = 250 min + 4 descansos × 10 = 40 min = 290 min (4 h 50 min). 7:00 + 4:50 = 11:50 a.m.",
  },
  {
    n: 36,
    stem: "De 60 docentes de una institución, 24 tienen título de maestría. ¿Qué fracción representa esto, simplificada?",
    options: ["1/3", "2/5", "3/5", "1/2"],
    correct: "B",
    expl: "24/60 = 2/5.",
  },
  {
    n: 37,
    stem: "Un colegio recibe una asignación de $420.000 por estudiante para el PAE, para 350 estudiantes beneficiarios. ¿Cuál es el valor total asignado?",
    options: ["$140.000.000", "$145.000.000", "$147.000.000", "$150.000.000"],
    correct: "C",
    expl: "420.000 × 350 = $147.000.000.",
  },
  {
    n: 38,
    stem: "En una prueba de 40 preguntas, un aspirante debe responder correctamente al menos el 70% para aprobar. ¿Cuántas preguntas debe acertar como mínimo?",
    options: ["24", "26", "28", "30"],
    correct: "C",
    expl: "40 × 0,70 = 28 preguntas.",
  },
  {
    n: 39,
    stem: "Una institución tiene 4 sedes con 210, 180, 165 y 245 estudiantes respectivamente. ¿Cuál es el promedio de estudiantes por sede?",
    options: ["190", "195", "200", "205"],
    correct: "C",
    expl: "Suma = 800. 800 / 4 = 200 estudiantes.",
  },
  {
    n: 40,
    stem: "La Prueba de Aptitudes y Competencias Básicas dura 3 horas para 150 preguntas distribuidas equitativamente en 5 componentes. Si un aspirante distribuye su tiempo proporcionalmente al número de preguntas de cada componente, ¿cuántos minutos debería destinar, en promedio, a cada componente?",
    options: ["30 minutos", "33 minutos", "36 minutos", "40 minutos"],
    correct: "C",
    expl: "3 horas = 180 min / 5 componentes = 36 minutos por componente.",
  },
];

for (const q of cuant) {
  push({
    id: `dir-apt-num-${String(q.n).padStart(2, "0")}`,
    pillar: "aptitudNumerica",
    module: "Razonamiento cuantitativo",
    topic: "Razonamiento cuantitativo · Directivo",
    stem: q.stem,
    options: q.options,
    correct: q.correct,
    expl: q.expl,
    tags: [],
    dif: 2,
  });
}

const blandas = [
  {
    n: 41,
    stem: "Un docente le informa al rector que un estudiante ha llegado tarde a clase de manera reiterada durante el último mes. El rector decide primero indagar con el estudiante y su acudiente las posibles causas antes de aplicar cualquier medida del manual de convivencia. Esta actuación refleja principalmente:",
    options: [
      "Falta de autoridad del rector frente a la situación",
      "Un enfoque comprensivo y garantista, propio del debido proceso",
      "Una demora innecesaria en la aplicación de sanciones",
      "Desconocimiento del manual de convivencia",
    ],
    correct: "B",
    expl: "Indagar antes de sancionar respeta el debido proceso y permite una respuesta institucional más justa.",
  },
  {
    n: 42,
    stem: "Dos docentes de un mismo grado tienen un desacuerdo frecuente sobre la metodología de evaluación, generando tensión en las reuniones de área. Como rector(a), ¿cuál sería la actuación más adecuada?",
    options: [
      "Ignorar la situación, pues es un asunto exclusivamente pedagógico entre docentes",
      "Sancionar a ambos docentes por no llegar a un acuerdo",
      "Facilitar un espacio de diálogo estructurado, con el coordinador académico, para construir criterios comunes",
      "Imponer la metodología de uno de los docentes para terminar la discusión",
    ],
    correct: "C",
    expl: "La mediación estructurada resuelve el conflicto de fondo sin imponer ni ignorar la tensión.",
  },
  {
    n: 43,
    stem: "Un padre de familia llega molesto a la rectoría exigiendo una respuesta inmediata sobre una queja radicada hace una semana que aún no ha sido resuelta. ¿Cuál es la respuesta más adecuada del rector?",
    options: [
      "Pedirle que regrese otro día porque no es un buen momento",
      "Escuchar su inquietud, explicar el estado del proceso y comprometerse con una fecha concreta de respuesta",
      "Delegar la conversación en la secretaria sin dar más información",
      "Decirle que la demora no es responsabilidad de la institución",
    ],
    correct: "B",
    expl: "Escuchar, informar con transparencia y comprometerse con un plazo es la respuesta más constructiva.",
  },
  {
    n: 44,
    stem: "Durante una reunión de Consejo Directivo, un miembro propone una decisión que el rector considera contraria a la normatividad vigente. ¿Cuál sería la actuación más apropiada?",
    options: [
      "Aceptar la propuesta para evitar un conflicto en la reunión",
      "Explicar con claridad las implicaciones normativas y proponer alternativas viables dentro del marco legal",
      "Retirarse de la reunión sin dar explicaciones",
      "Aprobar la decisión y corregirla informalmente después",
    ],
    correct: "B",
    expl: "El liderazgo técnico exige explicar el marco legal y ofrecer alternativas, no evadir ni ceder sin fundamento.",
  },
  {
    n: 45,
    stem: "Un estudiante con bajo rendimiento académico manifiesta a su director de grupo que está pasando por dificultades familiares. ¿Qué actuación institucional sería más pertinente liderar como directivo?",
    options: [
      "Remitirlo directamente a repitencia según el promedio obtenido",
      "Activar la ruta de apoyo psicosocial de la institución y hacer seguimiento conjunto con el equipo docente",
      "Indicar al docente que continúe la evaluación sin ajustes",
      "Esperar a que la familia solicite ayuda formalmente",
    ],
    correct: "B",
    expl: "La activación oportuna de la ruta de apoyo psicosocial atiende la causa de fondo del bajo rendimiento.",
  },
  {
    n: 46,
    stem: "En una evaluación de desempeño, un docente recibe una calificación baja en un componente específico. Al comunicarle el resultado, ¿cuál es el enfoque más constructivo?",
    options: [
      "Entregar el resultado por escrito sin espacio para retroalimentación",
      "Presentar el resultado, explicar los criterios y acordar un plan de mejoramiento conjunto",
      "Comparar públicamente su desempeño con el de otros docentes",
      "Omitir la conversación para no generar incomodidad",
    ],
    correct: "B",
    expl: "La retroalimentación con un plan de mejoramiento concertado favorece el desarrollo profesional del docente.",
  },
  {
    n: 47,
    stem: "Un grupo de docentes le solicita al rector eliminar una prueba institucional porque consideran que genera demasiada presión en los estudiantes. El rector no está de acuerdo con eliminarla, pero reconoce que hay preocupaciones válidas. ¿Cuál sería la actuación más adecuada?",
    options: [
      "Eliminar la prueba de inmediato para evitar el conflicto con los docentes",
      "Mantener la prueba sin dar ninguna explicación a los docentes",
      "Explicar el propósito pedagógico de la prueba y abrir un espacio para ajustar sus condiciones de aplicación",
      "Delegar la decisión final en los estudiantes mediante una votación",
    ],
    correct: "C",
    expl: "Sostener la decisión con fundamento, atendiendo la preocupación legítima, refleja liderazgo dialogante.",
  },
  {
    n: 48,
    stem: "Un docente comete un error significativo en el registro de notas que afecta a varios estudiantes. Al notar el error, ¿cuál es la actuación más adecuada del rector?",
    options: [
      "Sancionar públicamente al docente frente a sus colegas",
      "Ignorar el error si nadie más lo ha notado",
      "Abordar el error en privado, corregirlo formalmente y acordar medidas para evitar que se repita",
      "Reasignar inmediatamente las clases del docente sin conversar con él",
    ],
    correct: "C",
    expl: "Corregir con prontitud y en privado protege tanto la calidad del proceso como el respeto al docente.",
  },
  {
    n: 49,
    stem: "Durante una reunión de padres, uno de ellos interrumpe repetidamente y eleva el tono de voz para cuestionar una decisión académica. ¿Cuál sería la respuesta más adecuada del rector?",
    options: [
      "Responder también en tono elevado para poner límites",
      "Pedirle que se retire inmediatamente de la reunión sin más explicación",
      "Mantener la calma, reconocer su preocupación y proponer conversar el tema en un espacio individual al finalizar",
      "Ignorarlo por completo y continuar con la agenda",
    ],
    correct: "C",
    expl: "Desescalar sin ceder al tono, ofreciendo un espacio adecuado, resuelve la inquietud sin afectar la reunión.",
  },
  {
    n: 50,
    stem: "Un coordinador nota que una docente nueva tiene dificultades para manejar la disciplina de un grupo numeroso. ¿Cuál sería la actuación más constructiva?",
    options: [
      "Trasladarla de inmediato a un grupo más pequeño sin conversar con ella",
      "Ofrecerle acompañamiento pedagógico y estrategias de manejo de aula, con seguimiento cercano",
      "Informar el problema únicamente al rector sin hablar antes con la docente",
      "Esperar a que la situación empeore antes de intervenir",
    ],
    correct: "B",
    expl: "El acompañamiento formativo oportuno es la respuesta más constructiva ante una dificultad de un docente nuevo.",
  },
  {
    n: 51,
    stem: "Dos estudiantes de grados distintos protagonizan una pelea dentro de la institución. Ambos acusan al otro de haber iniciado la agresión. ¿Cuál sería el manejo más adecuado?",
    options: [
      "Sancionar a ambos por igual sin escuchar sus versiones",
      "Escuchar por separado a cada estudiante, indagar con testigos y aplicar el debido proceso según el manual de convivencia",
      "Sancionar únicamente al estudiante de mayor edad",
      "Dejar que los estudiantes resuelvan el conflicto entre ellos sin intervención institucional",
    ],
    correct: "B",
    expl: "El debido proceso exige indagación imparcial antes de cualquier medida disciplinaria.",
    tags: ["ley1620", "guiaMen49"],
  },
  {
    n: 52,
    stem: "Un docente le comenta al rector, de manera confidencial, que atraviesa una situación personal difícil que está afectando su desempeño. ¿Cuál sería la actuación más apropiada?",
    options: [
      "Compartir la información con otros docentes para que tengan más comprensión",
      "Escuchar con respeto, mantener la confidencialidad y explorar juntos posibles apoyos institucionales",
      "Sugerirle que solicite un traslado inmediato a otra institución",
      "Indicarle que su vida personal no debe mencionarse en el trabajo",
    ],
    correct: "B",
    expl: "La confidencialidad y el apoyo institucional son claves para un manejo ético de la situación.",
  },
  {
    n: 53,
    stem: "En el Consejo Directivo, un rector debe decidir entre dos propuestas de inversión: una mejora la conectividad a internet y otra repara la cubierta de un patio con filtraciones que representan riesgo en época de lluvias. ¿Qué actuación refleja mejor una toma de decisiones basada en priorización?",
    options: [
      "Elegir la propuesta más económica sin analizar el riesgo",
      "Priorizar la reparación que atiende un riesgo de seguridad inminente, dejando la otra para una siguiente vigencia",
      "Dividir el presupuesto en partes iguales sin evaluar la urgencia de cada una",
      "Posponer ambas decisiones hasta el siguiente año escolar",
    ],
    correct: "B",
    expl: "Ante un riesgo de seguridad, priorizar según urgencia es la actuación más responsable de un directivo.",
  },
  {
    n: 54,
    stem: "Un estudiante denuncia, mediante el conducto del personero estudiantil, una situación de trato inadecuado por parte de un docente. ¿Cuál sería la actuación institucional más apropiada?",
    options: [
      "Ignorar la denuncia si el docente tiene buena reputación",
      "Activar el protocolo correspondiente, indagar los hechos con imparcialidad y garantizar el debido proceso para ambas partes",
      "Sancionar de inmediato al docente sin verificar los hechos",
      "Pedirle al estudiante que retire la denuncia para evitar conflictos",
    ],
    correct: "B",
    expl: "El manejo imparcial y garantista es esencial ante cualquier denuncia, sin prejuzgar a ninguna de las partes.",
    tags: ["ley1620", "guiaMen49"],
  },
  {
    n: 55,
    stem: "Al implementar un cambio en la metodología de evaluación institucional, varios docentes expresan resistencia porque sienten que no fueron consultados. ¿Cuál sería la actuación más adecuada del rector?",
    options: [
      "Imponer el cambio de todas formas, ya que es una decisión directiva",
      "Reconocer la falta de consulta previa, abrir un espacio de retroalimentación y ajustar el proceso de implementación",
      "Retirar el cambio por completo ante la primera señal de resistencia",
      "Culpar a los docentes por resistirse a las mejoras institucionales",
    ],
    correct: "B",
    expl: "Reconocer el error de proceso y abrir espacios de participación fortalece la legitimidad del cambio.",
  },
  {
    n: 56,
    stem: "Un miembro del personal administrativo comete una falta leve por primera vez, relacionada con un retraso reiterado en la entrega de informes. ¿Cuál sería la actuación más adecuada?",
    options: [
      "Iniciar de inmediato un proceso disciplinario formal",
      "Conversar con la persona para entender las causas y acordar un plan de mejora, dejando constancia del compromiso",
      "Ignorar la situación mientras no afecte a terceros",
      "Trasladarlo a otra dependencia sin explicación",
    ],
    correct: "B",
    expl: "Ante una falta leve y sin antecedentes, el diálogo formativo es proporcional y constructivo.",
  },
  {
    n: 57,
    stem: "Durante una emergencia de salud de un estudiante, varios miembros del personal actúan de forma desorganizada porque no conocen bien el protocolo. ¿Qué actuación posterior sería más adecuada por parte del rector?",
    options: [
      "Sancionar al personal por no haber actuado con más rapidez",
      "Revisar lo ocurrido con el equipo, identificar fallas en el protocolo y realizar un simulacro de refuerzo",
      "Delegar toda la responsabilidad futura en el personal de enfermería escolar",
      "No hacer ningún seguimiento, dado que la situación ya se resolvió",
    ],
    correct: "B",
    expl: "El aprendizaje institucional tras una crisis requiere análisis y refuerzo del protocolo, no solo atribuir culpas.",
  },
  {
    n: 58,
    stem: "Un docente de mayor antigüedad se muestra reacio a incorporar herramientas digitales en su práctica pedagógica, a pesar de las capacitaciones ofrecidas. ¿Cuál sería la actuación más adecuada del coordinador?",
    options: [
      "Obligarlo a usar las herramientas bajo amenaza de sanción",
      "Indagar las razones de la resistencia y ofrecer acompañamiento personalizado y gradual",
      "Excluirlo de las decisiones pedagógicas del área",
      "Aceptar que nunca las use, sin ningún acompañamiento adicional",
    ],
    correct: "B",
    expl: "Comprender las causas de la resistencia permite un acompañamiento más efectivo que la imposición.",
  },
  {
    n: 59,
    stem: "En una reunión de área, un docente critica de forma poco respetuosa el trabajo de un colega frente a todo el grupo. ¿Cuál sería la intervención más adecuada del coordinador que lidera la reunión?",
    options: [
      "No intervenir, para no involucrarse en dinámicas entre docentes",
      "Interrumpir con respeto, recordar las normas de comunicación asertiva y proponer abordar el tema en privado si es necesario",
      "Sumarse a la crítica si coincide con la opinión del coordinador",
      "Finalizar la reunión de inmediato sin abordar la situación",
    ],
    correct: "B",
    expl: "Mediar oportunamente protege un ambiente de trabajo respetuoso sin evitar el conflicto.",
  },
  {
    n: 60,
    stem: "Un rector debe decidir sobre la reasignación de un docente a una sede con mayores necesidades, lo cual el docente rechaza por motivos de desplazamiento. ¿Cuál sería la actuación más equilibrada?",
    options: [
      "Imponer la reasignación sin dialogar con el docente",
      "Escuchar sus razones, revisar alternativas dentro del marco normativo y comunicar con claridad los criterios de la decisión final",
      "Cancelar la reasignación únicamente porque el docente no está de acuerdo",
      "Tomar la decisión sin informarle hasta el último momento",
    ],
    correct: "B",
    expl: "El equilibrio entre necesidades institucionales y comunicación transparente es clave en la gestión del talento humano.",
  },
];

for (const q of blandas) {
  push({
    id: `dir-apt-blan-${String(q.n).padStart(2, "0")}`,
    pillar: "comportamental",
    module: "Competencias blandas",
    topic: "Valoración de competencias blandas · Directivo",
    stem: q.stem,
    options: q.options,
    correct: q.correct,
    expl: q.expl,
    tags: q.tags || [],
    dif: 2,
    caseStudy: true,
  });
}

module.exports = {raw, push, L};
