/**
 * Directivo aptitudes — Ola 2: Gestión escolar (161–180) + Pedagógicas (181–200).
 */
const {raw, push} = require("./directivo_aptitudes_part5");

const gestion = [
  {
    n: 161,
    stem: "¿Qué es el Decreto 1075 de 2015 en el contexto del sector educativo colombiano?",
    options: [
      "El Decreto Único Reglamentario del Sector Educación, que compila en un solo cuerpo normativo diversos decretos reglamentarios previos",
      "Una ley que crea el Sistema General de Participaciones",
      "El decreto que regula exclusivamente la evaluación de estudiantes",
      "El decreto que crea la Comisión Nacional del Servicio Civil",
    ],
    correct: "A",
    expl: "El Decreto 1075 de 2015 es el Decreto Único Reglamentario del Sector Educación.",
    tags: ["decreto1075"],
  },
  {
    n: 162,
    stem: "¿Qué se entiende por 'entidad territorial certificada' en el sector educativo, según la Ley 715 de 2001?",
    options: [
      "Cualquier institución educativa con más de 1.000 estudiantes",
      "Un departamento, distrito o municipio que ha asumido la administración autónoma del servicio educativo en su jurisdicción",
      "Una universidad acreditada por el Ministerio de Educación",
      "Un colegio privado con convenio con el Estado",
    ],
    correct: "B",
    expl: "La certificación otorga a departamentos, distritos y ciertos municipios la administración autónoma de la educación.",
    tags: ["ley715"],
  },
  {
    n: 163,
    stem: "Según el Decreto 1278 de 2002, la evaluación del docente durante el período de prueba tiene como finalidad principal:",
    options: [
      "Sustituir la evaluación anual de desempeño de años posteriores",
      "Definir exclusivamente el salario inicial del docente",
      "Determinar si el docente reúne las condiciones idóneas para continuar en la carrera docente tras superar el concurso de méritos",
      "Reemplazar la valoración de antecedentes del concurso",
    ],
    correct: "C",
    expl: "Busca confirmar la idoneidad del docente para su inscripción definitiva en el escalafón.",
    tags: ["decreto1278"],
  },
  {
    n: 164,
    stem: "¿Cuál de las siguientes es una etapa propia del proceso de selección por concurso de méritos administrado por la CNSC para cargos docentes?",
    options: [
      "La afiliación automática a un sindicato docente",
      "La elección del cargo por votación de la comunidad educativa",
      "La asignación directa sin ningún tipo de evaluación",
      "La valoración de antecedentes académicos y de experiencia, posterior a la prueba de aptitudes y competencias básicas",
    ],
    correct: "D",
    expl: "Tras superar la prueba eliminatoria, se realiza la valoración de antecedentes como parte del puntaje total.",
  },
  {
    n: 165,
    stem: "¿Cuál es, de manera general, la vigencia de las listas de elegibles conformadas tras un concurso de méritos docente, según la normatividad vigente?",
    options: [
      "Dos años, contados a partir de su conformación, salvo disposición distinta en el acto administrativo correspondiente",
      "Diez años, sin posibilidad de vencimiento",
      "Seis meses únicamente",
      "La vigencia es indefinida mientras existan vacantes",
    ],
    correct: "A",
    expl: "Las listas de elegibles tienen, por regla general, vigencia limitada (habitualmente dos años).",
  },
  {
    n: 166,
    stem: "¿Cuál de los siguientes elementos debe contener, como mínimo, el manual de convivencia de una institución educativa, según la normatividad de convivencia escolar?",
    options: [
      "El presupuesto anual de la institución",
      "Las pautas de comportamiento esperado, el debido proceso ante faltas y las rutas de atención integral",
      "La planta de personal docente",
      "El calendario de vacaciones de los docentes",
    ],
    correct: "B",
    expl: "El manual debe incluir pautas, debido proceso y rutas de atención (Ley 1620 y su reglamentación).",
    tags: ["ley1620", "guiaMen49"],
  },
  {
    n: 167,
    stem: "¿Cuál es la diferencia principal entre el manual de convivencia y el reglamento interno de trabajo en una institución educativa?",
    options: [
      "Son exactamente el mismo documento con nombres distintos",
      "El reglamento interno de trabajo regula a los estudiantes",
      "El manual de convivencia regula la relación con estudiantes y la comunidad educativa; el reglamento interno de trabajo regula las relaciones laborales del personal administrativo",
      "El manual de convivencia solo aplica a los docentes",
    ],
    correct: "C",
    expl: "Ambos documentos regulan ámbitos distintos: convivencia escolar y relaciones laborales.",
    tags: ["ley1620"],
  },
  {
    n: 168,
    stem: "El Comité de Convivencia Laboral, regulado por la Resolución 652 de 2012, tiene como propósito principal:",
    options: [
      "Sancionar a los estudiantes por faltas de convivencia",
      "Reemplazar al Comité Escolar de Convivencia",
      "Definir el manual de convivencia institucional",
      "Prevenir y atender situaciones de acoso laboral entre los trabajadores de la institución",
    ],
    correct: "D",
    expl: "Es una instancia distinta del Comité Escolar de Convivencia, enfocada en relaciones laborales.",
  },
  {
    n: 169,
    stem: "En el Decreto 1278 de 2002, la evaluación de competencias es un mecanismo que permite a un docente:",
    options: [
      "Ascender de grado o de nivel salarial dentro del escalafón docente, según su desempeño demostrado",
      "Ingresar directamente a la carrera docente sin concurso",
      "Obtener automáticamente la reubicación a un cargo directivo",
      "Eximirse de la evaluación anual de desempeño",
    ],
    correct: "A",
    expl: "Es uno de los mecanismos de ascenso y reubicación salarial del Estatuto de Profesionalización Docente.",
    tags: ["decreto1278"],
  },
  {
    n: 170,
    stem: "El escalafón docente definido por el Decreto 1278 de 2002 organiza a los educadores principalmente en:",
    options: [
      "Categorías definidas exclusivamente por la antigüedad",
      "Grados (según título académico) y niveles salariales dentro de cada grado",
      "Un único nivel salarial para todos los docentes",
      "Categorías definidas por el número de estudiantes a cargo",
    ],
    correct: "B",
    expl: "Se organiza en grados asociados a la formación académica y niveles salariales dentro de cada grado.",
    tags: ["decreto1278"],
  },
  {
    n: 171,
    stem: "¿Quién tiene la responsabilidad principal de liderar la elaboración del Plan Individual de Ajustes Razonables (PIAR) de un estudiante, según el Decreto 1421 de 2017?",
    options: [
      "Exclusivamente un médico especialista externo a la institución",
      "Únicamente la Secretaría de Educación municipal",
      "El docente de aula, con el apoyo del docente de apoyo pedagógico y la participación de la familia",
      "Exclusivamente el rector, sin participación docente",
    ],
    correct: "C",
    expl: "El PIAR se construye de manera colaborativa, liderado por el docente de aula con apoyo pedagógico y la familia.",
    tags: ["decreto1421"],
  },
  {
    n: 172,
    stem: "¿Quién tiene la competencia para autorizar formalmente los permisos y licencias de un docente oficial, más allá del reporte inicial al rector?",
    options: [
      "Exclusivamente el Consejo Directivo de la institución",
      "La Asociación de Padres de Familia",
      "El Consejo Académico",
      "La entidad territorial certificada, a través de la dependencia de talento humano de la Secretaría de Educación",
    ],
    correct: "D",
    expl: "La autorización formal corresponde a la entidad territorial certificada (talento humano).",
    tags: ["ley715", "decreto1075"],
  },
  {
    n: 173,
    stem: "La Jornada Escolar Complementaria, promovida por el MEN, se caracteriza por:",
    options: [
      "Ofrecer actividades extracurriculares (deportivas, artísticas o culturales) en horario adicional a la jornada académica regular",
      "Reemplazar por completo la jornada académica regular",
      "Ser obligatoria únicamente para estudiantes de grado once",
      "Sustituir el Programa de Alimentación Escolar",
    ],
    correct: "A",
    expl: "Complementa, sin reemplazar, la jornada académica regular con actividades extracurriculares.",
  },
  {
    n: 174,
    stem: "El 'Día E', promovido por el Ministerio de Educación Nacional, tiene como propósito principal:",
    options: [
      "Suspender las clases para actividades exclusivamente recreativas",
      "Dedicar una jornada institucional a la reflexión pedagógica sobre los resultados del Índice Sintético de Calidad Educativa y la construcción de planes de mejoramiento",
      "Evaluar únicamente el desempeño de los directivos docentes",
      "Reemplazar la semana de desarrollo institucional",
    ],
    correct: "B",
    expl: "El Día E se dedica a la reflexión institucional sobre el ISCE y la planeación de mejoras.",
  },
  {
    n: 175,
    stem: "Las Semanas de Desarrollo Institucional, contempladas en el calendario académico, están destinadas principalmente a:",
    options: [
      "Actividades exclusivamente recreativas para los estudiantes",
      "La aplicación de pruebas Saber a todos los grados",
      "Actividades de planeación, evaluación institucional y capacitación docente, sin atención directa a estudiantes",
      "La elección del gobierno escolar",
    ],
    correct: "C",
    expl: "Se destinan a planeación, evaluación y desarrollo profesional docente, no a atención directa de estudiantes.",
  },
  {
    n: 176,
    stem: "¿Quién tiene la competencia para definir el calendario académico de las instituciones educativas oficiales de un municipio certificado?",
    options: [
      "Cada rector de manera independiente para su institución",
      "El Consejo Directivo de cada institución",
      "La Comisión Nacional del Servicio Civil",
      "La Secretaría de Educación de la entidad territorial certificada, dentro de los parámetros generales fijados por el MEN",
    ],
    correct: "D",
    expl: "Lo define la entidad territorial certificada, respetando lineamientos generales del MEN.",
    tags: ["ley715"],
  },
  {
    n: 177,
    stem: "La competencia para autorizar el traslado de un estudiante entre instituciones educativas oficiales de un mismo municipio certificado corresponde principalmente a:",
    options: [
      "La Secretaría de Educación municipal, a través de su sistema de matrícula, con la gestión de las instituciones involucradas",
      "Exclusivamente el rector de la institución de origen",
      "El Consejo Académico de la institución receptora",
      "La Asociación de Padres de Familia",
    ],
    correct: "A",
    expl: "Los traslados se gestionan vía sistema de matrícula de la Secretaría, con participación de las IE.",
  },
  {
    n: 178,
    stem: "Ante un desacuerdo persistente entre un docente y un directivo docente sobre una decisión administrativa, ¿cuál es una vía institucional apropiada para buscar una solución antes de acudir a instancias externas?",
    options: [
      "Acudir directamente a medios de comunicación",
      "Agotar los espacios internos de diálogo y, si es pertinente, el Comité de Convivencia Laboral, antes de escalar el conflicto a instancias externas",
      "Ignorar el desacuerdo indefinidamente",
      "Suspender unilateralmente las funciones del docente",
    ],
    correct: "B",
    expl: "Agotar instancias internas de diálogo y conciliación es el camino institucional apropiado.",
  },
  {
    n: 179,
    stem: "La contratación del servicio educativo con instituciones privadas, en zonas donde la oferta oficial es insuficiente, se rige principalmente por:",
    options: [
      "La libre decisión de cada familia sin ningún marco normativo",
      "La eliminación total de la educación oficial en esas zonas",
      "La normatividad que regula la prestación del servicio educativo por particulares mediante contrato con el Estado, sujeta a condiciones de calidad y cobertura",
      "Un acuerdo exclusivamente verbal entre el rector y el particular",
    ],
    correct: "C",
    expl: "Está sujeta a un marco normativo de calidad, cobertura y supervisión.",
    tags: ["ley715"],
  },
  {
    n: 180,
    stem: "¿Por qué es importante que una institución educativa oficial realice ejercicios de rendición de cuentas a la comunidad educativa?",
    options: [
      "Porque es un requisito exclusivamente estético sin ningún efecto práctico",
      "Porque reemplaza la necesidad de un Consejo Directivo",
      "Porque sustituye la autoevaluación institucional anual",
      "Porque fortalece la transparencia en el uso de recursos públicos y la participación de la comunidad en el seguimiento a la gestión institucional",
    ],
    correct: "D",
    expl: "Fortalece transparencia y participación comunitaria en el seguimiento de la gestión.",
  },
];

for (const q of gestion) {
  push({
    id: `dir-apt-ges-${String(q.n).padStart(3, "0")}`,
    pillar: "pedagogico",
    module: "Gestión escolar",
    topic: "Gestión escolar · Directivo (ola 2)",
    stem: q.stem,
    options: q.options,
    correct: q.correct,
    expl: q.expl,
    tags: q.tags || [],
    dif: 3,
  });
}

const pedago = [
  {
    n: 181,
    stem: "Según el enfoque de aprendizaje cooperativo de Johnson y Johnson, uno de sus elementos esenciales es:",
    options: [
      "La interdependencia positiva, donde el éxito de cada integrante depende del trabajo conjunto del grupo",
      "La competencia individual entre los integrantes del grupo",
      "La evaluación exclusivamente grupal, sin ninguna responsabilidad individual",
      "La ausencia de roles definidos dentro del equipo",
    ],
    correct: "A",
    expl: "La interdependencia positiva es uno de los cinco elementos básicos del aprendizaje cooperativo.",
  },
  {
    n: 182,
    stem: "La Zona de Desarrollo Próximo, propuesta por Vygotsky, se define como:",
    options: [
      "El nivel máximo de conocimiento que un estudiante puede alcanzar sin ayuda",
      "La distancia entre lo que un estudiante puede hacer de forma autónoma y lo que puede lograr con la guía de un adulto o un par más capaz",
      "El tiempo que un docente dedica a cada estudiante en una clase",
      "La etapa final del desarrollo cognitivo según Piaget",
    ],
    correct: "B",
    expl: "Es el concepto central de la teoría sociocultural de Vygotsky sobre el aprendizaje mediado.",
    tags: ["vygotsky"],
  },
  {
    n: 183,
    stem: "La teoría de las inteligencias múltiples de Howard Gardner, aplicada de manera pertinente en el aula, sugiere principalmente que:",
    options: [
      "Cada estudiante tiene un único tipo de inteligencia fijo de por vida",
      "Solo la inteligencia lógico-matemática debe evaluarse en la escuela",
      "Es útil diversificar las formas de presentar y evaluar el aprendizaje, reconociendo distintas fortalezas cognitivas de los estudiantes",
      "Los estudiantes deben separarse en grupos permanentes según su inteligencia dominante",
    ],
    correct: "C",
    expl: "La aplicación pertinente es diversificar estrategias, no etiquetar ni segregar de forma fija.",
  },
  {
    n: 184,
    stem: "La evaluación diagnóstica, aplicada generalmente al inicio de un período o unidad, tiene como propósito principal:",
    options: [
      "Asignar la calificación definitiva del período",
      "Sancionar a los estudiantes con menor desempeño previo",
      "Reemplazar la evaluación formativa durante el período",
      "Identificar los saberes previos y necesidades de los estudiantes para orientar la planeación pedagógica",
    ],
    correct: "D",
    expl: "La evaluación diagnóstica orienta la planeación a partir del punto de partida real.",
  },
  {
    n: 185,
    stem: "A diferencia de la evaluación formativa, la evaluación sumativa se caracteriza principalmente por:",
    options: [
      "Emitir un juicio valorativo final sobre el aprendizaje logrado al cierre de un proceso o período",
      "Brindar retroalimentación continua durante todo el proceso de aprendizaje",
      "Aplicarse exclusivamente al inicio de cada unidad",
      "Excluir cualquier forma de calificación numérica",
    ],
    correct: "A",
    expl: "La sumativa cierra un proceso con un juicio valorativo; la formativa acompaña el proceso.",
  },
  {
    n: 186,
    stem: "El portafolio, como estrategia de evaluación, permite principalmente:",
    options: [
      "Reducir la evaluación a un único momento del período académico",
      "Evidenciar el progreso del estudiante a lo largo del tiempo mediante una selección organizada de sus producciones",
      "Sustituir por completo la observación directa del docente",
      "Aplicarse únicamente en la educación superior",
    ],
    correct: "B",
    expl: "El portafolio documenta el proceso y la evolución del aprendizaje a lo largo del tiempo.",
  },
  {
    n: 187,
    stem: "El concepto de 'currículo oculto' se refiere a:",
    options: [
      "Un documento curricular confidencial que solo conocen los directivos",
      "La parte del currículo dedicada exclusivamente a la evaluación",
      "Los aprendizajes, valores y normas que los estudiantes adquieren de manera implícita a través de las dinámicas y relaciones escolares, más allá del currículo formal",
      "Un currículo alternativo aplicado únicamente en la educación privada",
    ],
    correct: "C",
    expl: "Alude a los aprendizajes no explícitos transmitidos por la cultura y prácticas institucionales.",
  },
  {
    n: 188,
    stem: "Cuando se habla del docente como 'mediador pedagógico', se hace referencia principalmente a que:",
    options: [
      "El docente resuelve conflictos exclusivamente disciplinarios en el aula",
      "El docente reemplaza completamente el rol de la familia en el aprendizaje",
      "El docente evalúa únicamente mediante pruebas estandarizadas",
      "El docente facilita y acompaña el proceso de construcción de conocimiento del estudiante, más que transmitir información de forma unidireccional",
    ],
    correct: "D",
    expl: "La mediación pedagógica implica acompañar y facilitar el aprendizaje activo del estudiante.",
    tags: ["vygotsky"],
  },
  {
    n: 189,
    stem: "La estrategia de 'aula invertida' (flipped classroom) se caracteriza principalmente por:",
    options: [
      "Que los estudiantes revisan contenidos introductorios fuera del aula, para dedicar el tiempo de clase a actividades de aplicación y profundización",
      "Eliminar por completo la exposición de contenidos por parte del docente",
      "Invertir el orden de las evaluaciones respecto a las actividades",
      "Aplicarse únicamente en la educación virtual",
    ],
    correct: "A",
    expl: "Traslado de contenidos introductorios fuera del aula para priorizar aplicación en clase.",
  },
  {
    n: 190,
    stem: "La gamificación educativa consiste principalmente en:",
    options: [
      "Reemplazar completamente las evaluaciones formales por videojuegos",
      "Incorporar elementos y dinámicas propias de los juegos (retos, niveles, recompensas) en actividades de aprendizaje para fomentar la motivación",
      "Aplicarse exclusivamente en la educación inicial",
      "Sustituir la planeación pedagógica por actividades recreativas sin propósito de aprendizaje",
    ],
    correct: "B",
    expl: "Usa elementos del juego para motivar el aprendizaje, sin reemplazar el propósito pedagógico.",
  },
  {
    n: 191,
    stem: "El desarrollo de competencias socioemocionales en el aula busca principalmente que los estudiantes:",
    options: [
      "Memoricen definiciones teóricas sobre las emociones",
      "Sean evaluados exclusivamente mediante pruebas escritas estandarizadas",
      "Reconozcan y gestionen sus emociones, y desarrollen habilidades para relacionarse de manera asertiva con los demás",
      "Eviten expresar cualquier emoción dentro del aula",
    ],
    correct: "C",
    expl: "Apuntan al reconocimiento, gestión emocional y relación asertiva con los demás.",
  },
  {
    n: 192,
    stem: "El aprendizaje autónomo se caracteriza principalmente porque el estudiante:",
    options: [
      "Trabaja siempre de manera individual, sin ninguna interacción con otros",
      "Depende exclusivamente de la instrucción directa del docente",
      "No requiere ningún tipo de retroalimentación",
      "Asume un rol activo en la planificación, ejecución y evaluación de su propio proceso de aprendizaje",
    ],
    correct: "D",
    expl: "Implica un rol activo y autorregulado, no necesariamente en soledad.",
  },
  {
    n: 193,
    stem: "Una secuencia didáctica bien estructurada debe contemplar, como mínimo, los siguientes momentos:",
    options: [
      "Inicio (activación de saberes previos), desarrollo (construcción y aplicación) y cierre (síntesis y evaluación)",
      "Únicamente actividades de evaluación sumativa",
      "Solo la exposición del docente, sin actividades de los estudiantes",
      "Un único momento sin necesidad de estructura interna",
    ],
    correct: "A",
    expl: "Inicio, desarrollo y cierre son la estructura básica de una secuencia didáctica coherente.",
  },
  {
    n: 194,
    stem: "La coevaluación y la autoevaluación, como estrategias complementarias a la heteroevaluación, permiten principalmente:",
    options: [
      "Reemplazar por completo la evaluación que realiza el docente",
      "Que los estudiantes desarrollen criterio propio sobre su desempeño y el de sus compañeros, fortaleciendo la reflexión sobre el aprendizaje",
      "Reducir la responsabilidad del docente en el proceso evaluativo",
      "Aplicarse únicamente en la educación superior",
    ],
    correct: "B",
    expl: "Complementan, sin reemplazar, la evaluación docente y fortalecen la reflexión del estudiante.",
  },
  {
    n: 195,
    stem: "El uso pedagógico de las TIC, más allá de su uso instrumental, implica principalmente:",
    options: [
      "Utilizar exclusivamente presentaciones digitales en reemplazo del tablero",
      "Evaluar el uso de dispositivos como fin en sí mismo",
      "Integrar las herramientas digitales de manera intencionada para fortalecer procesos de pensamiento y aprendizaje, no solo como medio de transmisión de información",
      "Prescindir por completo de materiales físicos o análogos",
    ],
    correct: "C",
    expl: "El uso pedagógico intencionado va más allá de lo instrumental y busca fortalecer procesos cognitivos.",
  },
  {
    n: 196,
    stem: "El aprendizaje basado en problemas (ABPr) se diferencia del aprendizaje basado en proyectos principalmente en que:",
    options: [
      "El ABPr no requiere ninguna investigación por parte del estudiante",
      "El aprendizaje basado en proyectos no admite trabajo en equipo",
      "Ambos enfoques son exactamente iguales en su estructura y duración",
      "El ABPr se centra en la resolución de un problema específico y acotado, mientras el aprendizaje basado en proyectos suele derivar en un producto más amplio y de mayor duración",
    ],
    correct: "D",
    expl: "Aunque ambos son activos, difieren en alcance y duración típica de la actividad.",
  },
  {
    n: 197,
    stem: "Respecto a los llamados 'estilos de aprendizaje' (visual, auditivo, kinestésico), la evidencia pedagógica actual recomienda principalmente:",
    options: [
      "Usar variedad de estrategias y recursos para todos los estudiantes, sin limitar la enseñanza a un único estilo supuestamente dominante en cada uno",
      "Diagnosticar un único estilo fijo por estudiante y enseñar exclusivamente bajo ese estilo",
      "Ignorar por completo cualquier diversidad en las formas de aprender",
      "Aplicar el mismo recurso didáctico a todos los estudiantes sin ninguna variación",
    ],
    correct: "A",
    expl: "La evidencia cuestiona estilos fijos y recomienda diversificar estrategias para todos.",
  },
  {
    n: 198,
    stem: "Una planeación de aula bien formulada debe articular, como mínimo:",
    options: [
      "Únicamente el tema a desarrollar, sin ningún propósito explícito",
      "Los propósitos de aprendizaje, las actividades o desempeños esperados, y las evidencias que permitirán valorar el logro",
      "Solo la bibliografía que el docente usará en la clase",
      "Exclusivamente el tiempo de duración de la clase",
    ],
    correct: "B",
    expl: "Una planeación coherente articula propósitos, desempeños esperados y evidencias.",
  },
  {
    n: 199,
    stem: "Para que la retroalimentación docente sea efectiva, debe caracterizarse principalmente por ser:",
    options: [
      "Genérica y aplicada por igual a todos los estudiantes sin distinción",
      "Entregada únicamente al finalizar el año escolar",
      "Oportuna, específica y orientada a acciones concretas de mejora, más que una valoración general",
      "Centrada exclusivamente en señalar errores, sin ninguna orientación de mejora",
    ],
    correct: "C",
    expl: "La retroalimentación efectiva es oportuna, específica y orientada a la mejora.",
  },
  {
    n: 200,
    stem: "El concepto de 'transposición didáctica' se refiere principalmente a:",
    options: [
      "La traducción literal de un libro de texto a otro idioma",
      "El traslado físico de estudiantes entre distintas sedes educativas",
      "La sustitución completa del docente por materiales autodidácticos",
      "El proceso mediante el cual un saber científico o disciplinar se transforma en un saber enseñable y adaptado al contexto escolar",
    ],
    correct: "D",
    expl: "Es la adaptación de un saber disciplinar a una forma enseñable en el contexto escolar (Chevallard).",
  },
];

for (const q of pedago) {
  push({
    id: `dir-apt-ped-${String(q.n).padStart(3, "0")}`,
    pillar: "pedagogico",
    module: "Competencias pedagógicas",
    topic: "Competencias pedagógicas · Directivo (ola 2)",
    stem: q.stem,
    options: q.options,
    correct: q.correct,
    expl: q.expl,
    tags: q.tags || [],
    dif: 2,
  });
}

module.exports = {raw, push};
