/**
 * Ola 5 — Casos oro enfocados en el rol de Rectoría.
 * Etiquetados como specialty "directivos" (Gestión directiva).
 */
const {gold} = require("./gold_handcrafted_core");

/** @type {ReturnType<typeof gold>[]} */
const wave5 = [
  gold({
    id: "oro-rect-01",
    module: "Gestión institucional y PEI",
    subtema: "Rectoría / PEI participativo",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "La rectoría reescribe el PEI en un fin de semana para una visita de supervisión, sin docentes, familias ni estudiantes.",
    stem: "La decisión más alineada a Ley 115 / Decreto 1860 es:",
    options: [
      "Validar el documento unilateral porque el rector es el máximo responsable",
      "Reabrir un proceso participativo con gobierno escolar y socializar ajustes antes de formalizar",
      "Archivar el PEI y operar solo con el PMI",
      "Delegar el PEI a un abogado externo sin comunidad",
    ],
    correct: "B",
    norma: "Ley 115 y Decreto 1860 conciben el PEI como proyecto de la comunidad educativa, no como trámite unilateral de rectoría.",
    theory: "Sin participación, el PEI pierde apropiación y no orienta prácticas reales de aula ni de gestión.",
    wrong: {
      A: "La responsabilidad del rector no elimina el deber de participación.",
      C: "El PMI no sustituye al PEI; se articula con él.",
      D: "La tercerización sin comunidad vacía el sentido institucional.",
    },
    tags: [
      {code: "ley115", focus: "PEI"},
      {code: "decreto1860", focus: "gobierno escolar"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-rect-02",
    module: "Gestión institucional y PEI",
    subtema: "Rectoría / Consejo Directivo",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "Hay que aprobar el presupuesto de inversión y el rector lo decide solo por chat con el pagador, sin sesión del Consejo Directivo.",
    stem: "Según el gobierno escolar (D.1860), conviene:",
    options: [
      "Mantener la decisión informal por agilidad",
      "Convocar al Consejo Directivo, deliberar con actas y formalizar la decisión",
      "Consultar solo al consejo de padres por WhatsApp",
      "Esperar a que supervisión dicte el presupuesto",
    ],
    correct: "B",
    norma: "El Decreto 1860 asigna al Consejo Directivo competencias de gobierno institucional; las decisiones de impacto deben ser trazables.",
    theory: "La gobernanza escolar legitima recursos y reduce riesgos de arbitrariedad o captura informal.",
    wrong: {
      A: "La agilidad no justifica omitir el órgano competente.",
      C: "El consejo de padres no reemplaza al Consejo Directivo.",
      D: "La supervisión no sustituye la autonomía con control interno.",
    },
    tags: [
      {code: "decreto1860", focus: "Consejo Directivo"},
      {code: "ley115", focus: "gobierno escolar"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-rect-03",
    module: "Inclusión y convivencia escolar",
    subtema: "Rectoría / Manual de convivencia",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "El manual de convivencia tiene 8 años, copia normas de otra IE y no tipifica rutas digitales ni debida proceso.",
    stem: "La acción rectoral prioritaria es:",
    options: [
      "Seguir usándolo porque 'siempre ha servido'",
      "Actualizarlo con participación, tipificación clara y rutas alineadas a Ley 1620 y Guías MEN 49/51",
      "Reemplazarlo por un reglamento verbal del rector",
      "Publicar sanciones ejemplarizantes en redes sin revisar el manual",
    ],
    correct: "B",
    norma: "Ley 1620 y Guías MEN 49/51 exigen manual vivo, contextualizado y coherente con rutas de atención.",
    theory: "Un manual desactualizado genera inequidad, improvisación y vulnerabilidad jurídica.",
    wrong: {
      A: "La antigüedad no garantiza validez ni pertinencia.",
      C: "El reglamento verbal carece de trazabilidad y participación.",
      D: "La exposición pública no es ruta institucional.",
    },
    tags: [
      {code: "ley1620", focus: "manual de convivencia"},
      {code: "guiaMen49", focus: "actualización"},
      {code: "guiaMen51", focus: "rutas"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-rect-04",
    module: "Pedagogía y evaluación formativa",
    subtema: "Rectoría / SIEE",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "Familias desconocen la escala; docentes del mismo grado valoran con criterios distintos; hay quejas por promoción.",
    stem: "Como rector, la intervención más coherente con el Decreto 1290 es:",
    options: [
      "Prohibir que familias pregunten por criterios",
      "Liderar revisión, socialización y monitoreo del SIEE para aplicación coherente",
      "Imponer promedios nacionales sin SIEE institucional",
      "Dejar que cada docente invente su propia escala cada periodo",
    ],
    correct: "B",
    norma: "El Decreto 1290 exige un sistema institucional de evaluación conocido, aplicado y orientado al aprendizaje.",
    theory: "La coherencia de criterios genera confianza y mejora la autorregulación del aprendizaje.",
    wrong: {
      A: "La opacidad aumenta conflicto y desconfianza.",
      C: "La autonomía institucional se ejerce vía SIEE, no vía imposición externa genérica.",
      D: "La inconsistencia vulnera el debido proceso evaluativo.",
    },
    tags: [{code: "decreto1290", focus: "SIEE institucional"}],
    dif: 2,
  }),
  gold({
    id: "oro-rect-05",
    module: "Inclusión y convivencia escolar",
    subtema: "Rectoría / Comité de convivencia",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "Un caso Tipo II llega a rectoría. El rector propone 'arreglarlo en privado' sin activar el comité ni registrar.",
    stem: "La respuesta correcta es:",
    options: [
      "Cerrar el caso en privado para proteger la imagen institucional",
      "Activar la ruta, proteger a las partes, registrar y hacer seguimiento con el Comité de Convivencia",
      "Expulsar de inmediato sin procedimiento",
      "Publicar los nombres en la cartelera",
    ],
    correct: "B",
    norma: "Ley 1620 y Guías 49/51 exigen ruta de atención integral con trazabilidad y roles definidos.",
    theory: "La informalidad protege la imagen, no los derechos ni el debido proceso.",
    wrong: {
      A: "El secreto informal puede constituir omisión.",
      C: "Sin procedimiento no hay garantía de derechos.",
      D: "La exposición pública vulnera intimidad.",
    },
    tags: [
      {code: "ley1620", focus: "Comité de Convivencia"},
      {code: "guiaMen51", focus: "Tipo II"},
    ],
    dif: 3,
    secs: 120,
  }),
  gold({
    id: "oro-rect-06",
    module: "Inclusión y convivencia escolar",
    subtema: "Rectoría / inclusión y PIAR",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "Ingresa un estudiante con discapacidad. Varios docentes dicen 'no estamos formados' y piden negarle el cupo.",
    stem: "La postura rectoral alineada al Decreto 1421 es:",
    options: [
      "Negar el cupo por falta de formación del equipo",
      "Garantizar el ingreso, activar PIAR/ajustes razonables y acompañar al equipo docente",
      "Aceptarlo sin ningún ajuste 'para que se adapte solo'",
      "Trasladarlo de inmediato a otra IE sin plan",
    ],
    correct: "B",
    norma: "El Decreto 1421 orienta educación inclusiva con PIAR y ajustes razonables; la falta de formación no habilita exclusión.",
    theory: "El liderazgo inclusivo convierte la barrera del entorno en objeto de gestión, no en culpa del estudiante.",
    wrong: {
      A: "La formación se gestiona; no justifica discriminación.",
      C: "Sin ajustes se niega el derecho a aprender en igualdad de condiciones.",
      D: "El traslado sin plan puede ser exclusión encubierta.",
    },
    tags: [{code: "decreto1421", focus: "PIAR y ajustes"}],
    dif: 2,
  }),
  gold({
    id: "oro-rect-07",
    module: "Gestión institucional y PEI",
    subtema: "Rectoría / PMI y PEI",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "El PMI lista compras de equipos, pero no se articula con las metas del PEI ni con evidencias de aprendizaje.",
    stem: "La mejora de gestión más sólida es:",
    options: [
      "Mantener el PMI como lista de compras independiente",
      "Alinear el PMI a prioridades del PEI con indicadores de aprendizaje y seguimiento",
      "Eliminar el PEI porque el PMI basta para supervisión",
      "Cambiar el PEI cada mes según la moda pedagógica",
    ],
    correct: "B",
    norma: "La gestión institucional debe articular PEI, mejoramiento y calidad del servicio educativo.",
    theory: "Un plan de mejoramiento sin norte pedagógico gasta recursos sin transformar resultados de aprendizaje.",
    wrong: {
      A: "Compras sin foco pedagógico son gestión incompleta.",
      C: "El PMI no sustituye la identidad y horizonte del PEI.",
      D: "La inestabilidad documental impide seguimiento serio.",
    },
    tags: [
      {code: "ley115", focus: "PEI"},
      {code: "decreto1860", focus: "mejoramiento"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-rect-08",
    module: "Gestión institucional y PEI",
    subtema: "Rectoría / Estatuto 1278",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "Un aspirante a docente afirma que el nombramiento se obtiene por amistad con el rector, sin concurso.",
    stem: "La lectura correcta del marco de profesionalización (D.1278) es:",
    options: [
      "Sí: el rector nombra libremente sin reglas",
      "El ingreso a la carrera docente se rige por concurso y reglas del sistema, no por favor informal",
      "Solo importa la antigüedad en el municipio",
      "El consejo de padres decide los nombramientos",
    ],
    correct: "B",
    norma: "El Decreto 1278 estructura la carrera docente con ingreso por mérito/concurso y reglas del sistema educativo.",
    theory: "La profesionalización protege la calidad y la igualdad de oportunidades frente al clientelismo.",
    wrong: {
      A: "El nombramiento no es potestad informal del rector.",
      C: "La antigüedad local no sustituye el concurso.",
      D: "El consejo de padres no nombra docentes de carrera.",
    },
    tags: [{code: "decreto1278", focus: "ingreso y carrera"}],
    dif: 1,
  }),
  gold({
    id: "oro-rect-09",
    module: "Gestión institucional y PEI",
    subtema: "Rectoría / liderazgo pedagógico",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "La rectoría dedica casi todo el tiempo a disciplina de pasillo y trámites; casi no hay acompañamiento a planeación ni a evidencias de aula.",
    stem: "Un liderazgo rectoral más pedagógico priorizaría:",
    options: [
      "Solo vigilancia de pasillos y sanciones",
      "Acompañar aulas, analizar evidencias de aprendizaje y apoyar planes de mejoramiento docente",
      "Eliminar el SIEE para reducir carga",
      "Delegar toda la pedagogía a las familias",
    ],
    correct: "B",
    norma: "La gestión directiva debe velar por la calidad del servicio educativo (Ley 115, D.1860, D.1278).",
    theory: "El liderazgo pedagógico mejora resultados cuando se centra en la enseñanza y el aprendizaje.",
    wrong: {
      A: "La convivencia importa, pero no sustituye el foco de aprendizaje.",
      C: "El SIEE es obligatorio y orientador.",
      D: "Las familias no reemplazan la gestión pedagógica institucional.",
    },
    tags: [
      {code: "decreto1278", focus: "calidad del servicio"},
      {code: "decreto1860", focus: "gestión"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-rect-10",
    module: "Gestión institucional y PEI",
    subtema: "Rectoría / Consejo Académico",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "Se cambia el plan de estudios de un área por decisión unilateral del rector, sin Consejo Académico ni socialización docente.",
    stem: "Lo más coherente con el gobierno escolar es:",
    options: [
      "Validar el cambio unilateral por agilidad",
      "Someter el ajuste al Consejo Académico y socializar criterios pedagógicos con el equipo",
      "Consultar solo a un influencer educativo",
      "Ignorar el plan de estudios porque 'cada docente hace lo suyo'",
    ],
    correct: "B",
    norma: "El Decreto 1860 organiza instancias (entre ellas el Consejo Académico) para decisiones curriculares institucionales.",
    theory: "Los cambios curriculares requieren deliberación pedagógica para coherencia y apropiación.",
    wrong: {
      A: "La agilidad no justifica saltarse la instancia académica.",
      C: "Las modas externas no sustituyen el órgano institucional.",
      D: "La atomización rompe el proyecto curricular común.",
    },
    tags: [
      {code: "decreto1860", focus: "Consejo Académico"},
      {code: "lineamientos", focus: "plan de estudios"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-rect-11",
    module: "Pedagogía y evaluación formativa",
    subtema: "Rectoría / promoción y apoyo",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "Al final del año, varios estudiantes con bajo desempeño no tuvieron planes de apoyo; la rectoría quiere negar promoción masivamente 'para subir estándares'.",
    stem: "Según el Decreto 1290, la postura más sólida es:",
    options: [
      "Negar promoción sin evidencias de acompañamiento previo",
      "Exigir que haya habido estrategias de apoyo y seguimiento antes de decidir promoción",
      "Promover a todos automáticamente sin criterios",
      "Evaluar solo con una prueba externa de un día",
    ],
    correct: "B",
    norma: "El Decreto 1290 vincula evaluación, seguimiento y estrategias de apoyo al proceso de promoción.",
    theory: "La exigencia académica es legítima cuando va acompañada de acompañamiento pedagógico, no solo de corte punitivo final.",
    wrong: {
      A: "Omite el deber de apoyo durante el proceso.",
      C: "La promoción sin criterios no es el estándar del 1290.",
      D: "Una sola prueba no agota la evaluación integral.",
    },
    tags: [{code: "decreto1290", focus: "promoción y apoyo"}],
    dif: 2,
  }),
  gold({
    id: "oro-rect-12",
    module: "Competencias comportamentales",
    subtema: "Rectoría / clima laboral",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "Dos docentes discuten fuerte en un corredor lleno de estudiantes. El tono escala y hay público.",
    stem: "La intervención rectoral más profesional es:",
    options: [
      "Confrontarlos en público para 'dar ejemplo'",
      "Contener, separar del escenario público, restablecer clima y abrir un espacio privado de mediación con acuerdos",
      "Ignorar el conflicto porque 'son adultos'",
      "Sancionar a ambos sin escuchar versiones",
    ],
    correct: "B",
    norma: "El liderazgo directivo debe proteger el clima institucional y el debido proceso en conflictos laborales/pedagógicos.",
    theory: "La contención pública y la mediación privada reducen daño al clima y permiten acuerdos sostenibles.",
    wrong: {
      A: "La confrontación pública refuerza el espectáculo del conflicto.",
      C: "Omitir puede normalizar violencia simbólica ante estudiantes.",
      D: "Sancionar sin escuchar vulnera debido proceso.",
    },
    tags: [{code: "decreto1278", focus: "clima y liderazgo"}],
    dif: 2,
  }),
  gold({
    id: "oro-rect-13",
    module: "Inclusión y convivencia escolar",
    subtema: "Rectoría / rutas de riesgo",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "Familias desconocen cómo reportar una situación de riesgo; solo existe un chat informal del rector.",
    stem: "La mejora institucional correcta es:",
    options: [
      "Mantener solo el WhatsApp del rector como canal único",
      "Socializar canales formales, protocolos y roles del Comité de Convivencia con trazabilidad",
      "Prohibir reportes de familias",
      "Publicar rumores en redes para 'investigar en comunidad'",
    ],
    correct: "B",
    norma: "Ley 1620 y Guías MEN orientan rutas claras, accesibles y con registro institucional.",
    theory: "Canales formales reducen re-victimización y dependencia de una sola persona.",
    wrong: {
      A: "Un chat personal no garantiza trazabilidad ni continuidad.",
      C: "Las familias son parte de la ruta de protección.",
      D: "Investigar por redes vulnera derechos y sesga el proceso.",
    },
    tags: [
      {code: "ley1620", focus: "canales de reporte"},
      {code: "guiaMen49", focus: "protocolo"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-rect-14",
    module: "Gestión institucional y PEI",
    subtema: "Rectoría / gobierno escolar activo",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "El gobierno escolar no se reunió en el año; las decisiones de impacto se improvisan.",
    stem: "La acción rectoral prioritaria es:",
    options: [
      "Centralizar todo en rectoría 'para no perder tiempo'",
      "Reactivar calendarios, convocatorias, quórums y actas de las instancias del gobierno escolar",
      "Sustituir instancias por encuestas anónimas en redes",
      "Esperar a que supervisión nombre los órganos",
    ],
    correct: "B",
    norma: "El Decreto 1860 organiza el gobierno escolar; su funcionamiento periódico es parte de la gestión institucional.",
    theory: "Sin instancias activas no hay participación real ni memoria institucional de decisiones.",
    wrong: {
      A: "La centralización excesiva debilita legitimidad y control.",
      C: "Las redes no reemplazan órganos estatutarios.",
      D: "La reactivación es deber institucional, no solo de supervisión.",
    },
    tags: [
      {code: "decreto1860", focus: "gobierno escolar"},
      {code: "ley115", focus: "participación"},
    ],
    dif: 1,
  }),
  gold({
    id: "oro-rect-15",
    module: "Currículo y referentes MEN",
    subtema: "Rectoría / calidad curricular",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "Docentes enseñan 'lo que alcanza el libro' sin articulación a DBA/EBC ni seguimiento institucional.",
    stem: "El liderazgo rectoral más pertinente es:",
    options: [
      "Prohibir cualquier libro de texto",
      "Orientar planeación y seguimiento con referentes MEN (DBA/EBC/lineamientos) y evidencias de aprendizaje",
      "Imponer un único cuadernillo nacional sin contexto",
      "Dejar el currículo solo a la preferencia individual de cada docente",
    ],
    correct: "B",
    norma: "Los referentes de calidad MEN orientan el currículo; la gestión institucional debe monitorear su apropiación.",
    theory: "El libro es un medio; el norte son aprendizajes esenciales con seguimiento colegiado.",
    wrong: {
      A: "El problema no es el libro, sino la falta de norte curricular.",
      C: "La imposición descontextualizada ignora el PEI y el contexto.",
      D: "La atomización rompe coherencia institucional.",
    },
    tags: [
      {code: "dba", focus: "planeación"},
      {code: "ebc", focus: "competencias"},
      {code: "lineamientos", focus: "currículo"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-rect-16",
    module: "Competencias comportamentales",
    subtema: "Rectoría / comunicación con familias",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "En reunión de padres, una familia acusa públicamente a un docente con tono agresivo. Hay estudiantes presentes.",
    stem: "La respuesta rectoral más adecuada es:",
    options: [
      "Dejar que el debate escale en público 'para transparencia'",
      "Contener el espacio, proteger la dignidad de las partes y abrir un canal privado con debido proceso",
      "Expulsar a la familia del colegio en el acto sin procedimiento",
      "Ridiculizar a la familia para defender al docente",
    ],
    correct: "B",
    norma: "El liderazgo institucional debe garantizar respeto, debido proceso y canales formales de reclamación.",
    theory: "La contención pública y el proceso privado protegen clima, derechos y posibilidad de solución.",
    wrong: {
      A: "El espectáculo público daña clima y puede revictimizar.",
      C: "Sanciones inmediatas sin proceso son arbitrarias.",
      D: "La ridiculización escalada el conflicto y modela violencia.",
    },
    tags: [{code: "ley1620", focus: "clima y respeto"}],
    dif: 2,
  }),
];

module.exports = {wave5};
