/**
 * Segunda ola oro: Decreto 1278, lineamientos curriculares y Guías MEN 49/50/51.
 * Casos distintos (no plantillas repetidas) para el concurso docente.
 */
const {gold} = require("./gold_handcrafted_core");

/** @type {ReturnType<typeof gold>[]} */
const wave2 = [
  // ========== Decreto 1278 ==========
  gold({
    id: "oro-1278-02",
    module: "Gestión institucional y PEI",
    subtema: "Decreto 1278 / evaluación de desempeño",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "En una IE se usa la evaluación de desempeño solo para sancionar, sin plan de mejoramiento ni retroalimentación formativa al docente.",
    stem: "La práctica más alineada al espíritu del Decreto 1278 es:",
    options: [
      "Eliminar toda evaluación docente",
      "Usar la evaluación de desempeño para orientar mejoramiento profesional con criterios claros",
      "Evaluar solo por popularidad entre estudiantes",
      "Sustituir la evaluación por antigüedad automática",
    ],
    correct: "B",
    norma: "El Decreto 1278 contempla evaluación de desempeño como componente del estatuto de profesionalización docente.",
    theory: "La evaluación profesional formativa articula evidencia, criterios y acciones de desarrollo, no solo sanción.",
    wrong: {
      A: "La ausencia de evaluación debilita la profesionalización.",
      C: "La popularidad no sustituye criterios de desempeño.",
      D: "El escalafón y la carrera no se reducen a antigüedad ciega.",
    },
    tags: [{code: "decreto1278", focus: "evaluación de desempeño"}],
    dif: 2,
  }),
  gold({
    id: "oro-1278-03",
    module: "Gestión institucional y PEI",
    subtema: "Decreto 1278 / deberes docentes",
    cargo: "primaria",
    caso: "Un docente sostiene que puede omitir planeación y registro porque 'ya conoce el grupo'.",
    stem: "Desde el estatuto de profesionalización, lo más coherente es:",
    options: [
      "Aceptar la omisión por experiencia",
      "Cumplir deberes de planeación, evaluación y registro como parte del ejercicio profesional",
      "Delegar toda la planeación a las familias",
      "Enseñar sin referentes institucionales",
    ],
    correct: "B",
    norma: "El Decreto 1278 reconoce derechos y deberes del docente; la planeación y el seguimiento son parte del ejercicio profesional.",
    theory: "La profesionalidad docente se expresa en decisiones intencionales, documentadas y orientadas al aprendizaje.",
    wrong: {
      A: "La experiencia no exonera de deberes profesionales.",
      C: "Las familias acompañan, no sustituyen la planeación docente.",
      D: "Los referentes institucionales orientan la práctica.",
    },
    tags: [{code: "decreto1278", focus: "deberes profesionales"}],
    dif: 2,
  }),
  gold({
    id: "oro-1278-04",
    module: "Gestión institucional y PEI",
    subtema: "Decreto 1278 / derechos y debido proceso",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "Se abre un proceso disciplinario a un docente sin notificarle cargos ni garantizar defensa.",
    stem: "La decisión institucional correcta es:",
    options: [
      "Continuar sin audiencia porque 'ya se sabe'",
      "Garantizar debido proceso, notificación y derecho de defensa",
      "Publicar el caso en redes para presión social",
      "Sancionar primero y revisar después",
    ],
    correct: "B",
    norma: "El marco del estatuto docente y el derecho administrativo exigen debido proceso en actuaciones que afectan al servidor.",
    theory: "La legitimidad institucional se sostiene en procedimientos justos y trazables.",
    wrong: {
      A: "Omitir defensa viola garantías mínimas.",
      C: "Las redes no son instancia disciplinaria.",
      D: "Sancionar sin proceso es arbitrario.",
    },
    tags: [{code: "decreto1278", focus: "debido proceso"}],
    dif: 3,
    secs: 120,
  }),
  gold({
    id: "oro-1278-05",
    module: "Gestión institucional y PEI",
    subtema: "Decreto 1278 / ingreso y carrera",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "Un aspirante cree que el nombramiento docente se obtiene solo por amistad con el rector, sin concurso.",
    stem: "La respuesta correcta según el marco del 1278 es:",
    options: [
      "Sí: el rector nombra libremente sin reglas",
      "El ingreso a la carrera docente se rige por concurso y reglas del estatuto / CNSC",
      "Solo importa el título universitario, sin proceso",
      "Cualquier persona puede ejercer sin evaluación de mérito",
    ],
    correct: "B",
    norma: "El Decreto 1278 organiza la carrera docente sobre mérito, concurso y evaluación, no sobre discrecionalidad informal.",
    theory: "El mérito profesional fortalece la calidad del servicio educativo público.",
    wrong: {
      A: "El nombramiento no es potestad informal del rector.",
      C: "El título es condición, no el único requisito de ingreso.",
      D: "El ejercicio docente exige idoneidad y procesos formales.",
    },
    tags: [{code: "decreto1278", focus: "ingreso y mérito"}],
    dif: 2,
  }),
  gold({
    id: "oro-1278-06",
    module: "Gestión institucional y PEI",
    subtema: "Decreto 1278 / escalafón",
    cargo: "primaria",
    caso: "Un docente asume que subir de grado en el escalafón depende solo de cumplir años, sin formación ni evaluación.",
    stem: "La lectura más precisa es:",
    options: [
      "El escalafón es automático por edad",
      "El ascenso en el escalafón articula requisitos de formación, experiencia y evaluación según el estatuto",
      "No existe escalafón docente",
      "El escalafón lo define cada familia del estudiante",
    ],
    correct: "B",
    norma: "El Decreto 1278 contempla el escalafón como estructura de carrera con requisitos profesionales.",
    theory: "La carrera docente vincula desarrollo profesional continuo con reconocimiento institucional.",
    wrong: {
      A: "La sola edad no basta.",
      C: "Sí existe estructura de escalafón.",
      D: "Las familias no definen el escalafón.",
    },
    tags: [{code: "decreto1278", focus: "escalafón"}],
    dif: 2,
  }),
  gold({
    id: "oro-1278-07",
    module: "Gestión institucional y PEI",
    subtema: "Decreto 1278 / desarrollo profesional",
    cargo: "matematicas",
    tagsCargo: ["matematicas", "primaria"],
    caso: "Tras una evaluación de desempeño con áreas por mejorar, la IE no ofrece acompañamiento ni plan de formación.",
    stem: "La acción más profesional es:",
    options: [
      "Archivar el resultado y no actuar",
      "Diseñar un plan de mejoramiento con acompañamiento y evidencias de avance",
      "Castigar públicamente al docente",
      "Ignorar los criterios de evaluación",
    ],
    correct: "B",
    norma: "La evaluación de desempeño en el estatuto debe conectarse con mejoramiento del servicio educativo.",
    theory: "El desarrollo profesional situado convierte la evaluación en aprendizaje organizacional.",
    wrong: {
      A: "Sin acción, la evaluación pierde sentido formativo.",
      C: "La humillación no es desarrollo profesional.",
      D: "Los criterios dan trazabilidad al proceso.",
    },
    tags: [{code: "decreto1278", focus: "mejoramiento profesional"}],
    dif: 2,
  }),
  gold({
    id: "oro-1278-08",
    module: "Gestión institucional y PEI",
    subtema: "Decreto 1278 vs Decreto 1290",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "Un consejo académico mezcla en un solo formato la evaluación de estudiantes (SIEE) y la evaluación de desempeño docente.",
    stem: "La corrección conceptual correcta es:",
    options: [
      "Son lo mismo y pueden unificarse sin problema",
      "Distinguir SIEE estudiantil (1290) de evaluación de desempeño docente (1278)",
      "Eliminar ambas evaluaciones",
      "Dejar solo la evaluación de estudiantes",
    ],
    correct: "B",
    norma: "El 1290 regula evaluación de aprendizajes; el 1278 regula, entre otros, la evaluación de desempeño docente. Son marcos distintos.",
    theory: "Claridad de propósitos evita decisiones injustas y confusión de roles.",
    wrong: {
      A: "Unificarlos confunde objetos de evaluación.",
      C: "Ambas cumplen funciones institucionales necesarias.",
      D: "Omitir evaluación docente debilita la carrera.",
    },
    tags: [
      {code: "decreto1278", focus: "desempeño docente"},
      {code: "decreto1290", focus: "SIEE estudiantil"},
    ],
    dif: 3,
    secs: 110,
  }),
  gold({
    id: "oro-1278-09",
    module: "Gestión institucional y PEI",
    subtema: "Decreto 1278 / ética profesional",
    cargo: "primaria",
    caso: "Un docente publica en redes calificaciones y comentarios sensibles sobre un estudiante.",
    stem: "Desde deberes profesionales y protección de datos, lo adecuado es:",
    options: [
      "Continuar porque 'es transparencia'",
      "Cesar la publicación, proteger la intimidad y usar canales institucionales",
      "Pedir likes a las familias",
      "Delegar la sanción al grupo de WhatsApp",
    ],
    correct: "B",
    norma: "El ejercicio docente implica deberes de confidencialidad y respeto; las actuaciones deben canalizarse institucionalmente.",
    theory: "La ética profesional protege la dignidad del estudiante y la confianza de la comunidad.",
    wrong: {
      A: "Exponer datos sensibles no es transparencia pedagógica.",
      C: "Las redes no son espacio de evaluación.",
      D: "WhatsApp no sustituye rutas institucionales.",
    },
    tags: [{code: "decreto1278", focus: "ética y confidencialidad"}],
    dif: 2,
  }),
  gold({
    id: "oro-1278-10",
    module: "Gestión institucional y PEI",
    subtema: "Decreto 1278 / permanencia y calidad",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "La dirección prioriza cobertura de horarios pero no acompaña la calidad de la práctica de aula.",
    stem: "Una gestión coherente con profesionalización docente también debe:",
    options: [
      "Ignorar lo que ocurre en el aula",
      "Acompañar pedagógicamente, observar evidencias de aprendizaje y apoyar mejoramiento",
      "Solo revisar asistencia del docente",
      "Sustituir acompañamiento por memorandos diarios",
    ],
    correct: "B",
    norma: "El estatuto busca profesionalizar el servicio; la gestión directiva debe velar por calidad educativa, no solo por presencia.",
    theory: "El liderazgo pedagógico mejora la enseñanza cuando se centra en evidencias de aprendizaje.",
    wrong: {
      A: "El aula es el núcleo del servicio educativo.",
      C: "La asistencia es necesaria pero insuficiente.",
      D: "El memorando no sustituye acompañamiento formativo.",
    },
    tags: [{code: "decreto1278", focus: "calidad del servicio"}],
    dif: 2,
  }),

  // ========== Guía MEN 49 ==========
  gold({
    id: "oro-g49-01",
    module: "Inclusión y convivencia escolar",
    subtema: "Guía MEN 49 / manual de convivencia",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "El manual de convivencia no se actualiza hace años y se copia de otra IE sin lectura de contexto.",
    stem: "Según la Guía 49, el proceso adecuado es:",
    options: [
      "Mantener el manual ajeno sin cambios",
      "Actualizarlo de forma participativa con lectura de contexto y lineamientos de la Ley 1620/Decreto 1965",
      "Imponerlo solo desde rectoría sin comunidad",
      "Eliminar el manual porque 'genera conflicto'",
    ],
    correct: "B",
    norma: "La Guía MEN 49 orienta el ajuste participativo del manual de convivencia y la Ruta de Atención Integral.",
    theory: "Un manual vivo nace del contexto y de acuerdos compartidos, no de copia acrítica.",
    wrong: {
      A: "El contexto local exige revisión periódica.",
      C: "Sin participación, pierde legitimidad.",
      D: "El manual es instrumento obligatorio de convivencia.",
    },
    tags: [
      {code: "guiaMen49", focus: "manual de convivencia"},
      {code: "ley1620", focus: "convivencia"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-g49-02",
    module: "Inclusión y convivencia escolar",
    subtema: "Guía MEN 49 / ruta promoción",
    cargo: "primaria",
    caso: "La IE solo actúa cuando ya hay pelea; no hay acciones de promoción de convivencia en el año.",
    stem: "El componente de promoción de la ruta integral apunta a:",
    options: [
      "Solo sancionar después del daño",
      "Fortalecer competencias ciudadanas, clima escolar y cultura de paz de manera proactiva",
      "Ignorar el conflicto hasta que escale",
      "Delegar toda la convivencia a la policía",
    ],
    correct: "B",
    norma: "La Guía 49 y la Ley 1620 articulan promoción, prevención, atención y seguimiento.",
    theory: "La promoción construye capacidades relacionales antes de que aparezca el conflicto grave.",
    wrong: {
      A: "La sanción sola no es promoción.",
      C: "La omisión agrava riesgos.",
      D: "La escuela tiene rol pedagógico propio.",
    },
    tags: [
      {code: "guiaMen49", focus: "promoción"},
      {code: "ley1620", focus: "ruta integral"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-g49-03",
    module: "Inclusión y convivencia escolar",
    subtema: "Guía MEN 49 / prevención",
    cargo: "primaria",
    caso: "Se detectan burlas reiteradas en un grado, pero se espera a que haya agresión física para intervenir.",
    stem: "Desde prevención (Guía 49 / ruta integral), conviene:",
    options: [
      "Esperar la agresión física para 'tener prueba'",
      "Intervenir temprano con mediación, acuerdos y seguimiento del clima del grupo",
      "Exponer públicamente a los involucrados en el patio",
      "Cerrar el caso sin registro",
    ],
    correct: "B",
    norma: "La prevención busca identificar riesgos y activar acciones antes de que escalen a situaciones graves.",
    theory: "La intervención temprana reduce daño y enseña regulación socioemocional.",
    wrong: {
      A: "Esperar el daño contradice prevención.",
      C: "La exposición pública puede revictimizar.",
      D: "Sin registro no hay seguimiento.",
    },
    tags: [{code: "guiaMen49", focus: "prevención"}],
    dif: 2,
  }),
  gold({
    id: "oro-g49-04",
    module: "Inclusión y convivencia escolar",
    subtema: "Guía MEN 49 / tipificación de situaciones",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "Ante un caso de ciberacoso grave, la IE lo trata como 'falta leve de puntualidad' y no activa protocolo.",
    stem: "La respuesta alineada a Guía 49 / Ley 1620 es:",
    options: [
      "Minimizarlo para evitar 'escándalo'",
      "Tipificar correctamente la situación y activar la ruta de atención y seguimiento",
      "Resolverlo solo en redes sociales",
      "Castigar sin indagar ni proteger",
    ],
    correct: "B",
    norma: "La tipificación correcta (Tipo I, II o III según el marco) determina la ruta de atención integral.",
    theory: "Clasificar mal el caso produce subatención o sobre-sanción injusta.",
    wrong: {
      A: "Minimizar puede agravar victimización.",
      C: "Las redes no son la ruta oficial.",
      D: "Sin indagación no hay debido proceso ni protección.",
    },
    tags: [
      {code: "guiaMen49", focus: "tipificación y atención"},
      {code: "ley1620", focus: "situaciones"},
    ],
    dif: 3,
    secs: 115,
  }),
  gold({
    id: "oro-g49-05",
    module: "Inclusión y convivencia escolar",
    subtema: "Guía MEN 49 / comité escolar de convivencia",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "El comité escolar de convivencia existe en el papel, pero no se reúne ni lidera la actualización del manual.",
    stem: "Según la Guía 49, el comité debe:",
    options: [
      "Permanecer inactivo",
      "Liderar promoción, prevención y actualización participativa del manual",
      "Sustituirse por el grupo de WhatsApp de padres",
      "Atender solo temas de notas académicas",
    ],
    correct: "B",
    norma: "La Guía 49 reconoce al comité como instancia clave para promover convivencia y ajustar el manual.",
    theory: "Sin instancia activa, la política de convivencia queda en discurso.",
    wrong: {
      A: "La inactividad incumple el marco de convivencia.",
      C: "WhatsApp no es el comité.",
      D: "El comité no es el consejo académico de notas.",
    },
    tags: [{code: "guiaMen49", focus: "comité de convivencia"}],
    dif: 2,
  }),
  gold({
    id: "oro-g49-06",
    module: "Inclusión y convivencia escolar",
    subtema: "Guía MEN 49 / seguimiento",
    cargo: "primaria",
    caso: "Tras mediar un conflicto, la IE no hace seguimiento y la tensión vuelve a escalar dos semanas después.",
    stem: "El componente de seguimiento exige:",
    options: [
      "Archivar y olvidar",
      "Verificar acuerdos, clima y reincidencia con acciones de acompañamiento",
      "Publicar el resultado en el mural sin consentimiento",
      "Transferir siempre el caso a otra IE",
    ],
    correct: "B",
    norma: "La ruta integral incluye seguimiento para constatar el restablecimiento de derechos y la efectividad de las acciones.",
    theory: "Sin seguimiento, la mediación es un evento aislado y no un proceso educativo.",
    wrong: {
      A: "Archivar sin verificar rompe la ruta.",
      C: "La exposición puede vulnerar intimidad.",
      D: "El traslado no es la primera respuesta pedagógica.",
    },
    tags: [{code: "guiaMen49", focus: "seguimiento"}],
    dif: 2,
  }),
  gold({
    id: "oro-g49-07",
    module: "Inclusión y convivencia escolar",
    subtema: "Guía MEN 49 / derechos sexuales y reproductivos",
    cargo: "primaria",
    tagsCargo: ["primaria"],
    caso: "Ante rumores sobre orientación sexual de un estudiante, compañeros lo hostigan y un adulto minimiza: 'son cosas de niños'.",
    stem: "La respuesta pedagógica y de protección más adecuada es:",
    options: [
      "Ignorar porque 'no es académico'",
      "Activar acciones de protección, educación en derechos y ruta de atención ante discriminación",
      "Obligar al estudiante a 'explicarse' ante el curso",
      "Sancionar a la víctima por 'provocar'",
    ],
    correct: "B",
    norma: "La Guía 49 profundiza en convivencia y derechos; la discriminación por orientación sexual exige prevención y atención.",
    theory: "La escuela debe ser un espacio seguro que educa en respeto a la diversidad.",
    wrong: {
      A: "La convivencia es parte del derecho a la educación.",
      C: "Exponer al estudiante revictimiza.",
      D: "Culpar a la víctima es una práctica dañina.",
    },
    tags: [
      {code: "guiaMen49", focus: "no discriminación"},
      {code: "ley1620", focus: "protección"},
    ],
    dif: 3,
    secs: 120,
  }),
  gold({
    id: "oro-g49-08",
    module: "Inclusión y convivencia escolar",
    subtema: "Guía MEN 49 / participación comunitaria",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "Solo docentes redactan normas de convivencia; familias y estudiantes no son consultados.",
    stem: "La Guía 49 recomienda:",
    options: [
      "Mantener el monopolio adulto sin diálogo",
      "Construir y actualizar el manual con participación de la comunidad educativa",
      "Imponer normas solo desde la secretaría de educación sin IE",
      "Eliminar normas claras para 'ser flexibles'",
    ],
    correct: "B",
    norma: "La Guía 49 prioriza procesos participativos para ajustar el manual de convivencia.",
    theory: "La apropiación de normas aumenta cuando quienes las viven participan en su construcción.",
    wrong: {
      A: "Sin diálogo baja el compromiso.",
      C: "La IE tiene autonomía y responsabilidad local.",
      D: "Flexibilidad no implica ausencia de reglas.",
    },
    tags: [{code: "guiaMen49", focus: "participación"}],
    dif: 2,
  }),

  // ========== Guía MEN 50 ==========
  gold({
    id: "oro-g50-01",
    module: "Pedagogía y evaluación formativa",
    subtema: "Guía MEN 50 / educación integral",
    cargo: "preescolar",
    tagsCargo: ["preescolar"],
    caso: "En transición se priorizan planas y dictados largos como en grados superiores, con poco juego.",
    stem: "Desde orientaciones de educación inicial, lo más coherente es:",
    options: [
      "Acelerar la escolarización formal a cualquier costo",
      "Privilegiar juego, exploración, cuidado y desarrollo integral con observación deliberada",
      "Eliminar toda intención educativa",
      "Evaluar solo con exámenes escritos cronometrados",
    ],
    correct: "B",
    norma: "La Guía MEN 50 y las orientaciones de educación inicial enfatizan desarrollo integral, juego y cuidado.",
    theory: "El aprendizaje temprano se construye en la acción, el juego y la interacción significativa (coherente con Piaget).",
    wrong: {
      A: "Forzar primaria temprana desconoce la especificidad de la inicial.",
      C: "Sí hay intencionalidad pedagógica, distinta a la primaria.",
      D: "La evaluación en inicial privilegia observación y evidencias situadas.",
    },
    tags: [
      {code: "guiaMen50", focus: "juego y desarrollo integral"},
      {code: "piaget", focus: "acción y desarrollo"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-g50-02",
    module: "Pedagogía y evaluación formativa",
    subtema: "Guía MEN 50 / observación",
    cargo: "preescolar",
    tagsCargo: ["preescolar"],
    caso: "Una maestra de inicial solo 'califica' con caritas sin registros anecdóticos ni criterios de desarrollo.",
    stem: "Una evaluación más pertinente en inicial sería:",
    options: [
      "Aplicar ICFES Saber 11 adaptado",
      "Documentar observaciones del desarrollo y aprendizajes con criterios claros y devolución a familias",
      "No observar para no 'etiquetar'",
      "Usar solo promedio numérico de planas",
    ],
    correct: "B",
    norma: "En educación inicial la evaluación es formativa, cualitativa y centrada en el desarrollo, no en ranking.",
    theory: "La documentación pedagógica hace visible el progreso y orienta la mediación.",
    wrong: {
      A: "Saber 11 no corresponde a inicial.",
      C: "Observar con ética no es etiquetar.",
      D: "Las planas no capturan desarrollo integral.",
    },
    tags: [
      {code: "guiaMen50", focus: "evaluación en inicial"},
      {code: "decreto1290", focus: "evaluación formativa"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-g50-03",
    module: "Pedagogía y evaluación formativa",
    subtema: "Guía MEN 50 / ambientes",
    cargo: "preescolar",
    tagsCargo: ["preescolar"],
    caso: "El aula de transición está organizada solo en filas frente al tablero, sin rincones de juego ni exploración.",
    stem: "Un ambiente más alineado a educación inicial:",
    options: [
      "Mantener filas rígidas todo el día",
      "Organizar espacios de juego, exploración y interacción con materiales significativos",
      "Vaciar el aula de materiales 'para orden'",
      "Convertir el aula en oficina administrativa",
    ],
    correct: "B",
    norma: "Las orientaciones de inicial subrayan ambientes enriquecidos que habilitan juego y aprendizaje.",
    theory: "El entorno es un 'tercer educador': estructura oportunidades de acción y lenguaje.",
    wrong: {
      A: "La rigidez limita exploración.",
      C: "Sin materiales se empobrece la experiencia.",
      D: "El aula debe ser espacio de aprendizaje.",
    },
    tags: [{code: "guiaMen50", focus: "ambientes de aprendizaje"}],
    dif: 1,
    secs: 70,
  }),
  gold({
    id: "oro-g50-04",
    module: "Pedagogía y evaluación formativa",
    subtema: "Guía MEN 50 / familias",
    cargo: "preescolar",
    tagsCargo: ["preescolar"],
    caso: "La IE de inicial solo convoca a familias para entregar 'notas' y no para corresponsabilidad en el desarrollo.",
    stem: "Una relación más coherente con Guía 50 es:",
    options: [
      "Excluir a las familias del proceso",
      "Establecer diálogo periódico sobre desarrollo, cuidados y aprendizajes del niño/a",
      "Usar solo amenazas de pérdida de cupo",
      "Sustituir la escuela por tutoría remota sin vínculo",
    ],
    correct: "B",
    norma: "La educación inicial reconoce la corresponsabilidad familia–escuela–Estado en el desarrollo integral.",
    theory: "El vínculo con familias potencia continuidad afectiva y de aprendizaje.",
    wrong: {
      A: "La exclusión debilita el desarrollo.",
      C: "La amenaza no construye alianza.",
      D: "El vínculo presencial y afectivo es central en inicial.",
    },
    tags: [{code: "guiaMen50", focus: "corresponsabilidad"}],
    dif: 2,
  }),
  gold({
    id: "oro-g50-05",
    module: "Pedagogía y evaluación formativa",
    subtema: "Guía MEN 50 / cuidado",
    cargo: "preescolar",
    tagsCargo: ["preescolar"],
    caso: "Se prioriza 'adelantar lectoescritura' y se descuida alimentación, descanso e higiene en la jornada.",
    stem: "La postura más alineada a desarrollo integral es:",
    options: [
      "Sacrificar el cuidado por rendimiento escolar anticipado",
      "Integrar cuidado y aprendizaje como dimensiones inseparables del desarrollo",
      "Eliminar rutinas de cuidado",
      "Evaluar solo velocidad de lectura",
    ],
    correct: "B",
    norma: "En inicial, el cuidado es dimensión educativa: bienestar, salud, afecto y aprendizaje van juntos.",
    theory: "Sin condiciones de bienestar, se compromete la disposición para aprender.",
    wrong: {
      A: "El rendimiento anticipado no justifica descuido.",
      C: "Las rutinas de cuidado educan autonomía.",
      D: "La velocidad no define calidad en inicial.",
    },
    tags: [{code: "guiaMen50", focus: "cuidado y aprendizaje"}],
    dif: 2,
  }),

  // ========== Guía MEN 51 ==========
  gold({
    id: "oro-g51-01",
    module: "Inclusión y convivencia escolar",
    subtema: "Guía MEN 51 / rutas de atención",
    cargo: "primaria",
    caso: "Hay una situación de violencia escolar y el docente no sabe a quién reportar ni qué protocolo seguir.",
    stem: "La acción inmediata más correcta es:",
    options: [
      "Guardar silencio para no involucrarse",
      "Activar la ruta institucional de atención según tipificación y proteger a los involucrados",
      "Publicar el caso en Facebook del colegio",
      "Pedir a los estudiantes que 'arreglen solos' sin acompañamiento",
    ],
    correct: "B",
    norma: "La Guía MEN 51 orienta la puesta en marcha de rutas de atención para convivencia escolar.",
    theory: "La respuesta oportuna y protocolizada reduce daño y da claridad de roles.",
    wrong: {
      A: "El silencio puede agravar la vulneración.",
      C: "Publicar vulnera intimidad y debido proceso.",
      D: "Sin mediación adulta se profundiza el daño.",
    },
    tags: [
      {code: "guiaMen51", focus: "ruta de atención"},
      {code: "ley1620", focus: "atención"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-g51-02",
    module: "Inclusión y convivencia escolar",
    subtema: "Guía MEN 51 / remisión",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "Una situación Tipo III requiere autoridades externas, pero la IE solo aplica amonestación verbal interna.",
    stem: "Lo correcto es:",
    options: [
      "Quedarse solo con amonestación interna",
      "Activar remisión a autoridades competentes y acciones de protección, además del manejo escolar",
      "Ocultar el caso para 'proteger la imagen'",
      "Expulsar sin registro ni ruta",
    ],
    correct: "B",
    norma: "En situaciones que constituyen presuntos delitos u otras graves, la ruta exige remisión a entidades competentes.",
    theory: "La escuela protege y no sustituye competencias de otras autoridades.",
    wrong: {
      A: "La amonestación interna puede ser insuficiente.",
      C: "Ocultar el caso puede ser omisión grave.",
      D: "Sin procedimiento se vulneran derechos.",
    },
    tags: [
      {code: "guiaMen51", focus: "remisión"},
      {code: "guiaMen49", focus: "tipificación"},
    ],
    dif: 3,
    secs: 120,
  }),
  gold({
    id: "oro-g51-03",
    module: "Inclusión y convivencia escolar",
    subtema: "Guía MEN 51 / confidencialidad",
    cargo: "primaria",
    caso: "Tras un reporte de acoso, varios adultos comentan detalles del caso en la sala de profesores con nombre completo.",
    stem: "La práctica correcta es:",
    options: [
      "Comentar libremente para 'alertar a todos'",
      "Restringir la información a quienes deben actuar en la ruta y proteger identidad",
      "Publicar un comunicado con nombres",
      "Interrogar al grupo completo en asamblea",
    ],
    correct: "B",
    norma: "Las rutas de atención exigen confidencialidad y protección de la intimidad de los involucrados.",
    theory: "La difusión innecesaria aumenta estigma y riesgo de revictimización.",
    wrong: {
      A: "Alertar no justifica chisme institucional.",
      C: "Publicar nombres vulnera derechos.",
      D: "La asamblea no es el espacio de indagación sensible.",
    },
    tags: [{code: "guiaMen51", focus: "confidencialidad"}],
    dif: 2,
  }),
  gold({
    id: "oro-g51-04",
    module: "Inclusión y convivencia escolar",
    subtema: "Guía MEN 51 / enfoque restaurativo",
    cargo: "primaria",
    caso: "Tras una falta Tipo I, la única respuesta es suspensión sin espacio de diálogo ni reparación.",
    stem: "Una alternativa más pedagógica sería:",
    options: [
      "Ignorar la falta",
      "Aplicar mediación/acuerdos restaurativos con seguimiento, según la gravedad y el manual",
      "Humillar en público como 'ejemplo'",
      "Transferir siempre a otra institución",
    ],
    correct: "B",
    norma: "Las guías de convivencia orientan respuestas formativas y rutas proporcionales a la tipificación.",
    theory: "Lo restaurativo busca reparar daño y restaurar vínculos, no solo castigar.",
    wrong: {
      A: "Ignorar enseña impunidad.",
      C: "La humillación daña y no educa.",
      D: "El traslado no es la primera respuesta pedagógica.",
    },
    tags: [
      {code: "guiaMen51", focus: "atención formativa"},
      {code: "ley1620", focus: "proporcionalidad"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-g51-05",
    module: "Inclusión y convivencia escolar",
    subtema: "Guía MEN 51 / roles",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "Nadie en la IE conoce quién activa la ruta cuando hay una situación de riesgo.",
    stem: "Para operar la Guía 51 se requiere:",
    options: [
      "Improvisar cada vez",
      "Definir roles, protocolos visibles y formación al equipo sobre la ruta",
      "Esperar que las familias activen solas la ruta",
      "Tener solo un afiche sin práctica",
    ],
    correct: "B",
    norma: "La efectividad de las rutas depende de protocolos claros y roles institucionales definidos.",
    theory: "La claridad organizacional reduce tiempo de respuesta y errores.",
    wrong: {
      A: "La improvisación aumenta riesgo.",
      C: "La escuela tiene deber de protección.",
      D: "El afiche sin práctica es insuficiente.",
    },
    tags: [{code: "guiaMen51", focus: "protocolos y roles"}],
    dif: 2,
  }),

  // ========== Lineamientos curriculares ==========
  gold({
    id: "oro-lin-w2-01",
    module: "Currículo y referentes MEN",
    subtema: "Lineamientos / lenguaje",
    cargo: "lenguaje",
    tagsCargo: ["lenguaje", "primaria"],
    caso: "En lenguaje se enseña solo ortografía aislada, sin comprensión ni producción de textos auténticos.",
    stem: "Desde lineamientos de lenguaje, lo más coherente es:",
    options: [
      "Mantener solo dictados de palabras sueltas",
      "Integrar lectura, escritura, oralidad y escucha en prácticas sociales del lenguaje",
      "Eliminar la escritura",
      "Enseñar solo gramática descontextualizada todo el año",
    ],
    correct: "B",
    norma: "Los lineamientos de lenguaje orientan el área hacia prácticas comunicativas reales, no solo fragmentos formales.",
    theory: "El lenguaje se aprende usándolo con propósito en contextos significativos.",
    wrong: {
      A: "La ortografía aislada no basta.",
      C: "La escritura es práctica central.",
      D: "La gramática sin uso pierde sentido.",
    },
    tags: [{code: "lineamientos", focus: "lenguaje"}],
    dif: 2,
  }),
  gold({
    id: "oro-lin-w2-02",
    module: "Currículo y referentes MEN",
    subtema: "Lineamientos / matemáticas",
    cargo: "matematicas",
    tagsCargo: ["matematicas"],
    caso: "El plan de matemáticas prioriza algoritmos memorizados y evita resolución de problemas y representación.",
    stem: "Una planeación alineada a lineamientos/EBC debería:",
    options: [
      "Seguir solo el índice del libro de algoritmos",
      "Articular pensamiento matemático, resolución de problemas y múltiples representaciones",
      "Eliminar la argumentación matemática",
      "Evaluar solo velocidad de cálculo mental",
    ],
    correct: "B",
    norma: "Lineamientos y EBC de matemáticas enfatizan pensamiento matemático y resolución de problemas.",
    theory: "Bruner y la didáctica actual recomiendan progresión enactivo–icónico–simbólico.",
    wrong: {
      A: "El libro no sustituye el referente de área.",
      C: "Argumentar es competencia matemática.",
      D: "La velocidad no define comprensión.",
    },
    tags: [
      {code: "lineamientos", focus: "matemáticas"},
      {code: "ebc", focus: "pensamiento matemático"},
      {code: "bruner", focus: "representaciones"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-lin-w2-03",
    module: "Currículo y referentes MEN",
    subtema: "Lineamientos / ciencias naturales",
    cargo: "ciencias",
    tagsCargo: ["ciencias", "primaria"],
    caso: "En ciencias se dictan definiciones para memorizar y no hay indagación ni registro de evidencias.",
    stem: "Desde lineamientos de ciencias, lo más adecuado es:",
    options: [
      "Priorizar solo memorización de glosario",
      "Promover indagación, formulación de preguntas, evidencia y explicación",
      "Eliminar el trabajo experimental por completo",
      "Sustituir ciencias por copiado de Wikipedia",
    ],
    correct: "B",
    norma: "Los lineamientos de ciencias naturales orientan hacia una ciencia escolar basada en indagación y explicación.",
    theory: "Aprender ciencia es aprender a preguntar, modelar y argumentar con evidencia.",
    wrong: {
      A: "El glosario sin indagación es frágil.",
      C: "La experiencia/observación es central.",
      D: "Copiar no es comprender.",
    },
    tags: [{code: "lineamientos", focus: "ciencias naturales"}],
    dif: 2,
  }),
  gold({
    id: "oro-lin-w2-04",
    module: "Currículo y referentes MEN",
    subtema: "Lineamientos / ciencias sociales",
    cargo: "sociales",
    tagsCargo: ["sociales", "primaria"],
    caso: "En sociales se enseña solo fechas memorísticas, sin análisis de problemas sociales ni pensamiento crítico.",
    stem: "Una práctica alineada a lineamientos/EBC sería:",
    options: [
      "Seguir solo listas de fechas",
      "Desarrollar pensamiento social, análisis de problemas y formación ciudadana",
      "Evitar toda discusión ética",
      "Eliminar el trabajo con fuentes",
    ],
    correct: "B",
    norma: "Los referentes de sociales orientan a comprensión crítica del entorno y competencias ciudadanas.",
    theory: "La ciudadanía se forma al interpretar problemas sociales con evidencia y argumentación.",
    wrong: {
      A: "Las fechas aisladas no construyen pensamiento social.",
      C: "La ética es parte de la formación ciudadana.",
      D: "Las fuentes sustentan el análisis.",
    },
    tags: [
      {code: "lineamientos", focus: "ciencias sociales"},
      {code: "ebc", focus: "competencias ciudadanas"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-lin-w2-05",
    module: "Currículo y referentes MEN",
    subtema: "Lineamientos / articulación EBC-DBA",
    cargo: "primaria",
    caso: "El plan de área cita lineamientos de 1998 pero ignora EBC y DBA vigentes en la planeación diaria.",
    stem: "La mejor integración de referentes es:",
    options: [
      "Usar solo un referente y descartar los demás",
      "Articular lineamientos (enfoque de área) con EBC/DBA (metas y progresión) en la planeación",
      "Ignorar todos los referentes MEN",
      "Copiar actividades virales sin meta",
    ],
    correct: "B",
    norma: "Lineamientos, EBC y DBA son complementarios: enfoque de área + competencias + aprendizajes por grado.",
    theory: "La coherencia curricular evita activismo sin progresión ni criterios de evaluación.",
    wrong: {
      A: "Se complementan, no se excluyen.",
      C: "Los referentes dan norte nacional de calidad.",
      D: "Sin meta no hay evaluación formativa.",
    },
    tags: [
      {code: "lineamientos", focus: "articulación"},
      {code: "ebc", focus: "competencias"},
      {code: "dba", focus: "progresión"},
    ],
    dif: 3,
    secs: 110,
  }),
  gold({
    id: "oro-lin-w2-06",
    module: "Currículo y referentes MEN",
    subtema: "Lineamientos / evaluación del área",
    cargo: "matematicas",
    tagsCargo: ["matematicas"],
    caso: "La evaluación de matemáticas solo pide resultados finales numéricos, sin justificar procedimientos ni representaciones.",
    stem: "Alineado a lineamientos/EBC, debería:",
    options: [
      "Mantener solo la respuesta final",
      "Valorar procesos, representaciones, argumentación y uso de conceptos en problemas",
      "Eliminar la resolución de problemas",
      "Evaluar solo limpieza del cuaderno",
    ],
    correct: "B",
    norma: "Los referentes de matemáticas privilegian comprensión y procesos, no solo el producto numérico.",
    theory: "Hacer visible el pensamiento matemático mejora la retroalimentación formativa (1290).",
    wrong: {
      A: "El producto aislado oculta el error conceptual.",
      C: "Los problemas son el corazón del área.",
      D: "La limpieza no mide competencia matemática.",
    },
    tags: [
      {code: "lineamientos", focus: "evaluación matemática"},
      {code: "decreto1290", focus: "criterios"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-lin-w2-07",
    module: "Currículo y referentes MEN",
    subtema: "Lineamientos / interdisciplinariedad",
    cargo: "primaria",
    caso: "Cada área trabaja temas aislados; un proyecto de agua potable no conecta ciencias, matemáticas ni lenguaje.",
    stem: "Una mejora curricular sería:",
    options: [
      "Mantener aislamiento total de áreas",
      "Diseñar articulaciones intencionales entre áreas con metas claras de cada referente",
      "Eliminar las áreas por completo",
      "Hacer proyectos sin criterios de evaluación",
    ],
    correct: "B",
    norma: "Los referentes permiten proyectos integradores sin perder la especificidad epistemológica de cada área.",
    theory: "La integración con intencionalidad evita el activismo y potencia transferencia de aprendizajes.",
    wrong: {
      A: "El aislamiento empobrece la comprensión del fenómeno.",
      C: "Las áreas aportan lentes disciplinares necesarios.",
      D: "Sin criterios no hay evaluación formativa.",
    },
    tags: [{code: "lineamientos", focus: "integración curricular"}],
    dif: 2,
  }),
  gold({
    id: "oro-lin-w2-08",
    module: "Currículo y referentes MEN",
    subtema: "Lineamientos / contextualización",
    cargo: "primaria",
    caso: "Se enseña un contenido de lineamientos con ejemplos urbanos ajenos a una IE rural amazónica, sin adaptación.",
    stem: "La decisión didáctica más pertinente es:",
    options: [
      "Insistir en ejemplos ajenos 'porque vienen en el libro'",
      "Contextualizar el referente a problemas, culturas y territorios del estudiantado",
      "Abandonar el referente nacional",
      "Enseñar solo folklore local sin competencias",
    ],
    correct: "B",
    norma: "Los referentes nacionales se contextualizan en el PEI y en la realidad de la comunidad educativa.",
    theory: "El aprendizaje significativo (Ausubel) ancla lo nuevo en experiencias y saberes del contexto.",
    wrong: {
      A: "El libro no es el currículo.",
      C: "Contextualizar no es abandonar el referente.",
      D: "Lo local se articula a competencias, no las reemplaza sin criterio.",
    },
    tags: [
      {code: "lineamientos", focus: "contextualización"},
      {code: "ausubel", focus: "significatividad"},
      {code: "ley115", focus: "PEI"},
    ],
    dif: 2,
  }),
];

// Micro-olas de alta calidad (enunciados únicos) para volumen controlado.
const microWave2 = [
  {
    prefix: "1278",
    module: "Gestión institucional y PEI",
    tags: [{code: "decreto1278", focus: "profesionalización"}],
    items: [
      ["Un docente pide formación continua y la IE responde que 'eso no es prioridad'.", "Priorizar desarrollo profesional alineado a necesidades de desempeño y aprendizaje de estudiantes", "El 1278 articula carrera y profesionalización docente.", "La formación continua mejora la práctica y el servicio educativo."],
      ["Se evalúa al docente sin socializar criterios previos.", "Socializar criterios de desempeño y brindar retroalimentación oportuna", "La evaluación de desempeño requiere transparencia y criterios.", "Sin criterios previos, la evaluación se percibe arbitraria."],
      ["Un directivo usa la evaluación solo para ranking interno entre docentes.", "Usarla para mejoramiento del servicio y planes de desarrollo profesional", "El propósito del estatuto es profesionalizar, no humillar.", "El ranking tóxico daña la colaboración pedagógica."],
      ["Se confunde 'periodo de prueba' con ausencia total de acompañamiento.", "Acompañar la inducción y el periodo de prueba con mentoría pedagógica", "El ingreso a carrera implica acompañamiento institucional.", "La mentoría acelera la apropiación de la cultura escolar."],
      ["Un docente incumple jornada sin justificación reiterada.", "Activar procedimientos institucionales con debido proceso y registro", "Hay deberes laborales y profesionales en el estatuto.", "La omisión reiterada afecta el derecho a la educación."],
      ["La IE no diferencia entre estímulo al buen desempeño y sanción.", "Diseñar reconocimiento del buen desempeño y rutas justas ante incumplimientos", "El estatuto contempla derechos, deberes y evaluación.", "El clima laboral mejora con justicia y reconocimiento."],
      ["Se pide al docente 'inventar evidencias' para una visita de supervisión.", "Documentar prácticas reales y honestas con evidencias de aprendizaje", "La profesionalización exige integridad.", "La simulación corrompe la mejora real."],
      ["Un docente excelso en aula es ignorado en espacios de liderazgo pedagógico.", "Abrir roles de mentoría y comunidades de aprendizaje entre pares", "El desarrollo profesional también es horizontal.", "Vygotsky institucional: la mediación entre pares docentes potencia la ZDP profesional."],
    ],
  },
  {
    prefix: "g49",
    module: "Inclusión y convivencia escolar",
    tags: [
      {code: "guiaMen49", focus: "convivencia"},
      {code: "ley1620", focus: "ruta"},
    ],
    items: [
      ["El glosario del manual no define acoso ni discriminación.", "Actualizar el manual con definiciones claras alineadas a la Guía 49 y la Ley 1620", "La Guía 49 propone glosario y actualización del manual.", "Sin definiciones compartidas, la tipificación falla."],
      ["Solo hay sanciones; no hay proyectos de promoción de convivencia.", "Diseñar acciones de promoción (ciudadanía, cuidado, diálogo) en el calendario escolar", "Promoción es el primer componente de la ruta integral.", "La cultura de paz se enseña con intencionalidad."],
      ["Un conflicto Tipo I se maneja como si fuera delito.", "Proporcionar respuesta formativa acorde a la tipificación", "La tipificación orienta la ruta y la proporcionalidad.", "Sobre-criminalizar daña el clima y el aprendizaje."],
      ["No se hace lectura de contexto antes de reescribir el manual.", "Diagnosticar clima, riesgos y percepciones de la comunidad educativa", "La Guía 49 exige lectura de lo que ocurre en el EE.", "Sin diagnóstico, el manual queda genérico."],
      ["Las familias desconocen la ruta de atención.", "Socializar rutas, roles y canales de reporte de forma comprensible", "La comunidad debe conocer cómo activar la ruta.", "La información clara aumenta la protección."],
      ["Se actualiza el manual sin el comité de convivencia.", "Liderar la actualización con el comité y participación amplia", "El comité es instancia clave según Guía 49.", "La legitimidad nace de la participación."],
      ["Tras un acuerdo restaurativo no hay monitoreo.", "Programar seguimiento de acuerdos y clima del grupo", "Seguimiento es componente de la ruta integral.", "Sin monitoreo, los acuerdos se diluyen."],
      ["Un docente ridiculiza a un estudiante por su acento o procedencia.", "Activar acciones pedagógicas y de protección frente a discriminación", "La Guía 49 enfatiza respeto a la diversidad.", "La escuela debe ser espacio seguro e inclusivo."],
    ],
  },
  {
    prefix: "g50",
    module: "Pedagogía y evaluación formativa",
    tags: [{code: "guiaMen50", focus: "educación inicial"}],
    items: [
      ["Se exige silencio absoluto todo el día en transición.", "Diseñar rutinas con juego, lenguaje y movimiento significativos", "La inicial se basa en desarrollo integral y juego.", "El lenguaje oral se desarrolla en interacción."],
      ["Se usa 'castigo del rincón' prolongado ante llanto.", "Acompañar regulación emocional con cuidado y límites respetuosos", "El cuidado es dimensión educativa en inicial.", "La contención afectiva enseña autorregulación."],
      ["No hay tiempo de juego exterior por 'perder clase'.", "Garantizar juego y actividad física como parte del aprendizaje", "Juego no es tiempo perdido: es mediación.", "El cuerpo y el movimiento son vías de conocimiento."],
      ["Se etiquetan niños como 'lentos' sin observación sistemática.", "Documentar con evidencias y diseñar mediaciones diferenciadas", "La observación ética orienta la enseñanza.", "Las etiquetas prematuras limitan oportunidades."],
      ["Las familias solo reciben un informe anual genérico.", "Compartir avances del desarrollo con ejemplos concretos y acuerdos de acompañamiento", "La corresponsabilidad requiere comunicación significativa.", "Ausubel familiar: anclar sugerencias en lo que ya hacen en casa."],
      ["Se impone lectura formal de cartillas a los 3 años como única meta.", "Respetar trayectorias y privilegiar lenguaje oral, juego simbólico y exploración", "Forzar primaria temprana contradice la especificidad de inicial.", "Piaget: no acelerar operaciones sin base sensoriomotriz/preoperacional."],
    ],
  },
  {
    prefix: "g51",
    module: "Inclusión y convivencia escolar",
    tags: [{code: "guiaMen51", focus: "rutas"}],
    items: [
      ["Hay afiche de la ruta pero nadie lo ha practicado en simulacro.", "Formar al equipo y ensayar la activación de protocolos", "La Guía 51 requiere operatividad, no solo difusión.", "La práctica reduce errores en la crisis."],
      ["Un caso se 'resuelve' cambiando de puesto sin escuchar a la víctima.", "Escuchar, proteger, registrar y aplicar la ruta según tipificación", "La atención debe ser integral y centrada en derechos.", "Mover de puesto sin proceso no repara el daño."],
      ["Se pide a la víctima confrontar sola al agresor en el patio.", "Mediar con adultos responsables y condiciones de seguridad", "La ruta evita revictimización.", "La confrontación forzada aumenta riesgo."],
      ["No se informa a orientación escolar ni a coordinación cuando corresponde.", "Activar la cadena de roles definida en el protocolo institucional", "Los roles claros hacen efectiva la Guía 51.", "La omisión de roles diluye responsabilidad."],
      ["Tras remisión externa, la IE abandona el acompañamiento pedagógico.", "Mantener seguimiento escolar de bienestar y aprendizajes", "La remisión no cierra el deber de cuidado escolar.", "El estudiante sigue siendo de la comunidad educativa."],
      ["Se usa la ruta solo para estudiantes; adultos que agreden quedan impunes.", "Aplicar también protocolos frente a vulneraciones por adultos según competencia", "La protección es para toda la comunidad educativa.", "La coherencia ética fortalece la convivencia."],
    ],
  },
  {
    prefix: "lin",
    module: "Currículo y referentes MEN",
    tags: [{code: "lineamientos", focus: "área"}],
    items: [
      ["El plan de área no declara el enfoque epistemológico del área.", "Releer lineamientos y explicitar el enfoque en el plan de área", "Los lineamientos definen el sentido del área.", "Sin enfoque, la secuencia se vuelve lista de temas."],
      ["Se evalúa lenguaje solo con opción múltiple de ortografía.", "Incluir producción y comprensión de textos con criterios de desempeño", "Lineamientos de lenguaje privilegian prácticas comunicativas.", "La evaluación debe ser coherente con lo enseñado."],
      ["En matemáticas se prohíbe el uso de material concreto en 4°.", "Permitir representaciones concretas/icónicas según necesidad de comprensión", "Bruner y lineamientos apoyan múltiples representaciones.", "Prohibir el concreto puede truncar la comprensión."],
      ["Ciencias se reduce a copiar el tablero sin hipótesis.", "Diseñar ciclos de pregunta–exploración–explicación–comunicación", "La indagación es núcleo de la ciencia escolar.", "Copiar no desarrolla pensamiento científico."],
      ["Sociales evita el análisis del conflicto social local.", "Trabajar problemas del entorno con respeto, evidencia y pensamiento crítico", "Los referentes de sociales forman ciudadanía crítica.", "El contexto local es laboratorio de análisis."],
      ["Se planea sin revisar DBA del grado correspondiente.", "Alinear metas del periodo a DBA y EBC del grado/área", "DBA orientan aprendizajes esenciales por grado.", "Saltar grados sin bases genera fragilidad."],
      ["El proyecto transversal no tiene criterios de evaluación por área.", "Definir evidencias y criterios por área articulados al proyecto", "La integración exige intencionalidad evaluativa.", "Sin criterios, el proyecto es activismo."],
      ["Se ignora la oralidad en lenguaje porque 'no se califica fácil'.", "Enseñar y evaluar oralidad con rúbricas y situaciones auténticas", "Oralidad es práctica social del lenguaje.", "Lo difícil de calificar no se elimina: se diseña mejor."],
    ],
  },
];

let idx = 0;
for (const block of microWave2) {
  for (const row of block.items) {
    idx += 1;
    const [caso, good, norma, theory] = row;
    wave2.push(
        gold({
          id: `oro-w2-${block.prefix}-${idx}`,
          module: block.module,
          subtema: `${block.prefix.toUpperCase()} · aplicación ${idx}`,
          cargo: idx % 4 === 0 ? "directivos" : idx % 3 === 0 ? "preescolar" : "primaria",
          tagsCargo:
            idx % 4 === 0
              ? ["directivos"]
              : idx % 3 === 0
                ? ["preescolar", "primaria"]
                : ["primaria"],
          caso,
          stem:
            idx % 2 === 0
              ? "Ante este caso, ¿qué decisión articula mejor norma vigente y mediación pedagógica?"
              : "Cuál respuesta evita una medida “casi correcta” pero insuficiente frente al referente MEN?",
          options: [
            "Aplicar una medida parcial (acta, charla o amonestación) sin seguimiento ni criterios claros",
            good,
            "Priorizar cobertura, rapidez o imagen institucional aunque persista el problema de fondo",
            "Resolver con criterio personal, desconectado de PEI/SIEE/rutas o referentes de área",
          ],
          correct: "B",
          norma,
          theory,
          wrong: {
            A: "Parece institucional, pero es parcial y sin cierre formativo.",
            C: "Privilegia imagen/cobertura sobre derecho y aprendizaje.",
            D: "La improvisación personal no sustituye el marco institucional.",
          },
          tags: block.tags,
          dif: 3,
          secs: 115,
        }),
    );
  }
}

module.exports = {wave2};
