/**
 * Ola 6 — Refuerzo Ciencias Sociales (32 ítems oro).
 * Especialidad: sociales. Competencias ciudadanas, pensamiento histórico y geográfico.
 */
const {gold} = require("./gold_handcrafted_core");

/** @type {ReturnType<typeof gold>[]} */
const sociales = [
  gold({
    id: "oro-soc-01",
    module: "Currículo y referentes MEN",
    subtema: "Sociales / multiperspectiva",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "Al estudiar la Independencia, el docente presenta una sola narrativa heroica y descalifica otras fuentes o actores.",
    stem: "Desde el pensamiento histórico escolar, lo más adecuado es:",
    options: [
      "Imponer una única versión oficial sin contraste",
      "Contrastar fuentes y perspectivas de distintos actores para comprender el proceso histórico",
      "Evitar el tema por ser controvertido",
      "Memorizar solo fechas y nombres",
    ],
    correct: "B",
    norma: "Los EBC de Ciencias Sociales promueven el análisis crítico de fuentes y perspectivas.",
    theory: "El pensamiento histórico se forma contrastando evidencias, no consumiendo una crónica única.",
    wrong: {
      A: "Una sola versión empobrece la comprensión.",
      C: "Lo controvertido se media pedagógicamente.",
      D: "Fechas sin interpretación no bastan.",
    },
    tags: [{code: "ebc", focus: "pensamiento histórico"}, {code: "lineamientos", focus: "sociales"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-02",
    module: "Currículo y referentes MEN",
    subtema: "Sociales / competencias ciudadanas",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "La clase de ciudadanas se limita a copiar artículos de la Constitución sin analizar dilemas del entorno escolar.",
    stem: "La práctica más alineada a competencias ciudadanas es:",
    options: [
      "Seguir solo con copia literal",
      "Articular normas con dilemas reales (convivencia, participación, derechos) y argumentación",
      "Eliminar la Constitución del programa",
      "Sustituir la clase por un discurso partidista",
    ],
    correct: "B",
    norma: "Los Estándares de Competencias Ciudadanas buscan formación para la acción democrática situada.",
    theory: "La ciudadanía se aprende analizando dilemas y practicando deliberación, no solo memorizando normas.",
    wrong: {
      A: "La copia no desarrolla competencia.",
      C: "La Constitución es referente clave.",
      D: "Adoctrinar no es educar en ciudadanía.",
    },
    tags: [{code: "ebc", focus: "ciudadanas"}, {code: "ley115", focus: "formación ciudadana"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-03",
    module: "Inclusión y convivencia escolar",
    subtema: "Sociales / Cátedra de la Paz",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "La Cátedra de la Paz se reduce a una conferencia anual sin seguimiento ni proyectos de aula.",
    stem: "Según la Ley 1732 y su sentido pedagógico, conviene:",
    options: [
      "Mantenerla como evento aislado",
      "Integrarla de forma continua al currículo y a prácticas de convivencia y memoria",
      "Eliminarla porque 'no está en Saber 11'",
      "Delegarla solo al personero sin docentes",
    ],
    correct: "B",
    norma: "La Cátedra de la Paz busca cultura de paz y competencias ciudadanas de manera sostenida.",
    theory: "La paz se forma en prácticas cotidianas y reflexión histórica, no en un acto protocolario.",
    wrong: {
      A: "El evento aislado no transforma cultura escolar.",
      C: "Su valor no se reduce a pruebas.",
      D: "Requiere mediación docente.",
    },
    tags: [{code: "ley1620", focus: "convivencia"}, {code: "ebc", focus: "paz"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-04",
    module: "Pedagogía y evaluación formativa",
    subtema: "Sociales / fuentes",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "Estudiantes usan un video de redes como 'prueba histórica' sin preguntar autor, fecha ni intención.",
    stem: "La mediación docente prioritaria es:",
    options: [
      "Aceptar cualquier video como fuente válida",
      "Enseñar criterios de crítica de fuentes (origen, contexto, sesgo, contraste)",
      "Prohibir internet en absolutos términos",
      "Calificar solo la duración del video",
    ],
    correct: "B",
    norma: "Los EBC de sociales exigen manejo crítico de información y fuentes.",
    theory: "La alfabetización mediática es parte del pensamiento social contemporáneo.",
    wrong: {
      A: "Sin crítica se refuerza la desinformación.",
      C: "El problema no es internet, sino la mediación.",
      D: "La duración no mide calidad histórica.",
    },
    tags: [{code: "ebc", focus: "fuentes"}, {code: "lineamientos", focus: "sociales"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-05",
    module: "Currículo y referentes MEN",
    subtema: "Sociales / territorio",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "La geografía se enseña solo con capitales memorizadas, sin mapas del municipio ni problemas de ordenamiento local.",
    stem: "El enfoque más pertinente es:",
    options: [
      "Insistir solo en listas de capitales",
      "Trabajar territorio, escalas y problemáticas locales con cartografía y análisis espacial",
      "Eliminar la geografía del plan de estudios",
      "Sustituir mapas por opiniones sin evidencia",
    ],
    correct: "B",
    norma: "Los referentes de sociales articulan pensamiento espacial y comprensión del territorio.",
    theory: "La geografía escolar interpreta relaciones sociedad-espacio con evidencias cartográficas.",
    wrong: {
      A: "Memorizar capitales no agota el pensamiento geográfico.",
      C: "Es un eje del área.",
      D: "Sin evidencia no hay análisis territorial.",
    },
    tags: [{code: "ebc", focus: "territorio"}, {code: "dba", focus: "sociales"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-06",
    module: "Pedagogía y evaluación formativa",
    subtema: "Sociales / dilemas éticos",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "Ante un dilema sobre privacidad en redes, el docente dicta 'la respuesta correcta' sin abrir deliberación.",
    stem: "Para formar juicio ciudadano, debería:",
    options: [
      "Imponer siempre su opinión como única válida",
      "Facilitar deliberación con argumentos, respeto a reglas y contraste de consecuencias",
      "Evitar dilemas porque generan debate",
      "Dejar que el grupo vote sin criterios",
    ],
    correct: "B",
    norma: "Las competencias ciudadanas incluyen toma de decisiones y argumentación ética.",
    theory: "La deliberación estructurada desarrolla perspectiva moral y escucha activa.",
    wrong: {
      A: "Imponer anula el ejercicio ciudadano.",
      C: "El debate mediado es aprendizaje.",
      D: "Votar sin criterios es superficial.",
    },
    tags: [{code: "ebc", focus: "deliberación"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-07",
    module: "Inclusión y convivencia escolar",
    subtema: "Sociales / diversidad étnica",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "En un aula intercultural, el currículo de sociales invisibiliza pueblos indígenas y comunidades negras del territorio.",
    stem: "La decisión más alineada a la Constitución y al área es:",
    options: [
      "Mantener un relato monocultural",
      "Incluir memorias, derechos y aportes de la diversidad étnica con rigor y respeto",
      "Tratar la diversidad solo como folklore de una fecha",
      "Separar estudiantes por etnia en el aula",
    ],
    correct: "B",
    norma: "La Constitución y los referentes de sociales reconocen la nación multiétnica y pluricultural.",
    theory: "La identidad y la ciudadanía se construyen reconociendo pluralidad y dignidad.",
    wrong: {
      A: "El monoculturalismo contradice el marco constitucional.",
      C: "El folklore puntual no basta.",
      D: "Separar vulnera inclusión.",
    },
    tags: [{code: "ley115", focus: "diversidad"}, {code: "ebc", focus: "identidad"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-08",
    module: "Pedagogía y evaluación formativa",
    subtema: "Sociales / causalidad histórica",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "Un estudiante explica un hecho histórico con una sola causa ('fue por una persona'). El docente acepta sin problematizar.",
    stem: "La mediación correcta es:",
    options: [
      "Aceptar siempre explicaciones unicausales",
      "Guiar el análisis de múltiples causas (políticas, económicas, sociales) e interrelaciones",
      "Prohibir cualquier explicación causal",
      "Reducir todo a memorias individuales sin contexto",
    ],
    correct: "B",
    norma: "El pensamiento histórico exige comprensión multicausal de procesos.",
    theory: "Los hechos sociales se explican por redes de factores, no por un único héroe.",
    wrong: {
      A: "La unicausalidad simplifica en exceso.",
      C: "La causalidad es central, bien mediada.",
      D: "Sin contexto no hay explicación histórica.",
    },
    tags: [{code: "ebc", focus: "causalidad"}, {code: "lineamientos", focus: "historia"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-09",
    module: "Pedagogía y evaluación formativa",
    subtema: "Sociales / participación escolar",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "El gobierno escolar existe en el papel, pero las decisiones se toman sin escuchar al consejo estudiantil.",
    stem: "Desde formación ciudadana, el docente/directivo debería:",
    options: [
      "Mantener la participación solo simbólica",
      "Garantizar espacios reales de consulta e incidencia estudiantil según el gobierno escolar",
      "Eliminar el personero para 'evitar problemas'",
      "Sustituir la participación por castigos",
    ],
    correct: "B",
    norma: "Ley 115 y Decreto 1860 establecen órganos de participación estudiantil con funciones reales.",
    theory: "Se aprende democracia ejerciéndola con mediación y responsabilidad.",
    wrong: {
      A: "Lo simbólico no forma ciudadanía.",
      C: "Eliminar el personero vulnera la norma.",
      D: "El castigo no sustituye participación.",
    },
    tags: [{code: "ley115", focus: "gobierno escolar"}, {code: "decreto1860", focus: "participación"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-10",
    module: "Currículo y referentes MEN",
    subtema: "Sociales / economía",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "Al hablar de desigualdad, el docente usa solo juicios morales sin datos, gráficos ni comparación territorial.",
    stem: "La aproximación más rigurosa es:",
    options: [
      "Quedarse solo en opiniones sin evidencia",
      "Analizar indicadores, causas estructurales y consecuencias con información verificable",
      "Negar la desigualdad para evitar el tema",
      "Reducir la clase a slogans",
    ],
    correct: "B",
    norma: "Los EBC de sociales incluyen comprensión de dinámicas económicas y sociales con evidencia.",
    theory: "El pensamiento social crítico combina datos, conceptos y argumentación ética.",
    wrong: {
      A: "Sin evidencia el juicio es frágil.",
      C: "Negar contradice la realidad social.",
      D: "Los slogans no forman competencia.",
    },
    tags: [{code: "ebc", focus: "economía y sociedad"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-11",
    module: "Pedagogía y evaluación formativa",
    subtema: "Sociales / línea de tiempo",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "Los estudiantes ordenan hechos en una línea de tiempo, pero no explican cambios ni continuidades.",
    stem: "Para potenciar la actividad, el docente debe pedir:",
    options: [
      "Solo pegar fechas con colores",
      "Interpretar cambios, continuidades y rupturas entre periodos",
      "Memorizar la línea sin discusión",
      "Eliminar las líneas de tiempo del área",
    ],
    correct: "B",
    norma: "El pensamiento temporal histórico va más allá de cronologías: interpreta procesos.",
    theory: "Cambio y continuidad son categorías clave del pensamiento histórico.",
    wrong: {
      A: "El colorido no garantiza comprensión.",
      C: "Memorizar sin interpretar es insuficiente.",
      D: "Es una herramienta útil si se media.",
    },
    tags: [{code: "ebc", focus: "tiempo histórico"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-12",
    module: "Inclusión y convivencia escolar",
    subtema: "Sociales / discriminación",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "En un debate, un estudiante usa estereotipos discriminatorios. El docente ignora 'para no cortar la participación'.",
    stem: "La actuación más adecuada es:",
    options: [
      "Ignorar el estereotipo",
      "Interrumpir con respeto, marcar el límite normativo y transformar el momento en aprendizaje ciudadano",
      "Expulsar de inmediato sin mediación formativa",
      "Reírse para bajar la tensión",
    ],
    correct: "B",
    norma: "Ley 1620 y el marco de derechos exigen prevenir y atender discriminación en la escuela.",
    theory: "La participación tiene límites éticos: dignidad y no discriminación.",
    wrong: {
      A: "Ignorar naturaliza la violencia simbólica.",
      C: "La sanción sin formación pierde oportunidad pedagógica.",
      D: "Reírse refuerza el estereotipo.",
    },
    tags: [{code: "ley1620", focus: "discriminación"}, {code: "ebc", focus: "ciudadanas"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-13",
    module: "Pedagogía y evaluación formativa",
    subtema: "Sociales / proyecto ciudadano",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "El 'proyecto de democracia' consiste en elegir un representante y no hacer nada más el resto del año.",
    stem: "Para que sea formación ciudadana auténtica, debería:",
    options: [
      "Quedarse en la elección simbólica",
      "Incluir diagnóstico, plan de acción, seguimiento y evaluación de impacto en la comunidad escolar",
      "Cancelar toda representación estudiantil",
      "Dejar que solo el docente ejecute las ideas",
    ],
    correct: "B",
    norma: "Las competencias ciudadanas se desarrollan en ciclos de acción y reflexión en la comunidad.",
    theory: "La ciudadanía activa implica agencia, no solo ritual electoral.",
    wrong: {
      A: "La elección sin agenda es cosmética.",
      C: "Eliminar representación niega el derecho.",
      D: "El docente media, no sustituye la agencia estudiantil.",
    },
    tags: [{code: "ebc", focus: "acción ciudadana"}, {code: "ley115", focus: "participación"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-14",
    module: "Currículo y referentes MEN",
    subtema: "Sociales / DBA",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "La planeación de 8° ignora los DBA de sociales y se basa solo en 'lo que siempre se ha enseñado'.",
    stem: "El uso correcto de los DBA es:",
    options: [
      "Ignorarlos por tradición",
      "Tomarlos como referente de aprendizajes esperados para orientar planeación y evaluación",
      "Copiarlos textualmente como único material de clase",
      "Usarlos solo en supervisión",
    ],
    correct: "B",
    norma: "Los DBA orientan saberes y habilidades por grado, complementarios a EBC y al PEI.",
    theory: "La planeación coherente articula referentes, contexto y evidencias.",
    wrong: {
      A: "La tradición no sustituye referentes vigentes.",
      C: "No son un guion literal de clase.",
      D: "Deben usarse de forma continua.",
    },
    tags: [{code: "dba", focus: "sociales"}, {code: "ebc", focus: "planeación"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-15",
    module: "Pedagogía y evaluación formativa",
    subtema: "Sociales / mapa mental vs análisis",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "Toda la evaluación del periodo es un mapa mental decorativo sin argumentación ni uso de fuentes.",
    stem: "Según evaluación formativa del área, conviene:",
    options: [
      "Mantener solo el mapa decorativo",
      "Pedir producciones que argumenten con fuentes, conceptos y evidencia (ensayo, debate, estudio de caso)",
      "Eliminar cualquier producción escrita",
      "Calificar solo la ortografía del mapa",
    ],
    correct: "B",
    norma: "El Decreto 1290 y los EBC exigen evidencias de comprensión y argumentación.",
    theory: "En sociales, el desempeño clave es explicar y argumentar con soporte.",
    wrong: {
      A: "Decorar no acredita pensamiento social.",
      C: "La escritura argumentativa es central.",
      D: "Ortografía no sustituye el análisis.",
    },
    tags: [{code: "decreto1290", focus: "evidencias"}, {code: "ebc", focus: "argumentación"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-16",
    module: "Pedagogía y evaluación formativa",
    subtema: "Sociales / conflicto armado",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "Al abordar el conflicto armado colombiano, el docente impone una lectura única y silencia preguntas de estudiantes.",
    stem: "El abordaje pedagógico más responsable es:",
    options: [
      "Imponer una sola lectura y censurar dudas",
      "Mediar con rigor, fuentes diversas, respeto a víctimas y espacio para preguntas difíciles",
      "Omitir el tema por completo",
      "Convertir la clase en insultos entre posturas",
    ],
    correct: "B",
    norma: "La Cátedra de la Paz y los referentes de sociales orientan memoria histórica con rigor y dignidad.",
    theory: "Los temas sensibles requieren mediación ética, evidencia y cuidado emocional.",
    wrong: {
      A: "La censura no forma pensamiento crítico.",
      C: "Omitir niega el derecho a comprender el país.",
      D: "El insulto no es deliberación.",
    },
    tags: [{code: "ebc", focus: "memoria"}, {code: "ley1620", focus: "cuidado"}],
    dif: 3,
    secs: 115,
  }),
  gold({
    id: "oro-soc-17",
    module: "Currículo y referentes MEN",
    subtema: "Sociales / derechos humanos",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "Se enseñan derechos humanos como lista para recitar, sin relacionarlos con casos escolares (bullying, debido proceso, participación).",
    stem: "La práctica más potente es:",
    options: [
      "Seguir con la lista memorizada",
      "Analizar casos del contexto escolar a la luz de derechos, deberes y rutas institucionales",
      "Afirmar que los derechos 'no aplican en el colegio'",
      "Evaluar solo la cantidad de artículos recitados",
    ],
    correct: "B",
    norma: "La formación en derechos se articula a la convivencia escolar (Ley 1620) y a ciudadanas.",
    theory: "Los derechos se comprenden cuando se aplican a situaciones reales.",
    wrong: {
      A: "Memorizar no garantiza apropiación.",
      C: "La escuela es espacio de derechos.",
      D: "Cantidad de artículos no mide competencia.",
    },
    tags: [{code: "ley1620", focus: "derechos"}, {code: "ebc", focus: "ciudadanas"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-18",
    module: "Pedagogía y evaluación formativa",
    subtema: "Sociales / comparación histórica",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "Al comparar dos periodos, los estudiantes solo dicen 'antes era peor / ahora es mejor' sin criterios.",
    stem: "El docente debería orientar a:",
    options: [
      "Aceptar juicios sin fundamento",
      "Definir criterios de comparación (economía, derechos, participación, territorio) y soportarlos con evidencia",
      "Prohibir cualquier comparación",
      "Reemplazar la comparación por dictado",
    ],
    correct: "B",
    norma: "El pensamiento histórico incluye comparación fundamentada entre sociedades y periodos.",
    theory: "Comparar con criterios evita anacronismos y opiniones vacías.",
    wrong: {
      A: "Sin criterios no hay análisis.",
      C: "Comparar es operación histórica clave.",
      D: "El dictado no sustituye el pensamiento.",
    },
    tags: [{code: "ebc", focus: "comparación histórica"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-19",
    module: "Pedagogía y evaluación formativa",
    subtema: "Sociales / fake news",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "Circula un meme falso sobre una decisión del Concejo municipal. Estudiantes lo comparten como noticia.",
    stem: "La respuesta pedagógica prioritaria es:",
    options: [
      "Ignorar el meme",
      "Hacer una práctica de verificación (fuentes, contraste, sesgos) y producir una conclusión argumentada",
      "Castigar a quien lo recibió sin análisis del contenido",
      "Prohibir hablar de política local",
    ],
    correct: "B",
    norma: "La ciudadanía digital crítica es parte de la formación social contemporánea.",
    theory: "Verificar información es una competencia social transferable.",
    wrong: {
      A: "Ignorar deja circular desinformación.",
      C: "Castigar sin formar no desarrolla criterio.",
      D: "Lo local es objeto legítimo de estudio.",
    },
    tags: [{code: "ebc", focus: "información"}, {code: "lineamientos", focus: "sociales"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-20",
    module: "Currículo y referentes MEN",
    subtema: "Sociales / Estado y poder",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "Al explicar ramas del poder público, el docente no conecta con ejemplos cercanos (Alcaldía, Concejo, jueces).",
    stem: "Para fortalecer comprensión, conviene:",
    options: [
      "Quedarse en el esquema abstracto del libro",
      "Ilustrar funciones con instituciones locales y casos verificables de separación de poderes",
      "Afirmar que 'en la práctica no importa'",
      "Evaluar solo el dibujo de un organigrama",
    ],
    correct: "B",
    norma: "Los EBC buscan comprender la organización del Estado y la participación democrática.",
    theory: "Anclar conceptos políticos en el entorno facilita el aprendizaje significativo.",
    wrong: {
      A: "Lo abstracto sin anclaje suele olvidarse.",
      C: "Minimizar el tema debilita la ciudadanía.",
      D: "El dibujo no acredita comprensión funcional.",
    },
    tags: [{code: "ebc", focus: "Estado"}, {code: "ausubel", focus: "anclaje"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-21",
    module: "Pedagogía y evaluación formativa",
    subtema: "Sociales / trabajo con datos",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "En un estudio sobre migración, no se usan tablas ni mapas; solo anécdotas.",
    stem: "La mejora metodológica más adecuada es:",
    options: [
      "Confiar solo en anécdotas",
      "Combinar relatos con datos, mapas y análisis de causas y efectos",
      "Eliminar cualquier relato humano",
      "Copiar un informe de internet sin citar",
    ],
    correct: "B",
    norma: "El área integra métodos cuantitativos y cualitativos para explicar lo social.",
    theory: "Triangular evidencias fortalece la explicación social.",
    wrong: {
      A: "La anécdota sola no basta.",
      C: "Los relatos también aportan comprensión.",
      D: "Plagiar vulnera ética académica.",
    },
    tags: [{code: "ebc", focus: "métodos"}, {code: "lineamientos", focus: "sociales"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-22",
    module: "Inclusión y convivencia escolar",
    subtema: "Sociales / género",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "Al estudiar liderazgo histórico, el material solo muestra hombres y presenta a las mujeres como 'apoyo doméstico'.",
    stem: "La decisión curricular equitativa es:",
    options: [
      "Mantener el sesgo del material",
      "Diversificar fuentes y problematizar roles de género en la historia y la sociedad",
      "Eliminar el tema de liderazgo",
      "Separar lecturas 'para niños' y 'para niñas'",
    ],
    correct: "B",
    norma: "La educación debe promover equidad de género y reconocimiento de aportes históricos diversos.",
    theory: "Visibilizar y problematizar estereotipos forma ciudadanía democrática.",
    wrong: {
      A: "Reproducir sesgos no es neutral.",
      C: "El liderazgo es contenido válido.",
      D: "Separar refuerza estereotipos.",
    },
    tags: [{code: "ebc", focus: "equidad"}, {code: "ley115", focus: "formación"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-23",
    module: "Pedagogía y evaluación formativa",
    subtema: "Sociales / simulación",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "Se hace un 'Congreso escolar' sin preparación de argumentos ni reglas de respeto; termina en gritos.",
    stem: "Para que la simulación forme, el docente debe:",
    options: [
      "Repetir el caos porque 'así es la política'",
      "Preparar roles, evidencias, reglas de deliberación y cierre reflexivo sobre el proceso",
      "Cancelar definitivamente toda simulación",
      "Dejar que un solo estudiante monopolice el uso de la palabra",
    ],
    correct: "B",
    norma: "Las estrategias activas requieren andamiaje y normas de participación democrática.",
    theory: "La simulación es potente si hay preparación, reglas y metacognición.",
    wrong: {
      A: "Naturalizar el caos no educa.",
      C: "Bien mediada, la simulación es valiosa.",
      D: "Monopolizar niega participación equitativa.",
    },
    tags: [{code: "ebc", focus: "deliberación"}, {code: "vygotsky", focus: "andamiaje"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-24",
    module: "Currículo y referentes MEN",
    subtema: "Sociales / globalización",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "Al tratar globalización, se presenta solo como 'avance tecnológico' sin impactos laborales, culturales o ambientales.",
    stem: "El análisis más completo debería:",
    options: [
      "Quedarse en una visión unilateral positiva",
      "Examinar oportunidades y tensiones (económicas, culturales, ambientales) con evidencia",
      "Rechazar cualquier vínculo internacional",
      "Reducir el tema a marcas de ropa",
    ],
    correct: "B",
    norma: "Los EBC buscan comprender interdependencias globales con mirada crítica.",
    theory: "Los procesos globales son multidimensionales y requieren balance de efectos.",
    wrong: {
      A: "La unilateralidad empobrece el análisis.",
      C: "El aislamiento no explica el presente.",
      D: "Las marcas no agotan el fenómeno.",
    },
    tags: [{code: "ebc", focus: "globalización"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-25",
    module: "Pedagogía y evaluación formativa",
    subtema: "Sociales / evaluación por rúbrica",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "En un debate evaluado, los estudiantes no conocían si se valoraba el uso de fuentes, el respeto o solo 'hablar mucho'.",
    stem: "Lo más coherente con evaluación formativa es:",
    options: [
      "Mantener criterios ocultos",
      "Socializar rúbrica previa: argumentos, evidencia, escucha y respeto normativo",
      "Calificar solo el volumen de voz",
      "Dar la misma nota a todos sin observación",
    ],
    correct: "B",
    norma: "El Decreto 1290 exige criterios claros y conocidos por los estudiantes.",
    theory: "La transparencia evaluativa orienta el desempeño durante la deliberación.",
    wrong: {
      A: "Sin criterios no hay equidad.",
      C: "El volumen no mide calidad argumentativa.",
      D: "La nota uniforme niega diferenciación justa.",
    },
    tags: [{code: "decreto1290", focus: "rúbrica"}, {code: "ebc", focus: "debate"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-26",
    module: "Pedagogía y evaluación formativa",
    subtema: "Sociales / patrimonio",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "El patrimonio local se aborda solo como 'cosa vieja' sin vínculo con identidad y cuidado comunitario.",
    stem: "La mediación más pertinente es:",
    options: [
      "Desvalorizar el patrimonio local",
      "Relacionar patrimonio material/inmaterial con identidad, memoria y responsabilidades ciudadanas",
      "Limitarse a fotos sin interpretación",
      "Estudiar solo patrimonios extranjeros",
    ],
    correct: "B",
    norma: "Los referentes de sociales incluyen identidad cultural y valoración del patrimonio.",
    theory: "El patrimonio se comprende como construcción social viva, no como objeto muerto.",
    wrong: {
      A: "Desvalorizar niega memoria colectiva.",
      C: "La foto sin sentido es insuficiente.",
      D: "Lo local es objeto legítimo de estudio.",
    },
    tags: [{code: "ebc", focus: "patrimonio"}, {code: "dba", focus: "identidad"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-27",
    module: "Inclusión y convivencia escolar",
    subtema: "Sociales / migración en el aula",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "Hay estudiantes migrantes y aparecen comentarios xenófobos. El docente dice que 'no es tema de la clase'.",
    stem: "La respuesta institucional-pedagógica correcta es:",
    options: [
      "Ignorar la xenofobia",
      "Abordar el hecho con enfoque de derechos, cuidado a las víctimas y formación antidiscriminación",
      "Exponer públicamente a los estudiantes migrantes",
      "Pedirles que 'se adapten en silencio'",
    ],
    correct: "B",
    norma: "Ley 1620 y el marco de derechos obligan a prevenir y atender discriminación.",
    theory: "El aula de sociales es espacio privilegiado para trabajar dignidad y convivencia.",
    wrong: {
      A: "Ignorar naturaliza la violencia.",
      C: "Exponer revictimiza.",
      D: "El silencio no garantiza inclusión.",
    },
    tags: [{code: "ley1620", focus: "xenofobia"}, {code: "ebc", focus: "derechos"}],
    dif: 3,
    secs: 110,
  }),
  gold({
    id: "oro-soc-28",
    module: "Pedagogía y evaluación formativa",
    subtema: "Sociales / anacronismo",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "Un estudiante juzga una sociedad del siglo XIX con criterios del presente sin historicizar. El docente valida el juicio.",
    stem: "La corrección pedagógica adecuada es:",
    options: [
      "Validar el anacronismo",
      "Enseñar a historicizar: comprender el contexto de época sin justificar opresiones, y distinguir presente/pasado",
      "Prohibir cualquier juicio ético",
      "Reírse del estudiante",
    ],
    correct: "B",
    norma: "El pensamiento histórico combate el anacronismo y promueve comprensión contextual.",
    theory: "Historicizar no es relativismo ciego: es comprender para explicar con rigor.",
    wrong: {
      A: "El anacronismo distorsiona la explicación.",
      C: "El juicio ético informado es posible y necesario.",
      D: "Ridiculizar bloquea el aprendizaje.",
    },
    tags: [{code: "ebc", focus: "historicidad"}],
    dif: 3,
    secs: 110,
  }),
  gold({
    id: "oro-soc-29",
    module: "Currículo y referentes MEN",
    subtema: "Sociales / medio ambiente y sociedad",
    cargo: "sociales",
    tagsCargo: ["sociales", "ciencias"],
    caso: "Un conflicto por el uso del río se enseña solo como 'tema de biología', sin actores sociales ni normas.",
    stem: "Desde sociales, el aporte específico debería ser:",
    options: [
      "Renunciar al tema porque es de ciencias",
      "Analizar actores, intereses, normas y conflictos socioambientales del territorio",
      "Culpar a un solo grupo sin evidencia",
      "Evitar cualquier salida al territorio",
    ],
    correct: "B",
    norma: "Las ciencias sociales explican conflictos socioambientales con categorías de poder, territorio y ciudadanía.",
    theory: "La interdisciplinariedad potencia la comprensión de problemas complejos.",
    wrong: {
      A: "El problema también es social.",
      C: "Sin evidencia se cae en estigma.",
      D: "El territorio es fuente de aprendizaje.",
    },
    tags: [{code: "ebc", focus: "socioambiental"}, {code: "lineamientos", focus: "territorio"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-30",
    module: "Pedagogía y evaluación formativa",
    subtema: "Sociales / entrevista oral",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "Estudiantes entrevistan a abuelos sobre el barrio, pero no contrastan con archivos ni contextualizan.",
    stem: "Para elevar la calidad histórica de la oralidad, conviene:",
    options: [
      "Tomar la entrevista como verdad absoluta",
      "Tratarla como fuente: triangular con otras evidencias y analizar contexto del testimonio",
      "Descartar toda historia oral",
      "Publicar la entrevista sin consentimiento",
    ],
    correct: "B",
    norma: "La historia oral es fuente válida si se critica y se contrasta metodológicamente.",
    theory: "Toda fuente tiene sesgo; la triangulación fortalece la explicación.",
    wrong: {
      A: "Ninguna fuente es infalible.",
      C: "La oralidad es rica para memoria local.",
      D: "El consentimiento es ético y obligatorio.",
    },
    tags: [{code: "ebc", focus: "fuentes orales"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-31",
    module: "Pedagogía y evaluación formativa",
    subtema: "Sociales / servicio social",
    cargo: "sociales",
    tagsCargo: ["sociales"],
    caso: "El servicio social estudiantil se cumple como 'horas firmadas' sin reflexión sobre impacto comunitario.",
    stem: "La mirada formativa más adecuada es:",
    options: [
      "Priorizar solo la firma de horas",
      "Articular servicio, diagnóstico comunitario y reflexión ética sobre el impacto",
      "Eliminar el servicio social",
      "Usarlo como castigo disciplinario",
    ],
    correct: "B",
    norma: "El servicio social tiene sentido formativo de solidaridad y participación ciudadana.",
    theory: "La experiencia comunitaria educa cuando se reflexiona y se vincula a aprendizajes.",
    wrong: {
      A: "Firmar horas sin sentido es burocracia.",
      C: "Es un espacio formativo valioso.",
      D: "No debe usarse como castigo.",
    },
    tags: [{code: "ley115", focus: "servicio social"}, {code: "ebc", focus: "ciudadanía"}],
    dif: 2,
  }),
  gold({
    id: "oro-soc-32",
    module: "Pedagogía y evaluación formativa",
    subtema: "Sociales / articulación con lenguaje",
    cargo: "sociales",
    tagsCargo: ["sociales", "lenguaje"],
    caso: "Sociales pide ensayos argumentativos, pero no coordina con lenguaje criterios de tesis, evidencia y cohesión.",
    stem: "La gestión pedagógica más efectiva es:",
    options: [
      "Mantener criterios contradictorios entre áreas",
      "Acordar con lenguaje una rúbrica compartida de argumentación aplicada a temas sociales",
      "Eliminar la escritura en sociales",
      "Evaluar solo contenido memorístico sin forma",
    ],
    correct: "B",
    norma: "La argumentación es competencia transversal reforzada por EBC de lenguaje y sociales.",
    theory: "La coherencia interdisciplinar mejora la calidad de las producciones estudiantiles.",
    wrong: {
      A: "La contradicción confunde al estudiante.",
      C: "Escribir es pensar en el área.",
      D: "Memorizar sin argumentar empobrece sociales.",
    },
    tags: [{code: "ebc", focus: "argumentación"}, {code: "ley115", focus: "articulación"}],
    dif: 2,
  }),
];

module.exports = {sociales};
