/**
 * Ola 6 — Refuerzo Ciencias Naturales (32 ítems oro).
 * Especialidad: ciencias. Estilo CNSC/ICFES + lineamientos/EBC/DBA MEN.
 */
const {gold} = require("./gold_handcrafted_core");

/** @type {ReturnType<typeof gold>[]} */
const ciencias = [
  gold({
    id: "oro-cie-01",
    module: "Currículo y referentes MEN",
    subtema: "Ciencias / indagación",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "En grado 6°, el docente pide copiar del tablero la definición de 'hipótesis' y memorizarla para el quiz, sin formular preguntas ni observar fenómenos.",
    stem: "Desde el enfoque de indagación en ciencias, la práctica más débil es:",
    options: [
      "Partir de una pregunta investigable y contrastar con evidencia",
      "Reducir el aprendizaje a memorizar definiciones sin explorar fenómenos",
      "Registrar observaciones y discutir posibles explicaciones",
      "Revisar el diseño experimental con el grupo",
    ],
    correct: "B",
    norma: "Los Lineamientos y EBC de Ciencias Naturales orientan el aprendizaje por indagación y explicación de fenómenos.",
    theory: "La indagación moviliza pregunta, evidencia y explicación; la definición aislada no construye pensamiento científico.",
    wrong: {
      A: "Sí es coherente con indagación.",
      C: "Observar y explicar es núcleo del área.",
      D: "Revisar el diseño fortalece la investigación escolar.",
    },
    tags: [{code: "lineamientos", focus: "indagación"}, {code: "ebc", focus: "ciencias"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-02",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / variables experimentales",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "Estudiantes quieren saber si la temperatura del agua afecta la disolución de azúcar. Cambian a la vez temperatura, cantidad de azúcar y tipo de recipiente.",
    stem: "La orientación pedagógica más adecuada es:",
    options: [
      "Dejar que cambien todas las variables a la vez 'para ir más rápido'",
      "Ayudarles a controlar variables: modificar solo la temperatura y mantener constantes las demás",
      "Eliminar el experimento y dictar la conclusión",
      "Evaluar solo la limpieza del laboratorio",
    ],
    correct: "B",
    norma: "Los referentes de ciencias privilegian el diseño experimental con control de variables.",
    theory: "Identificar variable independiente, dependiente y controladas es parte del pensamiento científico escolar.",
    wrong: {
      A: "Cambiar varias variables impide atribuir causas.",
      C: "Dictar la conclusión anula la indagación.",
      D: "La higiene importa, pero no sustituye el aprendizaje experimental.",
    },
    tags: [{code: "lineamientos", focus: "experimento"}, {code: "ebc", focus: "ciencias"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-03",
    module: "Currículo y referentes MEN",
    subtema: "Ciencias / DBA",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "Un docente de 5° planea solo con el libro de texto y no revisa los DBA del grado para ciencias.",
    stem: "El uso más pertinente de los DBA sería:",
    options: [
      "Ignorarlos porque 'el libro basta'",
      "Usarlos como referente de saberes y habilidades esperadas para orientar planeación y evaluación",
      "Reemplazar completamente el PEI por los DBA",
      "Aplicarlos solo el día de la visita de supervisión",
    ],
    correct: "B",
    norma: "Los DBA son un referente de planeación curricular complementario a EBC y al PEI.",
    theory: "Alinear propósitos, actividades y evidencias con referentes nacionales mejora la coherencia del área.",
    wrong: {
      A: "El libro no sustituye los referentes MEN.",
      C: "Los DBA no reemplazan el PEI.",
      D: "Su uso debe ser continuo, no cosmético.",
    },
    tags: [{code: "dba", focus: "ciencias"}, {code: "ebc", focus: "planeación"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-04",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / modelos",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "Para enseñar el sistema solar, el docente usa solo un dibujo plano en el cuaderno y afirma que 'los planetas están fijados en el cielo'.",
    stem: "La mediación más potente sería:",
    options: [
      "Insistir en la frase literal del cuaderno",
      "Usar modelos (maquetas, simulaciones) y discutir límites del modelo frente al fenómeno real",
      "Omitir el tema por ser abstracto",
      "Evaluar solo ortografía de nombres de planetas",
    ],
    correct: "B",
    norma: "Los lineamientos de ciencias promueven modelos y representaciones para explicar fenómenos.",
    theory: "Los modelos son herramientas de pensamiento: se construyen, se contrastan y se reconocen sus límites.",
    wrong: {
      A: "La frase fija puede reforzar ideas alternativas.",
      C: "Lo abstracto se aborda con mediación, no con omisión.",
      D: "Nombrar no equivale a comprender el sistema.",
    },
    tags: [{code: "lineamientos", focus: "modelos"}, {code: "ebc", focus: "ciencias"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-05",
    module: "Currículo y referentes MEN",
    subtema: "Ciencias / PRAE",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "El colegio tiene PRAE en el PEI, pero ciencias lo trata como una cartelera anual sin articulación con biología, química ni el entorno cercano.",
    stem: "La decisión más alineada es:",
    options: [
      "Dejar el PRAE como decoración institucional",
      "Articular el PRAE con preguntas del entorno (agua, residuos, biodiversidad) y con el currículo de ciencias",
      "Eliminar el PRAE porque 'no es evaluable en Saber'",
      "Delegarlo solo a la jornada complementaria sin docentes del área",
    ],
    correct: "B",
    norma: "El PRAE es un proyecto pedagógico transversal que articula la dimensión ambiental con el currículo.",
    theory: "La educación ambiental gana sentido cuando se ancla en problemas reales del contexto escolar.",
    wrong: {
      A: "El PRAE no es ornamento.",
      C: "Su valor no se reduce a pruebas estandarizadas.",
      D: "Requiere liderazgo pedagógico del área.",
    },
    tags: [{code: "lineamientos", focus: "PRAE"}, {code: "ley115", focus: "proyectos transversales"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-06",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / ideas alternativas",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "Varios estudiantes afirman que 'las plantas se alimentan solo de tierra'. El docente marca incorrecto y pasa al siguiente tema.",
    stem: "La actuación formativa más adecuada es:",
    options: [
      "Ignorar la idea porque 'ya se corrigió'",
      "Explicitar la idea alternativa, contrastarla con evidencia (fotosíntesis/experimentos) y reconstruir la explicación",
      "Ridiculizar la respuesta frente al grupo",
      "Pedir que copien la definición correcta diez veces",
    ],
    correct: "B",
    norma: "La evaluación formativa en ciencias usa el error como insumo para reorganizar ideas.",
    theory: "El cambio conceptual requiere confrontar ideas previas con evidencia y nuevas explicaciones (Ausubel/constructivismo).",
    wrong: {
      A: "Las ideas alternativas persisten si no se trabajan.",
      C: "Ridiculizar bloquea el aprendizaje.",
      D: "Copiar no garantiza comprensión.",
    },
    tags: [{code: "ausubel", focus: "saberes previos"}, {code: "decreto1290", focus: "formativa"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-07",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / laboratorio seguro",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "Antes de una práctica con ácidos diluidos, el docente no socializa normas de seguridad ni el uso de gafas y bata.",
    stem: "Lo más responsable pedagógicamente es:",
    options: [
      "Iniciar ya 'para no perder tiempo'",
      "Socializar riesgos, EPP y protocolos, y verificar comprensión antes de manipular sustancias",
      "Dejar que aprendan de los accidentes",
      "Hacer la práctica solo el docente sin que observen",
    ],
    correct: "B",
    norma: "La seguridad en el laboratorio es parte de la formación científica y del cuidado de la comunidad educativa.",
    theory: "La mediación incluye normas, anticipación de riesgos y responsabilidad compartida.",
    wrong: {
      A: "La seguridad no es tiempo perdido.",
      C: "El accidente no es método de enseñanza.",
      D: "Observar sin preparación tampoco forma hábitos seguros.",
    },
    tags: [{code: "lineamientos", focus: "laboratorio"}],
    dif: 1,
    secs: 70,
  }),
  gold({
    id: "oro-cie-08",
    module: "Inclusión y convivencia escolar",
    subtema: "Ciencias / inclusión en lab",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "Un estudiante con discapacidad visual queda fuera de las prácticas porque 'no puede ver el cambio de color'.",
    stem: "Según inclusión educativa, conviene:",
    options: [
      "Eximirlo permanentemente del laboratorio",
      "Diseñar ajustes (descripciones táctiles/auditivas, roles, materiales adaptados) para su participación plena",
      "Evaluarlo solo con dictado de definiciones",
      "Trasladarlo a otra asignatura ese día",
    ],
    correct: "B",
    norma: "El Decreto 1421 exige ajustes razonables para participación y aprendizaje en igualdad de condiciones.",
    theory: "La indagación puede mediarse por múltiples canales sensoriales (DUA).",
    wrong: {
      A: "Eximir es exclusión disfrazada.",
      C: "Solo dictado empobrece el derecho a aprender ciencias.",
      D: "Trasladar no resuelve la barrera.",
    },
    tags: [{code: "decreto1421", focus: "ajustes en ciencias"}],
    dif: 3,
    secs: 110,
  }),
  gold({
    id: "oro-cie-09",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / evidencia",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "Tras un experimento, el docente pide 'la respuesta correcta del libro' y no discute los datos que los grupos obtuvieron.",
    stem: "La práctica más alineada al área es:",
    options: [
      "Priorizar siempre el libro sobre los datos del aula",
      "Analizar los datos obtenidos, discutir fuentes de error y construir explicaciones con evidencia",
      "Calificar solo la limpieza del reporte",
      "Evitar el debate porque genera desorden",
    ],
    correct: "B",
    norma: "En ciencias, la evidencia empírica y su interpretación son centrales en los EBC.",
    theory: "Aprender ciencias es argumentar con datos, no solo confirmar el texto.",
    wrong: {
      A: "El libro orienta, no sustituye la evidencia propia.",
      C: "La forma del reporte no basta.",
      D: "El debate científico es aprendizaje, no desorden.",
    },
    tags: [{code: "ebc", focus: "evidencia"}, {code: "lineamientos", focus: "ciencias"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-10",
    module: "Currículo y referentes MEN",
    subtema: "Ciencias / biodiversidad",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "Al enseñar ecosistemas, el docente usa solo ejemplos de otros continentes y no conecta con el páramo o el río cercano a la IE.",
    stem: "Para enseñar ecosistemas con sentido territorial, la decisión didáctica más pertinente es:",
    options: [
      "Mantener solo ejemplos lejanos 'más cultos'",
      "Articular conceptos con el entorno local y comparar con otros ecosistemas",
      "Eliminar el tema de ecosistemas",
      "Evaluar solo listas de especies memorizadas",
    ],
    correct: "B",
    norma: "Los referentes de ciencias impulsan la comprensión del entorno natural colombiano y su diversidad.",
    theory: "El aprendizaje significativo ancla lo nuevo en experiencias y contextos cercanos (Ausubel).",
    wrong: {
      A: "Lo local no es menos académico.",
      C: "Es un eje del área.",
      D: "Memorizar listas no garantiza comprensión ecológica.",
    },
    tags: [{code: "ausubel", focus: "contexto"}, {code: "lineamientos", focus: "ecosistemas"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-11",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / evaluación formativa",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "La única evidencia de ciencias en el periodo es un examen final de 40 preguntas de selección múltiple.",
    stem: "Según el Decreto 1290 y la didáctica del área, conviene:",
    options: [
      "Mantener solo el examen final",
      "Diversificar evidencias: bitácoras, reportes, rúbricas de indagación y retroalimentación en proceso",
      "Eliminar cualquier calificación",
      "Evaluar únicamente asistencia al laboratorio",
    ],
    correct: "B",
    norma: "El Decreto 1290 concibe la evaluación como formativa, integral y con evidencias diversas.",
    theory: "En ciencias, el proceso de indagación debe ser visible en la evaluación, no solo el producto final.",
    wrong: {
      A: "Una sola prueba empobrece el SIEE del área.",
      C: "La evaluación sigue siendo necesaria con criterios.",
      D: "Asistencia no acredita aprendizaje científico.",
    },
    tags: [{code: "decreto1290", focus: "evidencias"}, {code: "ebc", focus: "ciencias"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-12",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / CTSA",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "Al hablar de minería y agua, el docente dice que 'eso es política, no ciencias' y evita el debate.",
    stem: "Desde un enfoque CTSA (ciencia-tecnología-sociedad-ambiente), lo más adecuado es:",
    options: [
      "Evitar todo vínculo con problemas sociales",
      "Analizar el fenómeno científico y sus implicaciones sociales y ambientales con evidencia",
      "Imponer una sola postura partidista",
      "Sustituir la clase por un mitin",
    ],
    correct: "B",
    norma: "Los lineamientos de ciencias incluyen la dimensión CTSA para formar ciudadanía científica.",
    theory: "Comprender ciencia implica situarla en problemas reales con argumentación basada en evidencia.",
    wrong: {
      A: "El aislamiento empobrece el sentido del área.",
      C: "La escuela forma pensamiento crítico, no adoctrinamiento.",
      D: "El mitin no es secuenciación didáctica.",
    },
    tags: [{code: "lineamientos", focus: "CTSA"}],
    dif: 3,
    secs: 110,
  }),
  gold({
    id: "oro-cie-13",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / representaciones",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "Estudiantes confunden 'calor' y 'temperatura'. El docente responde solo: 'miren el glosario'.",
    stem: "Una mediación más efectiva sería:",
    options: [
      "Repetir el glosario en voz alta",
      "Usar situaciones concretas, analogías y mediciones para distinguir ambos conceptos",
      "Eliminar ambos términos del programa",
      "Evaluar solo la definición literal",
    ],
    correct: "B",
    norma: "Los EBC de ciencias buscan comprensión conceptual, no solo vocabulario.",
    theory: "Los conceptos científicos se clarifican con múltiples representaciones y contraste de casos.",
    wrong: {
      A: "Repetir no garantiza discriminación conceptual.",
      C: "Son conceptos centrales.",
      D: "La literalidad no asegura comprensión.",
    },
    tags: [{code: "ebc", focus: "conceptos"}, {code: "vygotsky", focus: "mediación"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-14",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / trabajo colaborativo",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "En el laboratorio, un solo estudiante hace todo y el resto copia el informe.",
    stem: "Para fortalecer aprendizaje colaborativo auténtico, el docente debería:",
    options: [
      "Permitir que siempre trabaje el más rápido",
      "Asignar roles rotativos (registro, medición, seguridad, análisis) con responsabilidad individual y grupal",
      "Prohibir el trabajo en equipo",
      "Calificar solo al líder del grupo",
    ],
    correct: "B",
    norma: "La formación científica incluye habilidades de trabajo en equipo y comunicación de resultados.",
    theory: "La interdependencia positiva y la responsabilidad individual distinguen lo colaborativo de lo grupal superficial.",
    wrong: {
      A: "Concentrar la tarea excluye a otros del aprendizaje.",
      C: "El laboratorio se beneficia del trabajo conjunto mediado.",
      D: "Calificar solo al líder refuerza la exclusión.",
    },
    tags: [{code: "ebc", focus: "colaboración"}, {code: "vygotsky", focus: "aprendizaje social"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-15",
    module: "Currículo y referentes MEN",
    subtema: "Ciencias / salud",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "En una unidad sobre sistema digestivo, el docente no conecta con hábitos alimentarios ni con el PAE institucional.",
    stem: "La articulación más pertinente es:",
    options: [
      "Separar siempre cuerpo humano y vida cotidiana",
      "Relacionar estructuras/funciones con decisiones de salud y contexto alimentario escolar",
      "Eliminar la anatomía del currículo",
      "Enseñar solo marcas comerciales de comida",
    ],
    correct: "B",
    norma: "Los referentes de ciencias articulan conocimiento del cuerpo con cuidado de la salud.",
    theory: "El aprendizaje significativo vincula lo biológico con prácticas cotidianas.",
    wrong: {
      A: "La separación empobrece el sentido.",
      C: "Es un contenido clave.",
      D: "Publicidad no es educación científica.",
    },
    tags: [{code: "dba", focus: "cuerpo y salud"}, {code: "ausubel", focus: "cotidiano"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-16",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / gráficos",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "Los estudiantes grafican datos de crecimiento de plantas, pero el docente no pide interpretar tendencias ni incertidumbre.",
    stem: "El cierre más potente de la actividad es:",
    options: [
      "Archivar el gráfico sin discusión",
      "Interpretar patrones, comparar grupos y discutir posibles errores de medición",
      "Premiar solo el gráfico más 'bonito'",
      "Convertir la clase en un concurso de colores",
    ],
    correct: "B",
    norma: "Los EBC incluyen habilidades de registro, organización e interpretación de información.",
    theory: "El gráfico es medio para argumentar, no un adorno del cuaderno.",
    wrong: {
      A: "Sin interpretación no hay aprendizaje científico.",
      C: "La estética no sustituye el análisis.",
      D: "El concurso de colores desvía el propósito.",
    },
    tags: [{code: "ebc", focus: "interpretación de datos"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-17",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / preguntas investigables",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "Un estudiante pregunta: '¿Por qué el cielo es azul?'. El docente responde: 'Eso no entra en el examen'.",
    stem: "La respuesta más coherente con el área es:",
    options: [
      "Cerrar la curiosidad porque no está en el quiz",
      "Acoger la pregunta, orientar una indagación viable (nivel del grado) y vincularla a luz/atmósfera",
      "Decir que es magia",
      "Pedir que busque en internet sin mediación ni socialización",
    ],
    correct: "B",
    norma: "La curiosidad y la pregunta son motores del aprendizaje científico escolar.",
    theory: "El docente media la transformación de curiosidad en pregunta investigable ajustada al nivel.",
    wrong: {
      A: "El examen no debe matar la indagación.",
      C: "No es explicación científica.",
      D: "Sin mediación se pierde oportunidad de aprendizaje colectivo.",
    },
    tags: [{code: "lineamientos", focus: "pregunta"}, {code: "vygotsky", focus: "mediación"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-18",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / simulaciones",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "Sin laboratorio completo, el docente descarta enseñar circuitos porque 'no hay materiales'.",
    stem: "Una alternativa didáctica sólida es:",
    options: [
      "Omitir el tema todo el año",
      "Combinar simulaciones, materiales de bajo costo y discusión de limitaciones de cada representación",
      "Solo proyectar un video sin actividad del estudiante",
      "Evaluar el tema sin enseñarlo",
    ],
    correct: "B",
    norma: "Los referentes permiten diversas estrategias para aproximarse a fenómenos cuando el contexto es limitado.",
    theory: "La mediación multimodal mantiene el propósito de aprendizaje pese a restricciones materiales.",
    wrong: {
      A: "La omisión niega el derecho a aprender.",
      C: "El video pasivo no basta.",
      D: "Evaluar sin enseñar es inequitativo.",
    },
    tags: [{code: "lineamientos", focus: "mediaciones"}, {code: "ebc", focus: "ciencias"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-19",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / informe científico escolar",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "El 'informe' de laboratorio es copiar un formato con conclusiones ya escritas por el docente.",
    stem: "Para que el informe sea evidencia de aprendizaje, debe:",
    options: [
      "Seguir siendo copia literal",
      "Incluir pregunta, procedimiento, datos propios, análisis y conclusiones argumentadas por el estudiante",
      "Reducirse a una foto del experimento",
      "Eliminarse porque 'quita tiempo de teoría'",
    ],
    correct: "B",
    norma: "La comunicación de resultados es una competencia central en ciencias escolares.",
    theory: "Escribir científicamente consolida la explicación basada en evidencia.",
    wrong: {
      A: "Copiar no evidencia pensamiento.",
      C: "La foto sin análisis es insuficiente.",
      D: "Teoría y práctica se articulan, no se oponen.",
    },
    tags: [{code: "ebc", focus: "comunicación científica"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-20",
    module: "Currículo y referentes MEN",
    subtema: "Ciencias / química cotidiana",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "En química de media, se enseñan fórmulas sin relacionarlas con combustión, corrosión o medicamentos del entorno.",
    stem: "La mejora curricular más alineada es:",
    options: [
      "Aumentar solo la cantidad de fórmulas",
      "Articular representaciones simbólicas con fenómenos cotidianos y problemas auténticos",
      "Eliminar la simbología química",
      "Enseñar solo recetas de cocina sin conceptualización",
    ],
    correct: "B",
    norma: "Los EBC buscan explicar fenómenos mediante modelos y lenguaje de la química.",
    theory: "La triple representación (macro-micro-simbólico) se fortalece con contextos reales.",
    wrong: {
      A: "Más fórmulas sin sentido no mejoran comprensión.",
      C: "El lenguaje simbólico es necesario.",
      D: "Lo cotidiano sin concepto tampoco forma el área.",
    },
    tags: [{code: "ebc", focus: "química"}, {code: "ausubel", focus: "significativo"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-21",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / error experimental",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "Un grupo obtiene un resultado 'inesperado'. El docente anula su trabajo y les da los datos 'correctos'.",
    stem: "La actuación formativa correcta es:",
    options: [
      "Sustituir siempre los datos reales por los esperados",
      "Analizar con el grupo posibles fuentes de error y qué se aprende del resultado obtenido",
      "Sancionar al grupo por 'fallar'",
      "Ocultar el resultado al resto de la clase",
    ],
    correct: "B",
    norma: "El trabajo científico escolar valora la honestidad de los datos y el análisis crítico.",
    theory: "El error experimental es información pedagógica, no fracaso moral.",
    wrong: {
      A: "Falsificar datos contradice la ética científica.",
      C: "Sancionar castiga el aprendizaje.",
      D: "Socializar el análisis enriquece al grupo.",
    },
    tags: [{code: "lineamientos", focus: "ética científica"}, {code: "decreto1290", focus: "formativa"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-22",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / STEM interdisciplinar",
    cargo: "ciencias",
    tagsCargo: ["ciencias", "matematicas"],
    caso: "Para un proyecto de calidad del agua, ciencias no coordina con matemáticas (tablas/gráficos) ni con lenguaje (informe).",
    stem: "La gestión pedagógica más potente es:",
    options: [
      "Mantener las áreas totalmente aisladas",
      "Acordar un proyecto interdisciplinar con roles y evidencias compartidas entre áreas",
      "Dejar que solo ciencias cargue todo el proyecto",
      "Cancelar el proyecto por complejidad",
    ],
    correct: "B",
    norma: "El PEI y los proyectos permiten articulación curricular entre áreas.",
    theory: "Los problemas auténticos se abordan mejor con miradas interdisciplinares mediadas.",
    wrong: {
      A: "El aislamiento empobrece el proyecto.",
      C: "La sobrecarga de un área es insostenible.",
      D: "La complejidad se gestiona, no se evita.",
    },
    tags: [{code: "ley115", focus: "PEI"}, {code: "ebc", focus: "integración"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-23",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / mitos y evidencia",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "Circula en el curso un rumor sobre un 'remedio casero milagroso'. El docente lo prohíbe mencionar.",
    stem: "La oportunidad pedagógica más adecuada es:",
    options: [
      "Censurar sin análisis",
      "Guiar una evaluación crítica de afirmaciones con criterios de evidencia y fuentes confiables",
      "Aceptar el rumor como contenido oficial",
      "Convertirlo en castigo disciplinario",
    ],
    correct: "B",
    norma: "La alfabetización científica incluye discernir información confiable.",
    theory: "Pensamiento crítico: contrastar afirmaciones con evidencia y sesgos.",
    wrong: {
      A: "Censurar no forma criterio.",
      C: "Acreditar rumores es anti-científico.",
      D: "No es un problema solo de disciplina.",
    },
    tags: [{code: "ebc", focus: "pensamiento crítico"}, {code: "lineamientos", focus: "ciencias"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-24",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / secuenciación",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "El docente introduce notación química avanzada antes de experiencias macroscópicas con cambios de estado o reacciones simples.",
    stem: "La secuenciación más didáctica sería:",
    options: [
      "Empezar siempre por lo más abstracto",
      "Partir de fenómenos observables y avanzar hacia modelos y lenguaje simbólico",
      "Eliminar lo simbólico del curso",
      "Evaluar lo simbólico el primer día sin mediación",
    ],
    correct: "B",
    norma: "Los lineamientos sugieren progresiones de lo concreto/observacional a modelos más abstractos.",
    theory: "La trayectoria de representación favorece comprensión antes de formalizar.",
    wrong: {
      A: "Lo abstracto primero suele generar memorización vacía.",
      C: "El lenguaje simbólico es necesario en su momento.",
      D: "Evaluar sin enseñar es inequitativo.",
    },
    tags: [{code: "lineamientos", focus: "progresión"}, {code: "bruner", focus: "representaciones"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-25",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / rúbrica de indagación",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "Los estudiantes no saben qué se valora en el proyecto científico: solo reciben una nota final.",
    stem: "La práctica más formativa es:",
    options: [
      "Mantener criterios secretos",
      "Compartir una rúbrica clara (pregunta, método, datos, explicación, comunicación) antes y durante el proceso",
      "Calificar solo la portada",
      "Comparar notas en público para 'motivar'",
    ],
    correct: "B",
    norma: "El Decreto 1290 exige criterios claros y comunicación de la evaluación.",
    theory: "La rúbrica favorece autorregulación y calidad del proceso de indagación.",
    wrong: {
      A: "Sin criterios no hay equidad.",
      C: "La portada no acredita competencias científicas.",
      D: "La comparación pública daña el clima y no forma.",
    },
    tags: [{code: "decreto1290", focus: "criterios"}, {code: "ebc", focus: "indagación"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-26",
    module: "Currículo y referentes MEN",
    subtema: "Ciencias / física cotidiana",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "Al enseñar fuerza y movimiento, no se usan ejemplos del transporte escolar, el recreo o herramientas del entorno.",
    stem: "Para fortalecer sentido y transferencia, conviene:",
    options: [
      "Quedarse solo en fórmulas descontextualizadas",
      "Modelar situaciones cotidianas y luego formalizar con lenguaje de la física",
      "Evitar cualquier medición",
      "Sustituir física por solo historia de científicos",
    ],
    correct: "B",
    norma: "Los EBC buscan explicar el mundo físico cercano con modelos científicos.",
    theory: "La transferencia se potencia cuando el concepto nace de un problema reconocible.",
    wrong: {
      A: "La fórmula sin fenómeno suele ser frágil.",
      C: "Medir es parte del quehacer científico.",
      D: "La biografía no sustituye la modelación.",
    },
    tags: [{code: "ebc", focus: "física"}, {code: "ausubel", focus: "anclaje"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-27",
    module: "Inclusión y convivencia escolar",
    subtema: "Ciencias / género y STEM",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "En el laboratorio, se asignan a las estudiantes solo roles de 'aseo' y a los estudiantes la manipulación de equipos.",
    stem: "La actuación equitativa del docente es:",
    options: [
      "Mantener esos roles porque 'siempre ha sido así'",
      "Rotar roles de liderazgo técnico y asegurar acceso equitativo a equipos y tareas cognitivas",
      "Separar grupos por género de forma permanente",
      "Eliminar el laboratorio para evitar el conflicto",
    ],
    correct: "B",
    norma: "La escuela debe garantizar igualdad de oportunidades de aprendizaje sin estereotipos de género.",
    theory: "La participación equitativa en STEM se construye con mediación consciente de roles.",
    wrong: {
      A: "La costumbre no justifica exclusión.",
      C: "Separar refuerza estereotipos.",
      D: "Eliminar el laboratorio niega el derecho a aprender.",
    },
    tags: [{code: "ley115", focus: "equidad"}, {code: "ebc", focus: "participación"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-28",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / campo",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "Una salida de observación al huerto escolar se convierte en recreo libre sin guía de observación ni registro.",
    stem: "Para que sea experiencia científica, el docente debe:",
    options: [
      "Dejar el recreo sin estructura",
      "Definir pregunta, instrumentos de registro y socialización de hallazgos al regreso",
      "Prohibir salidas porque 'no son clase'",
      "Evaluar solo el comportamiento en la fila",
    ],
    correct: "B",
    norma: "Las salidas pedagógicas requieren intencionalidad y evidencia de aprendizaje.",
    theory: "El trabajo de campo es indagación situada cuando hay mediación y registro.",
    wrong: {
      A: "Sin estructura no hay indagación.",
      C: "El entorno es laboratorio ampliado.",
      D: "Comportamiento no sustituye evidencia científica.",
    },
    tags: [{code: "lineamientos", focus: "campo"}, {code: "decreto1290", focus: "evidencias"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-29",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / metacognición",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "Al terminar la unidad, no se pide a los estudiantes revisar qué entendieron, qué les falta ni cómo investigaron.",
    stem: "Una cierre metacognitivo pertinente sería:",
    options: [
      "Pasar directamente al siguiente capítulo",
      "Guiar una reflexión sobre estrategias usadas, evidencias logradas y nuevas preguntas",
      "Solo publicar el promedio del curso",
      "Hacer copia del resumen del docente",
    ],
    correct: "B",
    norma: "La evaluación formativa incluye reflexión sobre el propio aprendizaje.",
    theory: "La metacognición consolida el oficio de investigar y aprender ciencias.",
    wrong: {
      A: "Sin cierre se pierde consolidación.",
      C: "El promedio no enseña a pensar el proceso.",
      D: "Copiar el resumen es pasivo.",
    },
    tags: [{code: "decreto1290", focus: "metacognición"}, {code: "ebc", focus: "ciencias"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-30",
    module: "Currículo y referentes MEN",
    subtema: "Ciencias / cambio climático",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "El tema de cambio climático se reduce a una frase alarmista sin datos, escalas ni acciones locales posibles.",
    stem: "El abordaje más sólido es:",
    options: [
      "Usar solo miedo como estrategia",
      "Trabajar evidencias, escalas (local-global) y acciones posibles desde el PRAE y el aula",
      "Negar el fenómeno para 'no asustar'",
      "Dejarlo solo para redes sociales",
    ],
    correct: "B",
    norma: "La educación ambiental y científica debe basarse en evidencia y formación para la acción responsable.",
    theory: "Comprender sistemas complejos exige datos, causalidad y agencia ciudadana.",
    wrong: {
      A: "El miedo sin comprensión paraliza.",
      C: "Negar contradice la evidencia científica.",
      D: "La escuela debe mediar el tema.",
    },
    tags: [{code: "lineamientos", focus: "ambiente"}, {code: "ebc", focus: "sistemas"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-31",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / evaluación auténtica",
    cargo: "ciencias",
    tagsCargo: ["ciencias"],
    caso: "Para 'innovar', el docente reemplaza toda evaluación por un concurso de disfraces de científicos famosos.",
    stem: "La lectura más equilibrada es:",
    options: [
      "El disfraz basta como evidencia de competencia científica",
      "Puede ser motivador, pero debe articularse a desempeños científicos evaluables con criterios claros",
      "Toda gamificación es inválida",
      "Hay que eliminar la motivación del aula",
    ],
    correct: "B",
    norma: "La evaluación debe dar cuenta de aprendizajes del área con criterios explícitos (D.1290).",
    theory: "La motivación ayuda si está al servicio de desempeños, no como sustituto de ellos.",
    wrong: {
      A: "El disfraz no acredita indagación ni explicación.",
      C: "La gamificación puede ser válida con propósito.",
      D: "La motivación es aliada del aprendizaje.",
    },
    tags: [{code: "decreto1290", focus: "desempeños"}, {code: "ebc", focus: "ciencias"}],
    dif: 2,
  }),
  gold({
    id: "oro-cie-32",
    module: "Pedagogía y evaluación formativa",
    subtema: "Ciencias / articulación primaria-secundaria",
    cargo: "ciencias",
    tagsCargo: ["ciencias", "primaria"],
    caso: "Docentes de 5° y 6° no comparten qué ideas alternativas y habilidades de indagación ya se trabajaron.",
    stem: "Para mejorar la continuidad del área, conviene:",
    options: [
      "Ignorar lo hecho en primaria",
      "Hacer transición curricular: socializar aprendizajes previos, acuerdos de lenguaje y progresiones",
      "Repetir exactamente el mismo proyecto cada año sin ajuste",
      "Culpar a los estudiantes por 'llegar mal'",
    ],
    correct: "B",
    norma: "La coherencia curricular vertical es responsabilidad institucional del área.",
    theory: "La progresión de aprendizajes requiere continuidad y andamiaje entre grados.",
    wrong: {
      A: "Partir de cero desperdicia saberes previos.",
      C: "Repetir sin ajuste no es progresión.",
      D: "Culpar no mejora el sistema.",
    },
    tags: [{code: "ebc", focus: "progresión"}, {code: "ausubel", focus: "previos"}],
    dif: 2,
  }),
];

module.exports = {ciencias};
