/**
 * Tercera ola oro: casos situados por especialidad
 * (preescolar, matemáticas, lenguaje, directivos + refuerzo ciencias/sociales).
 */
const {gold} = require("./gold_handcrafted_core");

/** @type {ReturnType<typeof gold>[]} */
const wave3 = [
  // ========== PREESCOLAR ==========
  gold({
    id: "oro-esp-pre-01",
    module: "Pedagogía y evaluación formativa",
    subtema: "Preescolar / juego simbólico",
    cargo: "preescolar",
    tagsCargo: ["preescolar"],
    caso: "En transición, una niña organiza un 'consultorio' con muñecos y negociaciones de roles; la docente interrumpe para 'hacer planas'.",
    stem: "La decisión más alineada a educación inicial es:",
    options: [
      "Cortar el juego porque 'no es académico'",
      "Prolongar y mediar el juego simbólico como espacio de lenguaje, cuidado y representación",
      "Castigar la negociación entre pares",
      "Sustituir el juego por examen escrito",
    ],
    correct: "B",
    norma: "La Guía MEN 50 y las orientaciones de inicial privilegian el juego como mediación del desarrollo integral.",
    theory: "En el juego simbólico el niño representa roles y construye significados (Piaget/Vygotsky).",
    wrong: {
      A: "El juego es académico en inicial.",
      C: "La negociación es aprendizaje social.",
      D: "El examen escrito no es el eje de inicial.",
    },
    tags: [
      {code: "guiaMen50", focus: "juego simbólico"},
      {code: "vygotsky", focus: "mediación en juego"},
      {code: "piaget", focus: "representación"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-esp-pre-02",
    module: "Pedagogía y evaluación formativa",
    subtema: "Preescolar / rutinas de cuidado",
    cargo: "preescolar",
    tagsCargo: ["preescolar"],
    caso: "Durante el lavado de manos, la docente aprovecha para contar, nombrar partes del cuerpo y cantar secuencias.",
    stem: "Esta práctica se interpreta mejor como:",
    options: [
      "Pérdida de tiempo frente al 'contenido real'",
      "Intencionalidad pedagógica que integra cuidado, lenguaje y nociones matemáticas informales",
      "Solo higiene sin valor educativo",
      "Evaluación sumativa del periodo",
    ],
    correct: "B",
    norma: "En inicial, cuidado y aprendizaje son inseparables (orientaciones MEN / Guía 50).",
    theory: "Las rutinas situadas generan aprendizajes significativos anclados en la experiencia cotidiana (Ausubel).",
    wrong: {
      A: "El contenido real incluye cuidado y lenguaje.",
      C: "La higiene es educativa cuando se media.",
      D: "No es el momento de certificación sumativa.",
    },
    tags: [
      {code: "guiaMen50", focus: "cuidado e intencionalidad"},
      {code: "ausubel", focus: "experiencia cotidiana"},
    ],
    dif: 1,
    secs: 70,
  }),
  gold({
    id: "oro-esp-pre-03",
    module: "Inclusión y convivencia escolar",
    subtema: "Preescolar / inclusión sensorial",
    cargo: "preescolar",
    tagsCargo: ["preescolar"],
    caso: "Un niño con hipersensibilidad auditiva se desregula en asambleas ruidosas; la respuesta ha sido sancionarlo por 'indisciplina'.",
    stem: "La respuesta inclusiva correcta es:",
    options: [
      "Insistir en sanción para 'acostumbrarlo'",
      "Diseñar ajustes (ubicación, auriculares, tiempos, señales visuales) y documentar en PIAR si aplica",
      "Excluirlo de todas las asambleas sin plan",
      "Ignorar la hipersensibilidad",
    ],
    correct: "B",
    norma: "El Decreto 1421 orienta ajustes razonables y PIAR para participación y aprendizaje.",
    theory: "La autorregulación se apoya con andamiaje ambiental y emocional, no con castigo.",
    wrong: {
      A: "El castigo no es ajuste razonable.",
      C: "La exclusión sin plan vulnera participación.",
      D: "Ignorar niega el derecho a la educación inclusiva.",
    },
    tags: [
      {code: "decreto1421", focus: "ajustes en inicial"},
      {code: "guiaMen50", focus: "bienestar"},
    ],
    dif: 3,
    secs: 115,
  }),
  gold({
    id: "oro-esp-pre-04",
    module: "Pedagogía y evaluación formativa",
    subtema: "Preescolar / documentación pedagógica",
    cargo: "preescolar",
    tagsCargo: ["preescolar"],
    caso: "La IE exige 'notas numéricas' semanales en transición como en 5°.",
    stem: "La práctica más pertinente es:",
    options: [
      "Aplicar promedios idénticos a primaria",
      "Documentar procesos con observaciones, evidencias y devolución cualitativa a familias",
      "No registrar nada",
      "Usar solo ranking de 'más avanzado'",
    ],
    correct: "B",
    norma: "La evaluación en inicial es formativa y cualitativa; el 1290 también privilegia el carácter formativo.",
    theory: "La documentación hace visible el desarrollo y orienta la mediación docente.",
    wrong: {
      A: "Primaria no es el molde de inicial.",
      C: "Sin registro no hay seguimiento.",
      D: "El ranking daña el clima y no describe desarrollo.",
    },
    tags: [
      {code: "guiaMen50", focus: "evaluación cualitativa"},
      {code: "decreto1290", focus: "formativa"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-esp-pre-05",
    module: "Pedagogía y evaluación formativa",
    subtema: "Preescolar / lenguaje oral",
    cargo: "preescolar",
    tagsCargo: ["preescolar", "lenguaje"],
    caso: "Una docente corrige de inmediato cada error oral del niño y le pide callar si 'habla mal'.",
    stem: "Para fortalecer lenguaje en inicial conviene:",
    options: [
      "Silenciar para evitar errores",
      "Ampliar y reformular el habla del niño (andamiaje lingüístico) en situaciones auténticas",
      "Enseñar solo silabeo sin conversación",
      "Evaluar oralidad con examen escrito",
    ],
    correct: "B",
    norma: "Las orientaciones de inicial priorizan el lenguaje oral como base de la literacidad emergente.",
    theory: "Vygotsky: el adulto mediador amplía el discurso dentro de la ZDP lingüística.",
    wrong: {
      A: "Silenciar empobrece el input y la confianza.",
      C: "Sin conversación no hay uso real del lenguaje.",
      D: "La oralidad se evalúa en situación oral/observada.",
    },
    tags: [
      {code: "guiaMen50", focus: "lenguaje oral"},
      {code: "vygotsky", focus: "andamiaje lingüístico"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-esp-pre-06",
    module: "Currículo y referentes MEN",
    subtema: "Preescolar / nociones matemáticas",
    cargo: "preescolar",
    tagsCargo: ["preescolar", "matematicas"],
    caso: "Se enseñan 'sumas formales' en hoja a los 4 años, sin conteo, clasificación ni juego con cantidades.",
    stem: "Una secuencia más coherente con desarrollo y referentes sería:",
    options: [
      "Insistir en algoritmos formales prematuros",
      "Trabajar clasificación, serieción, conteo y comparación en juego y rutinas",
      "Eliminar toda experiencia numérica",
      "Memorizar tablas de multiplicar",
    ],
    correct: "B",
    norma: "En inicial, las nociones matemáticas emergen de la exploración y el juego, no de la formalización temprana.",
    theory: "Piaget: operaciones concretas se construyen desde acciones; Bruner: enactivo antes que simbólico.",
    wrong: {
      A: "Lo formal prematuro suele ser frágil.",
      C: "Sí hay matemáticas informales potentes.",
      D: "Las tablas no corresponden a esa edad.",
    },
    tags: [
      {code: "guiaMen50", focus: "pensamiento matemático temprano"},
      {code: "piaget", focus: "acciones"},
      {code: "bruner", focus: "enactivo"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-esp-pre-07",
    module: "Inclusión y convivencia escolar",
    subtema: "Preescolar / convivencia temprana",
    cargo: "preescolar",
    tagsCargo: ["preescolar"],
    caso: "Dos niños pelean por un juguete; la docente solo dice 'no peleen' y no media el conflicto.",
    stem: "La mediación más educativa es:",
    options: [
      "Ignorar el episodio",
      "Nombrar emociones, modelar turnos y acuerdos simples, y hacer seguimiento breve",
      "Castigar a ambos sin escuchar",
      "Entregar el juguete al más fuerte",
    ],
    correct: "B",
    norma: "La promoción de convivencia (Ley 1620 / Guías 49-51) también aplica en la primera infancia con mediación adulta.",
    theory: "La regulación socioemocional se aprende con andamiaje, no solo con prohibiciones.",
    wrong: {
      A: "Ignorar enseña que el conflicto no se elabora.",
      C: "Sin escucha no hay aprendizaje social.",
      D: "Premiar la fuerza modela inequidad.",
    },
    tags: [
      {code: "guiaMen49", focus: "mediación temprana"},
      {code: "ley1620", focus: "promoción"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-esp-pre-08",
    module: "Pedagogía y evaluación formativa",
    subtema: "Preescolar / familias",
    cargo: "preescolar",
    tagsCargo: ["preescolar"],
    caso: "Una familia exige 'más tareas de planas' porque teme que el niño 'llegue mal a primero'.",
    stem: "La conversación profesional más adecuada es:",
    options: [
      "Ceder y saturar de planas",
      "Explicar el enfoque de desarrollo integral, mostrar evidencias del progreso y acordar apoyos en casa coherentes con el juego y el lenguaje",
      "Descalificar a la familia",
      "Eliminar toda comunicación con la familia",
    ],
    correct: "B",
    norma: "La corresponsabilidad familia–escuela en inicial se construye con diálogo informado (Guía 50).",
    theory: "La alianza educa cuando se ancla en evidencias y en el sentido del desarrollo, no en ansiedad escolarizante.",
    wrong: {
      A: "Ceder a la ansiedad puede dañar el enfoque.",
      C: "Descalificar rompe la alianza.",
      D: "Sin familias se pierde continuidad.",
    },
    tags: [{code: "guiaMen50", focus: "diálogo con familias"}],
    dif: 2,
  }),

  // ========== MATEMÁTICAS ==========
  gold({
    id: "oro-esp-mat-01",
    module: "Currículo y referentes MEN",
    subtema: "Matemáticas / resolución de problemas",
    cargo: "matematicas",
    tagsCargo: ["matematicas", "primaria"],
    caso: "En 5°, el docente enseña solo el algoritmo de la división y luego pone 20 ejercicios idénticos sin contexto.",
    stem: "Una mejora alineada a EBC/lineamientos es:",
    options: [
      "Aumentar a 40 ejercicios idénticos",
      "Plantear problemas con sentido, múltiples estrategias y discusión de representaciones",
      "Eliminar la división del currículo",
      "Evaluar solo velocidad de cálculo",
    ],
    correct: "B",
    norma: "EBC y lineamientos de matemáticas centran el área en resolución de problemas y pensamiento matemático.",
    theory: "Bruner: progresar entre representaciones; la discusión hace visible el razonamiento.",
    wrong: {
      A: "Más de lo mismo no garantiza comprensión.",
      C: "La división es aprendizaje esencial del grado.",
      D: "La velocidad no mide comprensión profunda.",
    },
    tags: [
      {code: "ebc", focus: "pensamiento matemático"},
      {code: "lineamientos", focus: "matemáticas"},
      {code: "bruner", focus: "representaciones"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-esp-mat-02",
    module: "Pedagogía y evaluación formativa",
    subtema: "Matemáticas / error productivo",
    cargo: "matematicas",
    tagsCargo: ["matematicas"],
    caso: "Un estudiante obtiene 36 en 6×7 y el docente solo marca 'X' sin analizar el error.",
    stem: "La práctica formativa más potente es:",
    options: [
      "Solo bajar la nota",
      "Usar el error para indagar la estrategia (p. ej. 6×6+6) y reenseñar con representación",
      "Prohibir el uso de material concreto",
      "Pasar al siguiente tema sin cierre",
    ],
    correct: "B",
    norma: "El Decreto 1290 orienta la evaluación al servicio del aprendizaje y la retroalimentación.",
    theory: "El error es evidencia del pensamiento del estudiante; la mediación lo convierte en aprendizaje.",
    wrong: {
      A: "La nota sola no enseña.",
      C: "El concreto puede aclarar el hecho multiplicativo.",
      D: "Sin cierre se acumula incomprensión.",
    },
    tags: [
      {code: "decreto1290", focus: "retroalimentación"},
      {code: "dba", focus: "multiplicación"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-esp-mat-03",
    module: "Currículo y referentes MEN",
    subtema: "Matemáticas / DBA por grado",
    cargo: "matematicas",
    tagsCargo: ["matematicas", "primaria"],
    caso: "El plan de 3° trabaja ecuaciones algebraicas formales de secundaria 'para adelantar'.",
    stem: "Lo más coherente con DBA/EBC es:",
    options: [
      "Seguir adelantando sin bases",
      "Focalizar aprendizajes esenciales del grado y fortalecer sentido numérico y problemas",
      "Eliminar problemas verbales",
      "Enseñar solo geometría y omitir número",
    ],
    correct: "B",
    norma: "Los DBA orientan aprendizajes por grado; saltar sin bases fragiliza la progresión.",
    theory: "La progresión curricular respeta la construcción de estructuras (Piaget) y la ZDP (Vygotsky).",
    wrong: {
      A: "Adelantar sin bases genera simulacro de avance.",
      C: "Los problemas verbales desarrollan modelación.",
      D: "Número y geometría se articulan en el grado.",
    },
    tags: [
      {code: "dba", focus: "grado"},
      {code: "ebc", focus: "progresión"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-esp-mat-04",
    module: "Pedagogía y evaluación formativa",
    subtema: "Matemáticas / trabajo colaborativo",
    cargo: "matematicas",
    tagsCargo: ["matematicas"],
    caso: "En resolución de problemas, un estudiante avanza cuando discute con un par y se bloquea en silencio absoluto.",
    stem: "La estrategia más potente es:",
    options: [
      "Prohibir toda discusión",
      "Diseñar roles de discusión matemática (explicar, cuestionar, representar) con andamiaje",
      "Dar siempre la respuesta final del docente",
      "Evaluar solo el producto individual sin proceso",
    ],
    correct: "B",
    norma: "La enseñanza puede articular evaluación formativa (1290) con mediación social del aprendizaje.",
    theory: "Vygotsky: la ZDP se activa con pares más capaces y lenguaje matemático compartido.",
    wrong: {
      A: "La discusión es recurso didáctico, no ruido.",
      C: "Dar la respuesta anula el razonamiento.",
      D: "El proceso revela estrategias y errores.",
    },
    tags: [
      {code: "vygotsky", focus: "ZDP matemática"},
      {code: "decreto1290", focus: "proceso"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-esp-mat-05",
    module: "Inclusión y convivencia escolar",
    subtema: "Matemáticas / PIAR y evidencias",
    cargo: "matematicas",
    tagsCargo: ["matematicas", "primaria"],
    caso: "Un estudiante con PIAR comprende con material base 10, pero la evaluación solo admite algoritmo escrito cronometrado.",
    stem: "La decisión inclusiva correcta es:",
    options: [
      "Mantener el cronómetro idéntico sin ajustes",
      "Ajustar tiempo/forma de evidencia manteniendo el aprendizaje esencial acordado en el PIAR",
      "Eximir de toda evidencia matemática",
      "Bajar la meta esencial sin acuerdo del PIAR",
    ],
    correct: "B",
    norma: "Decreto 1421: ajustes razonables; 1290: evaluación con criterios al servicio del aprendizaje.",
    theory: "Equidad es diversificar medios de demostración, no eliminar la competencia matemática esencial.",
    wrong: {
      A: "Igualdad formal puede ser exclusión.",
      C: "Eximir niega el derecho a aprender.",
      D: "Cambiar la meta exige proceso PIAR, no improvisación.",
    },
    tags: [
      {code: "decreto1421", focus: "ajustes en matemáticas"},
      {code: "decreto1290", focus: "evidencias"},
    ],
    dif: 3,
    secs: 120,
  }),
  gold({
    id: "oro-esp-mat-06",
    module: "Currículo y referentes MEN",
    subtema: "Matemáticas / representaciones",
    cargo: "matematicas",
    tagsCargo: ["matematicas"],
    caso: "Se pasa de fichas a símbolos algebraicos en un solo paso, sin tablas, dibujos ni lenguaje verbal.",
    stem: "Bruner y la didáctica recomiendan:",
    options: [
      "Saltar directo al símbolo siempre",
      "Transitar enactivo → icónico → simbólico con conexiones explícitas",
      "Eliminar el símbolo para siempre",
      "Usar solo memorización de fórmulas",
    ],
    correct: "B",
    norma: "Los referentes de matemáticas valoran múltiples representaciones y conexiones entre ellas.",
    theory: "Bruner: la trayectoria representacional sostiene la comprensión durable.",
    wrong: {
      A: "El salto abrupto genera ritual sin sentido.",
      C: "El símbolo es meta, no enemigo.",
      D: "La fórmula sin modelo es frágil.",
    },
    tags: [
      {code: "bruner", focus: "E-I-S"},
      {code: "lineamientos", focus: "matemáticas"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-esp-mat-07",
    module: "Pedagogía y evaluación formativa",
    subtema: "Matemáticas / criterios de evaluación",
    cargo: "matematicas",
    tagsCargo: ["matematicas"],
    caso: "La rúbrica de un problema solo dice 'bien/mal'; no contempla estrategia, representación ni explicación.",
    stem: "Para alinear evaluación y aprendizaje debería:",
    options: [
      "Mantener bien/mal",
      "Explicitar criterios de proceso, representación, resultado y comunicación matemática",
      "Evaluar solo presentación estética",
      "Entregar la rúbrica después de calificar",
    ],
    correct: "B",
    norma: "El 1290 exige claridad de criterios; los EBC valoran procesos matemáticos.",
    theory: "Criterios visibles permiten autorregulación y feedback accionable.",
    wrong: {
      A: "Bien/mal no orienta la mejora.",
      C: "La estética no es el objeto matemático.",
      D: "Los criterios deben conocerse antes.",
    },
    tags: [
      {code: "decreto1290", focus: "criterios"},
      {code: "ebc", focus: "procesos"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-esp-mat-08",
    module: "Currículo y referentes MEN",
    subtema: "Matemáticas / contexto",
    cargo: "matematicas",
    tagsCargo: ["matematicas", "primaria"],
    caso: "Los problemas hablan de metros de nieve y tarifas de metro en una IE rural tropical sin adaptación.",
    stem: "La mejora didáctica es:",
    options: [
      "Insistir en contextos ajenos 'porque vienen en el libro'",
      "Contextualizar cantidades y situaciones al entorno manteniendo la estructura matemática del DBA",
      "Abandonar los problemas",
      "Enseñar solo cálculos sin situación",
    ],
    correct: "B",
    norma: "Los referentes se contextualizan en el PEI y la realidad del estudiantado.",
    theory: "Ausubel: la significatividad aumenta con anclaje en saberes y experiencias previas.",
    wrong: {
      A: "El libro no es el currículo.",
      C: "Los problemas son el corazón del área.",
      D: "Sin situación se empobrece la modelación.",
    },
    tags: [
      {code: "ausubel", focus: "contexto"},
      {code: "dba", focus: "problemas"},
      {code: "ley115", focus: "PEI"},
    ],
    dif: 2,
  }),

  // ========== LENGUAJE ==========
  gold({
    id: "oro-esp-len-01",
    module: "Currículo y referentes MEN",
    subtema: "Lenguaje / prácticas sociales",
    cargo: "lenguaje",
    tagsCargo: ["lenguaje", "primaria"],
    caso: "El periodo de lenguaje se reduce a dictados diarios y listas de palabras, sin lectura de textos completos.",
    stem: "Desde lineamientos/EBC de lenguaje, conviene:",
    options: [
      "Mantener solo dictados",
      "Organizar secuencias de lectura, escritura, oralidad y escucha con textos auténticos",
      "Eliminar la escritura",
      "Enseñar solo morfología descontextualizada",
    ],
    correct: "B",
    norma: "Lineamientos y EBC de lenguaje orientan hacia prácticas sociales del lenguaje.",
    theory: "Se aprende a leer y escribir leyendo y escribiendo con propósito comunicativo.",
    wrong: {
      A: "El dictado aislado no desarrolla competencia comunicativa.",
      C: "La escritura es práctica central.",
      D: "La morfología sin uso pierde sentido.",
    },
    tags: [
      {code: "lineamientos", focus: "lenguaje"},
      {code: "ebc", focus: "competencias comunicativas"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-esp-len-02",
    module: "Pedagogía y evaluación formativa",
    subtema: "Lenguaje / proceso de escritura",
    cargo: "lenguaje",
    tagsCargo: ["lenguaje"],
    caso: "Los estudiantes entregan el texto 'final' a la primera y solo reciben nota, sin borradores ni criterios.",
    stem: "Una secuencia formativa potente incluye:",
    options: [
      "Solo nota final",
      "Planificar–textualizar–revisar con rúbrica conocida y retroalimentación entre pares/docente",
      "Prohibir la revisión",
      "Evaluar solo cantidad de páginas",
    ],
    correct: "B",
    norma: "El 1290 orienta evaluación formativa; los referentes de lenguaje valoran el proceso de escritura.",
    theory: "La revisión con criterios desarrolla metacognición y calidad textual.",
    wrong: {
      A: "La nota sola no enseña a escribir mejor.",
      C: "La revisión es el corazón del oficio escritor.",
      D: "La extensión no define calidad.",
    },
    tags: [
      {code: "decreto1290", focus: "proceso de escritura"},
      {code: "lineamientos", focus: "escritura"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-esp-len-03",
    module: "Currículo y referentes MEN",
    subtema: "Lenguaje / comprensión lectora",
    cargo: "lenguaje",
    tagsCargo: ["lenguaje", "primaria"],
    caso: "Tras leer un texto argumentativo, la única actividad es copiar el primer párrafo al cuaderno.",
    stem: "Para fortalecer comprensión crítica debería:",
    options: [
      "Seguir solo con copia",
      "Formular preguntas de interpretación, evaluación de argumentos y producción de respuesta propia",
      "Evitar textos argumentativos",
      "Medir solo velocidad de lectura en voz alta",
    ],
    correct: "B",
    norma: "EBC de lenguaje incluyen niveles de comprensión y uso crítico de la información.",
    theory: "La lectura crítica exige inferencia, evaluación y toma de postura con evidencia del texto.",
    wrong: {
      A: "Copiar no garantiza comprensión.",
      C: "El argumentativo es clave en la formación ciudadana.",
      D: "La velocidad no es comprensión.",
    },
    tags: [
      {code: "ebc", focus: "lectura crítica"},
      {code: "dba", focus: "comprensión"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-esp-len-04",
    module: "Pedagogía y evaluación formativa",
    subtema: "Lenguaje / saberes previos",
    cargo: "lenguaje",
    tagsCargo: ["lenguaje"],
    caso: "Se introduce un género textual nuevo sin explorar qué saben los estudiantes ni para qué sirve ese género en la vida.",
    stem: "Ausubel y la didáctica del lenguaje sugieren:",
    options: [
      "Empezar por la definición abstracta y el examen",
      "Activar saberes previos, propósito comunicativo y modelos del género antes de producir",
      "Omitir modelos textuales",
      "Enseñar solo ortografía del género",
    ],
    correct: "B",
    norma: "La planeación con referentes de área articula propósito, género y evaluación.",
    theory: "Ausubel: el aprendizaje significativo ancla lo nuevo en la estructura cognitiva previa.",
    wrong: {
      A: "Sin anclaje, la definición se olvida.",
      C: "Los modelos orientan la producción.",
      D: "La ortografía es parte, no el todo.",
    },
    tags: [
      {code: "ausubel", focus: "género textual"},
      {code: "lineamientos", focus: "lenguaje"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-esp-len-05",
    module: "Inclusión y convivencia escolar",
    subtema: "Lenguaje / diversidad lingüística",
    cargo: "lenguaje",
    tagsCargo: ["lenguaje", "primaria"],
    caso: "Un estudiante habla una variedad regional; compañeros se burlan y el docente exige 'hablar bien' ridiculizando el acento.",
    stem: "La respuesta pedagógica correcta es:",
    options: [
      "Reforzar la burla como 'corrección'",
      "Valorar la diversidad lingüística, detener la discriminación y enseñar registros según contexto comunicativo",
      "Prohibir que el estudiante hable en clase",
      "Ignorar el hostigamiento",
    ],
    correct: "B",
    norma: "La Guía 49 y la Ley 1620 exigen prevención de discriminación; el lenguaje escolar debe ser inclusivo.",
    theory: "Enseñar registros (formal/informal) no implica estigmatizar la identidad lingüística.",
    wrong: {
      A: "Ridiculizar no es enseñar.",
      C: "Callar vulnera participación.",
      D: "Ignorar permite que escale el daño.",
    },
    tags: [
      {code: "guiaMen49", focus: "no discriminación"},
      {code: "ley1620", focus: "prevención"},
      {code: "lineamientos", focus: "variación lingüística"},
    ],
    dif: 3,
    secs: 115,
  }),
  gold({
    id: "oro-esp-len-06",
    module: "Pedagogía y evaluación formativa",
    subtema: "Lenguaje / oralidad",
    cargo: "lenguaje",
    tagsCargo: ["lenguaje"],
    caso: "La oralidad no se enseña ni se evalúa porque 'es difícil de calificar'.",
    stem: "La mejora profesional es:",
    options: [
      "Seguir omitiendo la oralidad",
      "Diseñar situaciones orales auténticas con rúbricas de claridad, escucha y argumentación",
      "Sustituir oralidad por más ortografía",
      "Evaluar oralidad solo por volumen de voz",
    ],
    correct: "B",
    norma: "Los referentes de lenguaje incluyen oralidad y escucha como prácticas centrales.",
    theory: "Lo que se enseña y evalúa con criterios se desarrolla; lo omitido se debilita.",
    wrong: {
      A: "Omitir empobrece la competencia comunicativa.",
      C: "Ortografía no reemplaza oralidad.",
      D: "El volumen no es argumentación.",
    },
    tags: [
      {code: "lineamientos", focus: "oralidad"},
      {code: "decreto1290", focus: "criterios orales"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-esp-len-07",
    module: "Currículo y referentes MEN",
    subtema: "Lenguaje / multimodalidad",
    cargo: "lenguaje",
    tagsCargo: ["lenguaje"],
    caso: "Los estudiantes producen un podcast escolar; la evaluación solo mira 'si leyeron bien el guion' y ignora audiencia y propósito.",
    stem: "Una evaluación más alineada al área valoraría:",
    options: [
      "Solo fluidez de lectura del guion",
      "Propósito, audiencia, organización discursiva, claridad y uso ético de fuentes",
      "Solo efectos de sonido",
      "Solo cantidad de minutos",
    ],
    correct: "B",
    norma: "Las prácticas sociales del lenguaje incluyen producciones multimodales con intención comunicativa.",
    theory: "Evaluar el propósito y la audiencia desarrolla competencia comunicativa real.",
    wrong: {
      A: "Leer guion no basta.",
      C: "El sonido es recurso, no el único criterio.",
      D: "La duración no define calidad.",
    },
    tags: [
      {code: "ebc", focus: "producción multimodal"},
      {code: "lineamientos", focus: "lenguaje"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-esp-len-08",
    module: "Pedagogía y evaluación formativa",
    subtema: "Lenguaje / andamiaje lector",
    cargo: "lenguaje",
    tagsCargo: ["lenguaje", "primaria"],
    caso: "Un texto está por encima del nivel independiente de varios estudiantes; el docente solo dice 'léanlo en silencio' y evalúa.",
    stem: "La mediación adecuada es:",
    options: [
      "Mantener lectura silenciosa sin apoyo",
      "Andamiar con vocabulario clave, lectura compartida y preguntas guía antes de la autonomía",
      "Bajar siempre a textos triviales sin desafío",
      "Castigar a quien no comprende",
    ],
    correct: "B",
    norma: "La enseñanza formativa acompaña trayectorias diversas hacia aprendizajes esenciales (1290 / inclusión).",
    theory: "Vygotsky: el texto desafiante se aborda en ZDP con mediación, no en soledad punitiva.",
    wrong: {
      A: "Sin andamiaje, el desafío se vuelve fracaso.",
      C: "Sin desafío no hay progreso.",
      D: "Castigar no enseña a comprender.",
    },
    tags: [
      {code: "vygotsky", focus: "lectura mediada"},
      {code: "decreto1290", focus: "trayectorias"},
    ],
    dif: 2,
  }),

  // ========== DIRECTIVOS ==========
  gold({
    id: "oro-esp-dir-01",
    module: "Gestión institucional y PEI",
    subtema: "Directivos / liderazgo pedagógico",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "La coordinación dedica el 90% del tiempo a disciplina de pasillo y casi nada a acompañar planeación ni evidencias de aprendizaje.",
    stem: "Un liderazgo más pedagógico priorizaría:",
    options: [
      "Solo vigilancia de pasillos",
      "Acompañar aula, analizar evidencias de aprendizaje y apoyar planes de mejoramiento docente",
      "Eliminar el SIEE",
      "Delegar toda la pedagogía a las familias",
    ],
    correct: "B",
    norma: "La gestión directiva debe velar por la calidad del servicio educativo (PEI, 1860, profesionalización 1278).",
    theory: "El liderazgo pedagógico mejora resultados cuando se centra en la enseñanza y el aprendizaje.",
    wrong: {
      A: "La convivencia importa, pero no sustituye el foco de aprendizaje.",
      C: "El SIEE es obligatorio y orientador.",
      D: "Las familias no reemplazan la gestión pedagógica.",
    },
    tags: [
      {code: "decreto1278", focus: "calidad del servicio"},
      {code: "ley115", focus: "PEI"},
      {code: "decreto1860", focus: "gestión"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-esp-dir-02",
    module: "Gestión institucional y PEI",
    subtema: "Directivos / SIEE",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "El SIEE no se socializa; docentes aplican criterios distintos y las familias desconocen la escala.",
    stem: "La acción directiva correcta es:",
    options: [
      "Mantener la opacidad",
      "Actualizar, socializar y monitorear la aplicación coherente del SIEE (Decreto 1290)",
      "Eliminar criterios de promoción",
      "Imponer una escala informal distinta cada periodo",
    ],
    correct: "B",
    norma: "El Decreto 1290 exige sistema institucional de evaluación conocido y aplicado.",
    theory: "La transparencia de criterios genera confianza y mejora la autorregulación del aprendizaje.",
    wrong: {
      A: "La opacidad genera inequidad.",
      C: "La promoción requiere criterios.",
      D: "La inconsistencia vulnera el debido proceso evaluativo.",
    },
    tags: [{code: "decreto1290", focus: "SIEE"}],
    dif: 2,
  }),
  gold({
    id: "oro-esp-dir-03",
    module: "Inclusión y convivencia escolar",
    subtema: "Directivos / rutas de convivencia",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "Hay un caso Tipo II y la rectoría decide 'arreglarlo en secreto' sin comité ni registro.",
    stem: "Lo correcto es:",
    options: [
      "Mantener el secreto informal",
      "Activar la ruta (Guías 49/51, Ley 1620), proteger, registrar y hacer seguimiento",
      "Publicar nombres en redes",
      "Expulsar sin procedimiento",
    ],
    correct: "B",
    norma: "Ley 1620 y Guías MEN 49/51 exigen ruta de atención integral con trazabilidad.",
    theory: "La informalidad protege la imagen, no los derechos.",
    wrong: {
      A: "El secreto informal puede ser omisión.",
      C: "Publicar nombres vulnera intimidad.",
      D: "Sin procedimiento no hay debido proceso.",
    },
    tags: [
      {code: "ley1620", focus: "ruta"},
      {code: "guiaMen49", focus: "atención"},
      {code: "guiaMen51", focus: "protocolo"},
    ],
    dif: 3,
    secs: 120,
  }),
  gold({
    id: "oro-esp-dir-04",
    module: "Gestión institucional y PEI",
    subtema: "Directivos / gobierno escolar",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "El consejo directivo no se reúne; decisiones de impacto se toman solo por WhatsApp del rector.",
    stem: "Según Decreto 1860 / Ley 115, conviene:",
    options: [
      "Seguir solo por WhatsApp",
      "Reactivar instancias del gobierno escolar con actas, participación y decisiones trazables",
      "Eliminar el gobierno escolar",
      "Sustituir el consejo por encuestas anónimas en redes",
    ],
    correct: "B",
    norma: "El Decreto 1860 organiza el gobierno escolar; la participación es parte del PEI.",
    theory: "La gobernanza escolar legítima requiere instancias, no solo liderazgo carismático.",
    wrong: {
      A: "WhatsApp no reemplaza el órgano oficial.",
      C: "El gobierno escolar es estructural.",
      D: "Las redes no son el consejo directivo.",
    },
    tags: [
      {code: "decreto1860", focus: "gobierno escolar"},
      {code: "ley115", focus: "PEI"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-esp-dir-05",
    module: "Inclusión y convivencia escolar",
    subtema: "Directivos / inclusión institucional",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "Ingresan estudiantes con discapacidad y la IE responde: 'no estamos preparados; mejor otra institución'.",
    stem: "La postura legal y ética correcta es:",
    options: [
      "Negar el cupo por falta de 'preparación'",
      "Garantizar atención con PIAR, ajustes y trabajo de equipo interdisciplinario",
      "Aceptar el cupo pero sin ajustes",
      "Eximir de toda evaluación sin criterios",
    ],
    correct: "B",
    norma: "El Decreto 1421 obliga a la atención educativa inclusiva con PIAR y ajustes razonables.",
    theory: "La preparación se construye en el hacer institucional, no como precondición para excluir.",
    wrong: {
      A: "La falta de preparación no justifica exclusión.",
      C: "Sin ajustes no hay inclusión real.",
      D: "Eximir sin criterios niega el derecho a aprender.",
    },
    tags: [{code: "decreto1421", focus: "deber institucional"}],
    dif: 3,
    secs: 115,
  }),
  gold({
    id: "oro-esp-dir-06",
    module: "Gestión institucional y PEI",
    subtema: "Directivos / acompañamiento docente",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "Tras resultados bajos en evidencias internas, la dirección solo envía memorandos sin observación de aula ni plan de apoyo.",
    stem: "Una gestión de mejoramiento debería:",
    options: [
      "Multiplicar memorandos",
      "Observar práctica, co-planificar, definir metas de aprendizaje y hacer seguimiento formativo (1278/calidad)",
      "Culpar públicamente a un docente en reunión general",
      "Ignorar los resultados",
    ],
    correct: "B",
    norma: "La evaluación y el mejoramiento del servicio educativo son horizontes del estatuto y de la gestión escolar.",
    theory: "El cambio pedagógico ocurre con acompañamiento situado, no con presión documental sola.",
    wrong: {
      A: "El memorando no enseña a enseñar mejor.",
      C: "La humillación pública destruye clima profesional.",
      D: "Ignorar niega el derecho a la calidad.",
    },
    tags: [{code: "decreto1278", focus: "mejoramiento"}],
    dif: 2,
  }),
  gold({
    id: "oro-esp-dir-07",
    module: "Gestión institucional y PEI",
    subtema: "Directivos / PEI vivo",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "El PEI está actualizado en el archivo, pero la planeación de área no lo consulta ni lo traduce a metas.",
    stem: "Para que el PEI sea gestión real hay que:",
    options: [
      "Dejarlo solo en el archivo",
      "Alinear planes de área, SIEE y proyectos al horizonte del PEI con participación docente",
      "Reemplazar el PEI por tendencias de redes",
      "Eliminar el consejo académico",
    ],
    correct: "B",
    norma: "La Ley 115 define el PEI como proyecto orientador de la institución.",
    theory: "Un PEI vivo se evidencia en decisiones cotidianas de currículo, evaluación y convivencia.",
    wrong: {
      A: "Archivado no es implementado.",
      C: "Las redes no sustituyen el PEI.",
      D: "El consejo académico es instancia clave.",
    },
    tags: [
      {code: "ley115", focus: "PEI"},
      {code: "decreto1860", focus: "implementación"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-esp-dir-08",
    module: "Inclusión y convivencia escolar",
    subtema: "Directivos / clima y datos",
    cargo: "directivos",
    tagsCargo: ["directivos"],
    caso: "La IE no analiza indicadores de convivencia ni reincidencia; actúa caso a caso sin lectura institucional.",
    stem: "Según Guía 49, una mejora de gestión sería:",
    options: [
      "Seguir solo reactivos",
      "Hacer lectura de contexto, priorizar riesgos y planear promoción/prevención con el comité",
      "Ocultar estadísticas",
      "Sancionar de forma masiva sin diagnóstico",
    ],
    correct: "B",
    norma: "La Guía 49 pide lectura de lo que ocurre en el EE para orientar el manual y la ruta.",
    theory: "La gestión basada en evidencia anticipa riesgos y enfoca recursos.",
    wrong: {
      A: "Lo reactivo llega tarde.",
      C: "Ocultar impide mejorar.",
      D: "La sanción masiva sin diagnóstico es injusta e ineficaz.",
    },
    tags: [
      {code: "guiaMen49", focus: "lectura de contexto"},
      {code: "ley1620", focus: "prevención"},
    ],
    dif: 2,
  }),

  // ========== CIENCIAS / SOCIALES (refuerzo especialidad) ==========
  gold({
    id: "oro-esp-cie-01",
    module: "Currículo y referentes MEN",
    subtema: "Ciencias / indagación",
    cargo: "ciencias",
    tagsCargo: ["ciencias", "primaria"],
    caso: "En 4°, el tema 'estados de la materia' se enseña solo con definición para memorizar, sin observación ni registro.",
    stem: "Desde lineamientos de ciencias, lo más coherente es:",
    options: [
      "Memorizar definiciones y repetir",
      "Diseñar indagación con observación, registro de evidencias y explicación",
      "Omitir el tema",
      "Copiar la Wikipedia al cuaderno",
    ],
    correct: "B",
    norma: "Los lineamientos de ciencias naturales orientan hacia indagación y explicación basada en evidencia.",
    theory: "Aprender ciencia es aprender a preguntar, observar y argumentar.",
    wrong: {
      A: "La memorización aislada es frágil.",
      C: "Es aprendizaje esencial del grado.",
      D: "Copiar no es indagar.",
    },
    tags: [
      {code: "lineamientos", focus: "ciencias"},
      {code: "ebc", focus: "indagación"},
    ],
    dif: 2,
  }),
  gold({
    id: "oro-esp-soc-01",
    module: "Currículo y referentes MEN",
    subtema: "Sociales / ciudadanía",
    cargo: "sociales",
    tagsCargo: ["sociales", "primaria"],
    caso: "Tras un conflicto en el barrio, la clase de sociales evita el tema y sigue solo con listas de fechas.",
    stem: "Una práctica alineada a competencias ciudadanas sería:",
    options: [
      "Evitar todo problema social",
      "Analizar el conflicto con respeto, evidencia y propuestas de convivencia, articulado a EBC/ciudadanía",
      "Tomar partido partidista desde el tablero",
      "Sustituir la clase por castigo colectivo",
    ],
    correct: "B",
    norma: "EBC de competencias ciudadanas y lineamientos de sociales forman pensamiento crítico y convivencia.",
    theory: "El contexto local es oportunidad de aprendizaje ciudadano mediado éticamente.",
    wrong: {
      A: "Evitar empobrece la formación ciudadana.",
      C: "El adoctrinamiento no es pensamiento crítico.",
      D: "El castigo colectivo no enseña análisis social.",
    },
    tags: [
      {code: "ebc", focus: "competencias ciudadanas"},
      {code: "lineamientos", focus: "sociales"},
      {code: "ley1620", focus: "formación para la convivencia"},
    ],
    dif: 2,
  }),
];

// Expansión situada: microcasos únicos por especialidad (volumen controlado).
const specialtyMicro = [
  {
    esp: "preescolar",
    module: "Pedagogía y evaluación formativa",
    tags: [
      {code: "guiaMen50", focus: "inicial"},
      {code: "piaget", focus: "desarrollo"},
    ],
    items: [
      ["Un niño de 5 años aún no escribe su nombre con letra convencional y se le niega el recreo.", "Acompañar la literacidad emergente con juego, nombre propio y trazos significativos; no castigar el desarrollo", "Inicial no sanciona el ritmo madurativo.", "La escritura emerge con sentido, no con privación."],
      ["El rincón de arte se cierra 'porque ensucia'.", "Mantener exploración artística con rutinas de cuidado del espacio", "El arte es dimensión del desarrollo integral.", "La organización se enseña, no se elimina la experiencia."],
      ["Se usa solo ficha fotocopiada todo el día.", "Equilibrar ficha puntual con juego, movimiento y proyectos cortos", "La ficha no puede ser el currículo de inicial.", "El cuerpo y el juego son mediaciones privilegiadas."],
      ["Un niño bilingüe (castellano–lengua indígena) es corregido para que 'deje su lengua'.", "Valorar la lengua propia y fortalecer el castellano como L2/adicional sin estigma", "La diversidad cultural es riqueza del sistema educativo.", "Vygotsky: el lenguaje materno media el pensamiento."],
      ["No hay registro de accidentes menores ni acuerdos de cuidado.", "Protocolizar cuidado, registro y comunicación con familias", "El cuidado es parte de la gestión de inicial.", "La trazabilidad protege derechos."],
      ["La asamblea matutina es monólogo adulto de 40 minutos.", "Diseñar asamblea breve con participación infantil real", "La participación construye ciudadanía temprana.", "La atención infantil no sostiene monólogos largos."],
      ["Se etiquetan 'listos' y 'atrasados' frente al grupo.", "Describir avances con lenguaje de proceso y metas próximas", "La evaluación formativa evita estigma.", "Las etiquetas limitan la ZDP percibida."],
      ["Falta material y se cancela toda exploración sensorial.", "Usar materiales del entorno y reciclados con intencionalidad", "La pobreza de recursos no anula la pedagogía.", "El entorno cercano es laboratorio."],
    ],
  },
  {
    esp: "matematicas",
    module: "Currículo y referentes MEN",
    tags: [
      {code: "ebc", focus: "matemáticas"},
      {code: "dba", focus: "grado"},
    ],
    items: [
      ["Se prohíbe explicar el procedimiento; solo importa la respuesta.", "Valorar y enseñar estrategias, justificación y verificación", "EBC: procesos matemáticos.", "La justificación revela comprensión."],
      ["Geometría se reduce a memorizar nombres de figuras.", "Explorar propiedades, composición/descomposición y argumentación", "Lineamientos: pensamiento espacial.", "Las propiedades importan más que la etiqueta."],
      ["Estadística aparece solo en la última semana del año.", "Distribuir recolección y lectura de datos a lo largo del año", "EBC incluyen pensamiento aleatorio/variacional según grado.", "Los datos necesitan tiempo de práctica."],
      ["Un estudiante usa estrategia distinta a la del tablero y se invalida.", "Validar estrategias correctas equivalentes y comparar eficiencia", "Múltiples estrategias son riqueza didáctica.", "Bruner: varias representaciones del mismo concepto."],
      ["La calculadora se prohíbe siempre, incluso en exploración de patrones.", "Usar herramientas con intencionalidad según la meta de aprendizaje", "La herramienta puede liberar atención para el razonamiento.", "La meta define si el instrumento ayuda o estorba."],
      ["Problemas 'trampa' se usan para confundir, no para enseñar.", "Diseñar problemas desafiantes con propósito formativo y andamiaje", "El reto debe estar en ZDP, no en la humillación.", "1290: evaluación al servicio del aprendizaje."],
      ["No hay conexión entre aritmética y situaciones de medida del entorno.", "Articular número, medida y estimación en contextos reales", "Los pensamientos matemáticos se integran.", "Ausubel: anclaje en experiencia."],
      ["La recuperación es otra lista de algoritmos sin diagnóstico.", "Diagnosticar errores conceptuales y reenseñar con representación", "Formativa: partir de evidencia del error.", "Sin diagnóstico, la recuperación es ritual."],
    ],
  },
  {
    esp: "lenguaje",
    module: "Currículo y referentes MEN",
    tags: [
      {code: "lineamientos", focus: "lenguaje"},
      {code: "ebc", focus: "comunicación"},
    ],
    items: [
      ["Se corrige la escritura solo con tinta roja y sin criterios de contenido.", "Retroalimentar ideas, organización, audiencia y luego convenciones", "La escritura es comunicación, no solo norma.", "Priorizar sentido + forma en espiral."],
      ["La biblioteca de aula está cerrada 'para que no se dañen los libros'.", "Circulares libros con acuerdos de cuidado y tiempo de lectura libre", "Sin acceso no hay hábito lector.", "La lectura voluminosa construye competencia."],
      ["Un texto literario se usa solo para sacar personajes y fechas.", "Trabajar interpretación, disfrutar estético y producir respuesta creativa", "Literatura forma sensibilidad y pensamiento.", "Reducir a ficha empobrece la experiencia."],
      ["No se enseña citación ética; se copia de internet sin crédito.", "Enseñar uso ético de fuentes y parafraseo según grado", "Competencia comunicativa incluye ética de la información.", "Copiar sin crédito no es producción."],
      ["La escucha nunca se enseña; solo se exige silencio.", "Diseñar tareas de escucha activa con propósito (tomar notas, responder, resumir)", "Escucha es práctica social del lenguaje.", "Silencio ≠ comprensión."],
      ["Se evalúa lectura solo con opción múltiple de detalle literal.", "Incluir inferencia, propósito del autor y evaluación del texto", "EBC: niveles de comprensión.", "Lo literal es piso, no techo."],
      ["Los estudiantes no saben para quién escriben.", "Explicitar audiencia y propósito antes de producir", "Género = propósito + audiencia + rasgos.", "Sin audiencia, el texto queda vacío."],
      ["Se ridiculiza la letra 'feá' en público.", "Acompañar legibilidad con respeto y metas formativas privadas", "El clima seguro habilita riesgo cognitivo.", "1620/49: prevenir hostigamiento también en aula académica."],
    ],
  },
  {
    esp: "directivos",
    module: "Gestión institucional y PEI",
    tags: [
      {code: "ley115", focus: "gestión"},
      {code: "decreto1860", focus: "gobierno escolar"},
    ],
    items: [
      ["El plan de mejoramiento institucional no tiene metas medibles ni responsables.", "Definir metas, indicadores, responsables y fechas de seguimiento", "La gestión requiere planeación con trazabilidad.", "Sin responsables, el plan es discurso."],
      ["Las actas del consejo académico no existen o están incompletas.", "Institucionalizar actas claras que registren decisiones pedagógicas", "1860: instancias con funcionamiento real.", "La memoria institucional evita repetición de errores."],
      ["Se prioriza ornamentación de eventos sobre tiempo de aula.", "Proteger tiempo de enseñanza-aprendizaje como bien público", "El núcleo del servicio es el aprendizaje.", "Los eventos deben servir, no desplazar, la pedagogía."],
      ["No hay inducción a docentes nuevos sobre PEI, SIEE y rutas.", "Diseñar inducción obligatoria con mentoría y documentos vivos", "1278/calidad: profesionalización desde el ingreso.", "La inducción reduce improvisación dañina."],
      ["La inclusión depende de 'buena voluntad' individual, no de política IE.", "Protocolizar PIAR, roles de apoyo y seguimiento institucional (1421)", "La inclusión es deber del establecimiento.", "Sin política, la carga cae en un solo docente."],
      ["Se usan datos de aprendizaje solo para ranking de grados.", "Usar datos para decisiones de acompañamiento y recursos", "Evaluación institucional formativa.", "El ranking tóxico no mejora la enseñanza."],
      ["Familias solo son citadas cuando hay sanción.", "Abrir canales de participación y escuela de padres con sentido pedagógico", "PEI y 1860: comunidad educativa.", "La alianza preventiva supera la citación punitiva."],
      ["El manual de convivencia no se revisa tras cambios de la Ley 1620.", "Actualizar con comité, participación y tipologías vigentes (Guía 49)", "El manual debe estar vivo y alineado.", "Un manual obsoleto genera respuestas ilegales o ineficaces."],
    ],
  },
];

let n = 0;
for (const block of specialtyMicro) {
  for (const row of block.items) {
    n += 1;
    const [caso, good, norma, theory] = row;
    wave3.push(
        gold({
          id: `oro-esp-${block.esp.slice(0, 3)}-m${n}`,
          module: block.module,
          subtema: `${block.esp} · caso situado ${n}`,
          cargo: block.esp,
          tagsCargo: block.esp === "lenguaje"
            ? ["lenguaje", "primaria"]
            : block.esp === "matematicas"
              ? ["matematicas", "primaria"]
              : [block.esp],
          caso,
          stem:
            n % 2 === 0
              ? "En esta especialidad, ¿qué decisión articula mejor norma, didáctica y contexto?"
              : "Cuál opción evita tanto el activismo vacío como la omisión de referentes de la especialidad?",
          options: [
            "Aplicar una corrección superficial (más tareas, charla o sanción) sin cambiar la mediación",
            good,
            "Forzar homogeneidad “para todos igual”, omitiendo trayectoria, ajustes o especificidad del área",
            "Priorizar producto/ritual (nota, ficha, evento) aunque no haya evidencia de aprendizaje esencial",
          ],
          correct: "B",
          norma,
          theory,
          wrong: {
            A: "Corrige la superficie y deja intacta la causa pedagógica.",
            C: "La igualdad formal niega la respuesta situada de la especialidad.",
            D: "El ritual evaluativo no garantiza el aprendizaje esencial.",
          },
          tags: block.tags,
          dif: 3,
          secs: 115,
        }),
    );
  }
}

module.exports = {wave3};
